### ISSUE TITLE
icqt removes higher frequencies

### ISSUE THREAD

**Issue by cpdomina** [librosa/librosa#1010]
#### Description
`icqt` does not recover higher frequencies. Is this expected behavior from cqt or inversion algorithm themselves, or maybe I am missing some parameter?

#### Steps/Code to Reproduce

```
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt


audio, sr = librosa.load(librosa.util.example_audio_file(), offset=10, duration=5, sr=44100)

D = librosa.amplitude_to_db(np.abs(librosa.stft(audio)), ref=np.max)
librosa.display.specshow(D, y_axis='log', sr=sr)
```
<img width="607" alt="original" src="https://user-images.githubusercontent.com/299011/67105801-5a735200-f1c1-11e9-82e5-c64881b07cb8.png">

```
cqt = librosa.cqt(audio, sr=sr)
y = librosa.icqt(cqt, sr=sr)

D = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)
librosa.display.specshow(D, y_axis='log', sr=sr)
```
<img width="614" alt="icqt" src="https://user-images.githubusercontent.com/299011/67105844-74149980-f1c1-11e9-9e3e-0fdc6e6e33e2.png">

#### Expected Results
Spectograms should be similar. 

Decreasing `hop_length` and increasing `n_bins`, `bins_per_octave` seems to make no difference.

#### Versions
Darwin-17.7.0-x86_64-i386-64bit
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.15.4
SciPy 1.2.1
librosa 0.7.1

**Comment by bmcfee** [comment]
> `icqt` does not recover higher frequencies. Is this expected behavior from cqt or inversion algorithm themselves, or maybe I am missing some parameter?

This is expected behavior.  The CQT by default will be limited to 7 octaves up from C1, so anything above that will not be represented and therefore not recovered by the icqt.

You can of course push the upper frequency limit higher, but you will eventually encounter a limit imposed by your chosen hop length: for the CQT to capture the signal reliably, successive windows need to overlap, and high frequencies have shorter windows.

**Comment by cpdomina** [comment]
Thanks for the explanation @bmcfee !
Closing the ticket
