### ISSUE TITLE
Faster resampling?

### ISSUE THREAD

**Issue by danpovey** [librosa/librosa#1012]
Guys,
I just wrote a utility for resampling audio data based on convolution from Torch, and it was about 8 times faster than librosa when using the same configuration (num_zeros and so on).  This is on CPU.
You can see it at this repo
https://github.com/danpovey/filtering
e.g. you can check it out and do
`cd tests; python3 ./test_resampler_speed.py`
to see.
  
I know you probably don't want a torch dependency but I don't think that was, likely, the key part, I think it was more about precomputing the coefficients as a tensor that can be applied directly  without interpolation.

Just something to bear in mind in the future in case any of your developers have the bandwidth.  I.e. that it's possible to do resampling significantly faster than what's there now.

```
mac:tests: python3 ./test_resampler_speed.py
our torch-filter filter size = {} torch.Size([1, 1, 274])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
T:b.shape = torch.Size([2, 5000]), c.shape = torch.Size([2, 10000])
Elapsed time for our torch-based resampler: 0.12666641599999995
R:b.shape = (2, 5000), c.shape = (2, 10000)
R:b.shape = (2, 5000), c.shape = (2, 10000)
R:b.shape = (2, 5000), c.shape = (2, 10000)
R:b.shape = (2, 5000), c.shape = (2, 10000)
R:b.shape = (2, 5000), c.shape = (2, 10000)
R:b.shape = (2, 5000), c.shape = (2, 10000)
R:b.shape = (2, 5000), c.shape = (2, 10000)
R:b.shape = (2, 5000), c.shape = (2, 10000)
R:b.shape = (2, 5000), c.shape = (2, 10000)
R:b.shape = (2, 5000), c.shape = (2, 10000)
Elapsed time for librosa resampler: 1.0655667419999997
.
```

**Comment by bmcfee** [comment]
Cool, thanks for this.  For the record, librosa doesn't directly implement resampling; it calls out to either resampy (for sinc interpolation resampling) or scipy (for fft or polyphase) resampling, so it might make more sense to compare directly to those.

It's also worth mentioning a few other things about benchmarking:

1. librosa uses resampy by default, which in turn uses jit compilation on the interpolation method.  The first call will be expensive since it includes a compilation, and subsequent calls with the same input types will be faster.
2. resampy implements a couple of different filters: a small one for "fast" resampling and a large one for high-quality.  It's worth comparing to those separately, and also measuring the resulting SNR of the resampled signal in each case.

**Comment by danpovey** [comment]
Oh sorry... part of me knew that, I think I thought I was commenting on the
resampy repo.
I'll make the same comment on resampy.
Yeah, I was using the high-quality one I believe and comparing with
something that, also used 64 zeros.

**Comment by danpovey** [comment]
I made the same comment on resampy now.
