### ISSUE TITLE
numba's DTW segfaults on NaN similarity

### ISSUE THREAD

**Issue by igneus-lau** [librosa/librosa#1014]
#### Description

The example code plot_music_sync.py from [https://librosa.github.io/librosa/auto_examples/plot_music_sync.html#sphx-glr-download-auto-examples-plot-music-sync-py](https://librosa.github.io/librosa/auto_examples/plot_music_sync.html#sphx-glr-download-auto-examples-plot-music-sync-py) runs fine with sir_duke_fast.mp3 and sir_duke_slow.mp3. But encounter segmentation fault when using other mp3 files.
#### Steps/Code to Reproduce
1. Replace 
```
x_1, fs = librosa.load('audio/sir_duke_fast.mp3')
```
to 
```
x_1, fs = librosa.load('audio/BFJazz_-_Stargazer_from_Texas.mp3')
```
in plot_music_sync.py.

2. Run plot_music_sync.py again and segmentation fault occurs.

3. The exception seems to be thrown from this line:
```
D, wp = librosa.sequence.dtw(X=x_1_chroma, Y=x_2_chroma, metric='cosine')
```

#### Expected Results

Python should exit without Segmentation fault: 11
#### Actual Results

/Users/igneus/.pyenv/versions/3.7.4/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
/Users/igneus/.pyenv/versions/3.7.4/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
Segmentation fault: 11
#### Versions

Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.4 (default, Sep 26 2019, 17:15:53)
[Clang 10.0.1 (clang-1001.0.46.4)]
NumPy 1.17.3
SciPy 1.3.1
librosa 0.7.1

**Comment by lostanlen** [comment]
Thank you for reporting. Can you please upload the audio file `BFJazz_-_Stargazer_from_Texas.mp3` and share the URL here?

**Comment by igneus-lau** [comment]
Thanks for your reply. I downloaded the audio file from this repository: https://github.com/librosa/librosa_gallery/tree/master/audio. It's the first one on the list.

**Comment by ArtemisZGL** [comment]
i wonder if there any potential problems when showing "UserWarning: PySoundFile failed. Trying audioread instead.", because i used librosa.load to load an audio which codec is mp3, container is wav.

**Comment by bmcfee** [comment]
It's almost certainly not an audio decoding issue. Please fill out the complete issue template with all dependency versions, so that we can diagnose the problem. My guess is that your numba installation has a problem somewhere.

**Comment by igneus-lau** [comment]
Here are the dependency versions I've installed:

Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.4 (default, Sep 26 2019, 17:15:53)
[Clang 10.0.1 (clang-1001.0.46.4)]
NumPy 1.17.3
SciPy 1.3.1
librosa 0.7.1
matplotlib 3.1.1
numba 0.46.0
audioread 2.1.8
scikit-learn 0.21.3
joblib 0.14.0
decorator 4.4.1
six 1.12.0
resampy 0.2.2
soundfile 0.10.2

**Comment by igneus-lau** [comment]
I tried to run this code in miniconda, same error occurs.

**Steps:**
1. $ conda create -n music
2. $ conda activate music
3. $ conda install -c conda-forge librosa
4. Replace 
`x_1, fs = librosa.load('audio/sir_duke_fast.mp3')`
with
`x_1, fs = librosa.load('audio/BFJazz_-_Stargazer_from_Texas.mp3')`
in plot_music_sync.py.
5. $ python plot_music_sync.py

**Actual Results**

/Users/igneus/opt/miniconda3/envs/music/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
/Users/igneus/opt/miniconda3/envs/music/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
Segmentation fault: 11

**Versions**

Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.17.3
SciPy 1.3.1
librosa 0.7.1
matplotlib 3.1.2
numba 0.46.0
audioread 2.1.8
scikit-learn 0.21.3
joblib 0.14.0
decorator 4.4.1
six 1.13.0
resampy 0.2.2
soundfile 0.10.2

**Comment by bmcfee** [comment]
I still suspect numba here.  If it's getting to the DTW line, then loading was not the problem.  Can you try rolling back to numba 0.45.1 to see if that fixes the problem?

**Comment by igneus-lau** [comment]
I tried to rollback numba to 0.45.1, but the same Segmentation fault error still exists.

Here's the versions and output:

$ python plot_music_sync.py
Darwin-19.0.0-x86_64-i386-64bit
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.17.3
SciPy 1.3.1
librosa 0.7.1
matplotlib 3.1.2
**numba 0.45.1**
audioread 2.1.8
scikit-learn 0.21.3
joblib 0.14.0
decorator 4.4.1
six 1.13.0
resampy 0.2.2
soundfile 0.10.2
/Users/igneus/opt/miniconda3/envs/music/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
/Users/igneus/opt/miniconda3/envs/music/lib/python3.7/site-packages/librosa/core/audio.py:146: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
**Segmentation fault: 11**

**Comment by bmcfee** [comment]
> I tried to rollback numba to 0.45.1, but the same Segmentation fault error still exists.
> 
> Here's the versions and output:

That's very weird.  Do other tracks also fail, or just this one?

**Comment by igneus-lau** [comment]
I tried 3 different mp3 files, all of them failed with same output.

**Comment by bmcfee** [comment]
Well I'm stumped. I very much doubt this is anything in our codebase, since we don't do anything directly dealing with memory allocation that could cause a segfault.

I think the next thing to do is to step through the example script one line at a time to narrow down the cause. After numba, the two most likely candidates (I think) would be audioread and matplotlib.  This leads to two not diagnostic questions:

- does the script work if you run it on a .wav input instead of .mp3? If so, it's a problem with audioread.
- does the script work on any input if you disable the plotting? If so, it's a problem with matplotlib.

**Comment by igneus-lau** [comment]
I converted mp3 files to wav, and remove all plotting code. Same segmentation fault error still exists.

Now the code is very simple:

```
from __future__ import print_function
import librosa

# a.wav is the original sir_duke_fast.mp3
x_1, fs = librosa.load('audio/a.wav')

# b.wav is the original BFJazz_-_Stargazer_from_Texas.mp3
x_2, fs = librosa.load('audio/b.wav')

n_fft = 4410
hop_size = 2205

x_1_chroma = librosa.feature.chroma_stft(y=x_1,
                                         sr=fs,
                                         tuning=0,
                                         norm=2,
                                         hop_length=hop_size,
                                         n_fft=n_fft)
x_2_chroma = librosa.feature.chroma_stft(y=x_2,
                                         sr=fs,
                                         tuning=0,
                                         norm=2,
                                         hop_length=hop_size,
                                         n_fft=n_fft)

# dtw line is where segmentation fault happens
D, wp = librosa.sequence.dtw(X=x_1_chroma, Y=x_2_chroma, metric='cosine')
```

**Comment by igneus-lau** [comment]
I converted the mp3 files to wav, and removed all plotting code. But the same segmentation error is still thrown from the dtw line. 

Now the code is very simple:

```
from __future__ import print_function
import librosa

x_1, fs_1 = librosa.load('audio/sir_duke_fast.wav')
x_2, fs_2 = librosa.load('audio/BFJazz_-_Stargazer_from_Texas.wav')

n_fft = 4410
hop_size = 2205

x_1_chroma = librosa.feature.chroma_stft(y=x_1,
                                         sr=fs_1,
                                         tuning=0,
                                         norm=2,
                                         hop_length=hop_size,
                                         n_fft=n_fft)
x_2_chroma = librosa.feature.chroma_stft(y=x_2,
                                         sr=fs_2,
                                         tuning=0,
                                         norm=2,
                                         hop_length=hop_size,
                                         n_fft=n_fft)

# dtw line is where segmentation fault happens
D, wp = librosa.sequence.dtw(X=x_1_chroma, Y=x_2_chroma, metric='cosine')
```

**Comment by bmcfee** [comment]
Thanks for the minimal example -- I can confirm that this is happening in my development environment as well.

I still suspect a numba bug, though it might also be due to the distance matrix calculation, which is in scipy.

```
INSTALLED VERSIONS
------------------
python: 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0]

librosa: 0.7.1

audioread: 2.1.8
numpy: 1.17.3
scipy: 1.3.0
sklearn: 0.21.2
joblib: 0.13.2
decorator: 4.4.0
six: 1.13.0
soundfile: 0.10.2
resampy: 0.2.2
numba: 0.44.1

numpydoc: 0.9.1
sphinx: 2.2.1
sphinx_rtd_theme: 0.4.2
sphinxcontrib.versioning: 2.2.1
sphinx-gallery: None
pytest: 3.10.1
pytest-mpl: None
pytest-cov: None
matplotlib: 3.1.1
presets: 0.1.3
```

**Comment by bmcfee** [comment]
Aha!  The problem appears to be down to the use of cosine distance when there are zero-vectors in the input.

```python
In [15]: C = scipy.spatial.distance.cdist(x_1_chroma.T, x_2_chroma.T, metric='cosine')                                                                                                        

In [16]: C                                                                                                                                                                                    
Out[16]: 
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])
```
This is because `x_2_chroma` has silent regions that produce all-zeros chroma vectors.  librosa's feature normalization is clever enough to detect numerical instability when trying to l2-normalize feature vectors, and it leaves them as unnormalized 0s.  The scipy distance calculator is not so clever though, and when it tries to compute cosine distance, will do an unstable normalization first, resulting in a 0/0 -> `nan` in the distance matrix.

Why this turns into a segfault is a total mystery to me, but it's easy enough to detect.

For now, I would suggest replacing `cosine` with `euclidean` or `sqeuclidean`; they'll give identical cost paths when normalization is not a problem, and will be numerically stable when normalization is a problem.  Making this change seems to fix the problem on my end.

---

## TODO

- Detect `nan`s in the distance matrix and raise an exception before calling into the numba-optimized DP function.

**Comment by 00sapo** [comment]
The same happens with 'braycurtis'

**Comment by bmcfee** [comment]
Digging into this a little more, it only seems to trigger when `backtrack=True`.

**Comment by bmcfee** [comment]
Upon closer inspection, requiring `isfinite` on the cost matrix is incompatible with our implementation of Sakoe-Chiba, which uses infs off the diagonal to constrain the solution path.  This is very tricky indeed...

**Comment by bmcfee** [comment]
The problem is indeed subtle, and I think it might be a regression introduced by #920 .  Tagging @fzalkow for input here.

What's happening is that the `D_steps` matrix is populated by default with `-1`, meaning that step sizes are assumed to be the last value of `step_sizes_sigma` until the cost accumulation replaces it with a better value.  By default, this corresponds to a move of `[1, 0]` (meaning up one row, stay in the same column).

Now, when the cost accumulator encounters a `nan` value (or an `inf`), the condition to replace the `D_steps` entry is never hit, so the default values propagate through.  When `subseq=False`, a full-path alignment must be constructed, so the path must cross through every row and every column, which means we must hit these nan/inf paths.  (This isn't a problem for Sakoe-Chiba, because we know exactly where the infs are and step around them in path construction.)

The segfault occurs because the exit condition of the backtracking loop needs to land exactly at `(0, 0)` (start-start), but the `D_steps` matrix is not guaranteed to have a path back to the origin.

We can fix this for the default step sizes by initializing `D_steps` to 0 for the center block, left-steps on the first row and up-steps on the first column.  (I think we should always have been doing this anyway!)  However, if the user supplies their own step_sizes array, this logic goes out the window and I'm not sure what we can do.

At this point, I'm open to creative solutions, because I'm not seeing a clean way to resolve this in general.  The options currently on the table:

- Require all costs to be finite.  If using global constraints, ignore those parts of the matrix when checking.
- Be more careful with `D_steps` initialization, though for user-supplied values, I'm not sure we can fix this in general.  Maybe we need more safety checks here?
- Somehow detect and skip over bad cost values in the accumulator.

Side note: I also discovered a separate bug, #1029 , which I've fixed locally and will roll into the PR for this one once we have a plan.

**Comment by bmcfee** [comment]
Some last thoughts on the options above:

- We should definitely relax the exit condition.  Step sizes can be provided by the user, and there's no way to guarantee that the origin is always reachable.  Instead of checking for hitting the origin, we can iterate as long as both coordinates are non-negative.  Tacking on a dummy path post-hoc is relatively easy, as there are only two ways to do it.

- I still think it's a good idea to at least warn the user when the cost matrix has nans.  Infs should be okay, but nan is deadly.

- Should we add restrictions to the step sizes array?  Right now we only check that the shapes are compatible with the additive and multiplicative weights, but we could probably be more careful.  For example:
   - These should always be integer valued.  (They're used in array index math.)
   - They should always be non-negative valued. (Corresponding to proper sub-problems.)
   - Other constraints?  Should we require that there's always an `[0, 1]` and `[1, 0]` (left and up, respectively) option?  This is sufficient to guarantee that the origin is always reachable from any candidate point, and I can't think of a good reason to not have these options when using DTW.

**Comment by fzalkow** [comment]
Hi all!

> The problem is indeed subtle, and I think it might be a regression introduced by #920. Tagging @fzalkow for input here.

You are right, that may be introduced in this commit. However, if we would reverse the standard step size order, I would guess the problem also existed before that commit.

> We should definitely relax the exit condition

Strictly speaking, a warping path needs to reach the cell `(0, 0)` to be valid.

> Other constraints? Should we require that there's always an `[0, 1]` and `[1, 0]` (left and up, respectively) option?

We often use the step sizes `[1, 1]`, `[2, 1]`, `[1, 2]`. This constrains the slope of the warping path and gives more stable results for certain cases. Of course if `N>2M` or `M>2N` (with `M` and `N` being the lengths of the sequences, respectively), then there is no valid warping path in this case. Probably the function does not exist properly in this case.

> I still think it's a good idea to at least warn the user when the cost matrix has nans. Infs should be okay, but nan is deadly.

We may even raise an exception at this point. Wouldn't that solve this issue? I cannot think of a case where you want to have `nans` in your cost matrix.

**Comment by bmcfee** [comment]
>  However, if we would reverse the standard step size order, I would guess the problem also existed before that commit.

Yup, I think the problem was always there, it just never popped up in testing.



> Strictly speaking, a warping path needs to reach the cell `(0, 0)` to be valid.

Only if we're doing full-sequence alignment.  Subsequence alignment doesn't need to hit 0,0.  To be clear, I wasn't suggesting to allow full-sequences to not hit 0,0, just that we could special case it to patch in a full solution outside that particular loop.





> We often use the step sizes `[1, 1]`, `[2, 1]`, `[1, 2]`. This constrains the slope of the warping path and gives more stable results for certain cases. Of course if `N>2M` or `M>2N` (with `M` and `N` being the lengths of the sequences, respectively), then there is no valid warping path in this case. Probably the function does not exist properly in this case.


Interesting -- this is exactly the sort of thing I was worried about.  Maybe if we hit that case, it throws a runtime error?  Sometimes a path might exist and sometimes it might not.  Having strict horizontal and vertical moves guarantees a solution, but it might not be necessary in all cases.



> We may even raise an exception at this point. Wouldn't that solve this issue? I cannot think of a case where you want to have `nans` in your cost matrix.

I think we could still run into the bug that triggered this discussion even if the matrix is all finite, so we should fix the loop condition / step size issue anyway.

I generally agree that nans are bad news here, but I can imagine some creative uses of them in subsequence alignment, eg if you want to put break points in a sequence across which the path should not cross.  But that's pretty esoteric and definitely not standard.

**Comment by fzalkow** [comment]
> Only if we're doing full-sequence alignment. Subsequence alignment doesn't need to hit 0,0.

Right! 

> Interesting -- this is exactly the sort of thing I was worried about. Maybe if we hit that case, it throws a runtime error? Sometimes a path might exist and sometimes it might not. Having strict horizontal and vertical moves guarantees a solution, but it might not be necessary in all cases.

I think we could catch that. First, calculating the maximal/minimal slope of the given step sizes, and, second, asserting a minimal/maximal relationship between `N` and `M`. Given that and a complete cost matrix (without infs or nans), there should always be a valid solution. I can work on a PR regarding the assertion.

> I can imagine some creative uses of them in subsequence alignment, eg if you want to put break points in a sequence across which the path should not cross.

We could still use infs here, even if we forbid nans. Of course, arbitrary infs could also screw up dtw.

**Comment by bmcfee** [comment]
> Given that and a complete cost matrix (without infs or nans), there should always be a valid solution.

This part gets a little dicey wrt Sakoe-Chiba though, since we implement that by infs.  I could also imagine a use-case where a user may want to code in their own inf patterns to represent forbidden paths other than Sakoe-Chiba, and if possible, I think we should allow for that.
