### ISSUE TITLE
librosa.core.tone returns wrong length

### ISSUE THREAD

**Issue by fromjupiter** [librosa/librosa#1053]
Here is my console output:

> >>> import librosa
> >>> wav = librosa.core.tone(440,44100,length=1740)
> >>> len(wav)
> 1741

I expect the output to be 1740.

**Comment by bmcfee** [comment]
Ah, how embarrassing!  Thanks for catching that.

This seems to be triggered by an edge case and depends on the sampling rate.  If you repeat the above with `sr=4410`, the length matches as expected.

I suppose this comes down to our use of `np.arange()` to generate the time steps, rather than `np.linspace`, where the number of points can be set exactly.  This should be easy enough to fix.

**Comment by fromjupiter** [comment]
Thank u Brian for the quick fix!
