### ISSUE TITLE
Better error message when using wrong number of FFT samples

### ISSUE THREAD

**Issue by JulianFerry** [librosa/librosa#1132]
When I call a FFT-related function with incorrect parameters, I run into the same error message which I find hard to interpret: `ValueError: range() arg 3 must not be zero`

Reproducible example:
```
import librosa
import numpy as np
audio = np.random.random(10000)
fft = librosa.stft(audio.astype('float64'), n_fft=100000)
```
returns:
```
/usr/local/Caskroom/miniconda/base/envs/deep-music/lib/python3.6/site-packages/librosa/core/spectrum.py in stft(y, n_fft, hop_length, win_length, window, center, dtype, pad_mode)
    233                                           stft_matrix.itemsize))
    234 
--> 235     for bl_s in range(0, stft_matrix.shape[1], n_columns):
    236         bl_t = min(bl_s + n_columns, stft_matrix.shape[1])
    237 

ValueError: range() arg 3 must not be zero
```

I was also getting the same error message with `librosa.cqt` but I can't remember what settings it was with. I was trying to maximise the frequency resolution (maximising n_bins and bins_per_octave) across a single time bin (hop_length=audio.shape[0]) so I imagine the cause of the error was the same as the one in my example above.

Could you please add an error message for this?

**Comment by bmcfee** [comment]
Thanks got noting that. A more helpful error message would certainly be appropriate here!

**Comment by JulianFerry** [comment]
Having never contributed to open source it didn't even occur to me I could PR this myself. I'm happy to give this a shot

**Comment by lostanlen** [comment]
@JulianFerry thank you for reporting. The way out of this is an error message explaining that the n_fft must be smaller than the length of the input.

FYI, n_fft=100000 is way too high in audio. You rarely ever see n_fft go above 2**13 = 8192.
Also, powers of two are preferable over powers of ten in this case: that's when the FFT algorithm is going to be fastest.

**Comment by JulianFerry** [comment]
> @JulianFerry thank you for reporting. The way out of this is an error message explaining that the n_fft must be smaller than the length of the input.
> 
> FYI, n_fft=100000 is way too high in audio. You rarely ever see n_fft go above 2**13 = 8192.
> Also, powers of two are preferable over powers of ten in this case: that's when the FFT algorithm is going to be fastest.

What surprised me is that n_fft can go above the length of the input without any errors - is this normal? E.g. setting n_fft=20000 here still runs fine. Also I would have expected n_fft=10000 (input length) to return an FFT with only one column but `fft.shape` returns `(5001, 5)`

 This were just toy numbers btw, but good to know about the powers of two thanks!

**Comment by bmcfee** [comment]
> is this normal?

In general, the frame length and signal length are more or less independent for an STFT.  It's not like a DFT where the number of samples dictates the number of frequencies you can analyze.



> Also I would have expected n_fft=10000 (input length) to return an FFT with only one column but `fft.shape` returns `(5001, 5)`

The number of frames depends primarily on the hop length, since that dictates the amount of overlap.  I think this is described well enough in the [stft docs](https://librosa.github.io/librosa/generated/librosa.core.stft.html?highlight=stft#librosa.core.stft) (under `hop_length`), but let me know if there's something unclear about it.

**Comment by JulianFerry** [comment]
> > is this normal?
> 
> In general, the frame length and signal length are more or less independent for an STFT. It's not like a DFT where the number of samples dictates the number of frequencies you can analyze.

I see, sorry that's a limitation of my understanding of the DFT and STFT algorithms then.

Would you be happy for me to submit a PR with an error message for this and a fix for #1132?
If yes, is this correct?
>n_fft must be smaller than the length of the input

or should it be ok to use n_fft > y.shape[0] since this currently doesn't throw an error?

**Comment by bmcfee** [comment]
> or should it be ok to use n_fft > y.shape[0] until it breaks, since this currently doesn't always throw an error?

Good question.  Right now, it's undefined behavior, so it could go either way, either:

1. Throw an error if `n_fft > len(y)`, or
2. zero-pad `y` out to fill at least one frame.  (This will also depend on centering behavior to determine the shape of the padding, but that's doable.)

I don't have strong opinions on this -- it took 7 years for this issue to surface, so I think it's a pretty unusual corner case.

(1) is obviously the easy solution.

(2) is nice theoretically; there's no reason this behavior shouldn't be defined.  Since we already do a little padding for frame centering, there's precedent for it.

@lostanlen what do you think?

**Comment by lostanlen** [comment]
I vote for (1). I work with bird calls, which are very short sounds (3k-10k samples). If i were to accidentally set an `n_fft` above the duration of the sound while computing the STFT, i would prefer to be notified, update my code, and start again; rather than to have librosa perform some padding under the hood without telling me.

@JulianFerry cases where n_fft is exactly equal to the input length are best addressed by `np.fft.fft`
https://numpy.org/doc/stable/reference/generated/numpy.fft.fft.html

**Comment by bmcfee** [comment]
> I vote for (1). I work with bird calls, which are very short sounds (3k-10k samples). If i were to accidentally set an `n_fft` above the duration of the sound while computing the STFT, i would prefer to be notified, update my code, and start again; rather than to have librosa perform some padding under the hood without telling me.

Implementing this now, and realized that it's a little more subtle than that.  The default behavior is to pad the signal by `n_fft//2` on either side, so you can only ever have `n_fft < len(y)` when `center=False`.

I don't think we should do this check before padding.  Maybe throw a warning if `n_fft > original length` and `center=True`, and exception if `center=False`?
