### ISSUE TITLE
Feature extractor: instantaneous frequency

### ISSUE THREAD

**Issue by turian** [librosa/librosa#1225]
**Is your feature request related to a problem? Please describe.**

[GANSynth](https://arxiv.org/abs/1902.08710) and [this work](https://www.math.ucdavis.edu/~saito/data/sonar/boashash1.pdf) discuss the instantaneous frequency. This would be a useful feature to extract.

**Describe the solution you'd like**

One simplified way to compute the IF, shared with me by @maxsolomonhenry, is as follows:

```
    cqt_ = librosa.cqt(y=y, sr=sr)
    IF = np.diff(np.unwrap(np.angle(cqt_)))
```

**Describe alternatives you've considered**

Search for alternate implementations, or not use this feature.

**Comment by bmcfee** [comment]
Librosa has always had instantaneous (linear) frequency, first in `ifgram` (now deprected and removed) and now in https://librosa.org/doc/latest/generated/librosa.reassigned_spectrogram.html?highlight=instantaneous%20frequency

We don't have it for CQT-based implementations, but since it's a one-liner to compute unwrapped phase differentials, I don't see a huge need to add it.

**Comment by lostanlen** [comment]
I agree with @bmcfee. The solution is so terse from librosa's internal functions that it doesn't warrant a new function of its own.

I will add that the IF estimation in the Boashash 1992 paper is not primarily based phase unwrapping, but on the statistical moment of the Wigner-Ville Distribution (see Equation 22).
