### ISSUE TITLE
`y_axis='mel'` argument in `specshow` results in incorrectly labeled units as well as incorrect y-axis ticks. 

### ISSUE THREAD

**Issue by wcneill** [librosa/librosa#1235]
Hello, 

I **think** I've found a bug, and if this is a mess up on my part, I apologize in advance. 

**Describe the bug**
It appears that the mel-scale spectrogram y-axis is displayed incorrectly when using `librosa.display.specshow()` with `y_axis='mel'` keyword argument. 

**The expected behavior is as follows:** If an original spectrogram `D` has frequency values ranging from 0 to ~5000, then the accompanying mel-spectrogram that is obtained by `librosa.feature.melspectrogram(S=D, sr=sr)` should have mel values ranging from 20 to ~2500. Using the `y_axis='mel'` argument should result in a y-axis that is on the 'mel' scale. The y-axis ticks can be scaled in any manner (log base 10 or log base 2 maybe), but most importantly the value range should be between 0 and roughly 2500. 

**Actual behavior is as follows:** The data is spread over a labeled range from 0 to ~10000 units. The y-axis appears to be in log base 2 scale, which is fine. However, the labeled units are Hz rather than mels, which is incorrect. 

**Summary:** The range of values (y-axis ticks) seems incorrect, and the label "Hz" should be converted to "Mels".

**To Reproduce**:
The following code will produce side by side of a standard spectrogram produced using `stft()` and a mel spectrogram which is produced using `librosa.feature.melspectrogram()` applied to the original `stft()` output. 
```
import librosa as li
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import scipy.signal as sig

# load sample audio
file = li.ex('trumpet')
aud, sr = li.load(file, sr=None)
n_ftt = 512
rsr = 11025

# apply low pass filter before downsampling. Attenuate at resample rate divided by 2.
cutoff = rsr / 2 
sos = sig.butter(10, cutoff, fs=sr, btype='lowpass', analog=False, output='sos')
aud = sig.sosfilt(sos, aud)

# downsample and update sample rate value
aud, sr = li.resample(aud, sr, rsr), rsr

# create both standard and mel spectrograms:
spec = li.stft(aud, n_fft=512, window=sig.windows.hamming)
spec = np.abs(spec)
mel_spec = li.feature.melspectrogram(S=spec, sr=11025)

# plot standard spectrogram and mel-scale spectrogram side by side:
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
specs = (li.amplitude_to_db(sp) for sp in (spec, mel_spec))
scales = ('hz', 'mel')

for i, (sp, sc) in enumerate(zip(specs, scales)):
        li.display.specshow(sp, x_axis='time', y_axis=sc, sr=sr, ax=axes[i])
       
plt.tight_layout()
plt.show()
```

**Screenshots**
This is the result of the "To Reproduce" code above:
![image](https://user-images.githubusercontent.com/54779308/91755534-1f330500-eb80-11ea-9c25-9e59000d1033.png)

**Software versions***
```
Windows-10-10.0.14393-SP0
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
NumPy 1.19.1
SciPy 1.5.2
librosa 0.8.0
INSTALLED VERSIONS
------------------
python: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]

librosa: 0.8.0

audioread: 2.1.8
numpy: 1.19.1
scipy: 1.5.2
sklearn: 0.23.2
joblib: 0.16.0
decorator: 4.4.2
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.50.1

numpydoc: None
sphinx: 3.1.1
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 6.0.1
pytest-mpl: None
pytest-cov: None
matplotlib: 3.3.0
presets: None


```

**Additional context**
That's it! Perhaps I'm missing something conceptually or there is an error in my code, but I think I've got everything right. If I've messed something up, I apologize for reporting this as a bug!

**Comment by lostanlen** [comment]
@wcneill this is intended behavior.

(1) thank you for the code. I can reproduce it.

(2) The reason why we don't offer the y-axis to be numbered in mels is that mels are less intepretable than Hertz as a physical unit. There is also considerable inconsistency across authors (see Umesh et al. "Fitting the mel scale" for a review. If you told me that a pitch is heard at, say, 2000 mels, i wouldn't know precisely the corresponding fundamental frequency: Beranek 1949 says that 2000 mels = 3120 Hz but Umesh 1999 says that 2000 mels = 3000 Hz. That's a pretty significant difference of almost a semitone (1/12th of an octave). The inevitable consequence is that, if we were to support mel as a physical unit, we'd have to support multiple fitting conventions (at least HTK and Slaney), so that would result in feature creep.

(3) What you describe is not a bug in the sense that the yticklabels are correct. If you really insist on having them not converted to Hertz, you can make a custom conversion with the `mel_to_hz` utility:

```python
yticks_mel = np.arange(0, 41, 5)
yticks_hz = librosa.mel_to_hz(yticks_mel)
plt.gca().set_yticks([], minor=True)
plt.gca().set_yticks(yticks_hz, minor=False)
plt.gca().set_yticklabels(yticks_mel)
plt.gca().set_ylabel("Mel (Slaney)")

plt.tight_layout()
plt.show()
```

Hopefully this will solve your problem.

**Comment by lostanlen** [comment]
However, i am realizing that the same approach does not work as nicely with HTK's MFCC.
![mel_htk](https://user-images.githubusercontent.com/3943142/91762062-3800e200-eba3-11ea-9e13-645447afb89f.png)

In this example, the mel-spectrogram is HTK, the tick-labels are HTK, but the stretching is Slaney. As a result, the yticks are not equally spaced.
I would guess that this is due to the fact that specshow does not have an `htk` keyword, and thus cannot propagate the `htk=True` setting to the `mel_frequencies` callsite in `__coord_mel_hz`
https://github.com/librosa/librosa/blob/main/librosa/display.py#L1132

**Comment by wcneill** [comment]
@lostanlen Thank you for the quick turn-around! It seems that I don't fully understand the theory. I knew that there was disagreement and different formulations on the Mel scale, but I don't seem to understand what a 'Hz' is in the context of the mel-spectrogram displayed by `specshow`. For example, why is the data spread out between 0 and 10000 'Hz'? This is very confusing behavior, as Hz has a very specific meaning in my mind (1/secs).

**Comment by bmcfee** [comment]
@wcneill maybe it would help to understand how this is all implemented under the hood.

When you say `y_axis='mel'`, specshow will calculate the center frequency (in Hz) of each mel band, based on the parameters (sampling rate, nfft, etc).  It will then render the spectrogram in natural (y-axis) coordinates, which in this case means Hz.  Finally, based on how the Slaney (default) filters are defined, it uses a linear axis warping below 1KHz, and a logarithmic warping above 1KHz (a `symlog` axis, in matplotlib speak) to stretch the rendered figure.  The reason we do it this way is so that the y-axis is always in Hz, and you can interact with the plot accordingly: eg by plotting f0 curves (also measured in hz), or highlighting frequency bands of interest, etc.  Similar things are done for linear stft, log-frequency stft, and cqt: the coordinates will all be transformed so that the resulting y-axis is in Hz.

**Comment by lostanlen** [comment]
so, should `specshow` support an `htk` optional argument?

**Comment by bmcfee** [comment]
> so, should `specshow` support an `htk` optional argument?

It feels a *little* bloaty, but I'd be okay with it.  It would just be a pass-through param at this line:
https://github.com/librosa/librosa/blob/7a5efc5f8b921db6ee8079b411629198c2154a18/librosa/display.py#L1266
