### ISSUE TITLE
Librosa Resampled output is introduced some artifact in the end

### ISSUE THREAD

**Issue by ranjithkumards** [librosa/librosa#1247]
Hi,
we are doing upsampling the input data(1364 bytes) of 8Khz data into 48KHZ, while doing so at the output file I am able to hear tik tik sound.
      
       chunk = 1364
      while True:
      data = f.read(chunk)
      if not data:
       break

      upsampledata= np.frombuffer(data,dtype=np.int16)
      upsampledata=upsampledata/32767
      upsampledata = upsampledata.astype(np.float32)
      upsampledata = librosa.resample(upsampledata, 8000, 48000,res_type='scipy',fix=True)

can anyone please explain the problem?

**Comment by bmcfee** [comment]
This type of question is better suited to our discussion forum: it's not a bug or feature request.

In general, it's not going to be easy for someone to diagnose this without access to the audio.  Does it happen with other resampling modes?

**Comment by ranjithkumards** [comment]
We tried with 8K to 32KHz , 8K to 22050Hz upsampling and observed same issue,also tried with removing scipy but issue not resolved.


 Later we tried with  increasing the data size to 4096 bytes from 1364 bytes then we found that resampled output is improved.

**Comment by ranjithkumards** [comment]
@bmcfee Here i have attached the upsampled output file for your  reference

**Comment by bmcfee** [comment]
I'm pretty confident that this is not an error, since `res_type='scipy'` punts all resampling operations directly to scipy's FFT-based resampler.  It may rather be a case of unexpected outcomes.  It looks like you might be trying to do a streaming sample rate conversion, working on blocks of audio independently?  If that's what you're doing, resampling is likely to introduce discontinuities at the frame boundaries.  You might want to consider using overlapping windows to smooth out these effects.

**Comment by ranjithkumards** [comment]
Dear Mr @bmcfee ,
Even I tried with 
res_type='kaiser_best'
res_type='kaiser_fast'
Result is not improved.

**working on blocks of audio independently?**
-->Yes we are doing frame by frame processing independently(streaming)

**consider using overlapping windows to smooth out these effects**
Can you please guide us to use which windowing and how?

Regards,
CGowda
