### ISSUE TITLE
CQT and MFCC calculation gives an additional vector

### ISSUE THREAD

**Issue by ktatar** [librosa/librosa#1264]
Hi all, 

MFCC and CQT calculations give an additional vector to the resulting array. Here is an example code:

`import librosa`
`import numpy as np`
`y = np.zeros(2560)`
`sr = 44100`
`C = librosa.cqt(y, sr=sr, hop_length=256, n_bins=384, bins_per_octave=48)`
`M = librosa.feature.mfcc(y=y, sr=sr, hop_length=256, n_mfcc=80 )`
`print('CQT array shape: {}\nMFCC array shape{}'.format(C.shape, M.shape))`

Here, the audio length is 2560 samples, and the hop-size is 256. This code should generate 10 vectors calculated from 10 blocks separated by 256 samples, but I end up with 11. Anyone know why? It seems like it has sth do with the windowing, maybe I am missing sth here? If I calculate the audio back using icqt, I end up with a numpy array with 2560 samples, so it seems consistent within the librosa. Any insights about this?

**Comment by lostanlen** [comment]
Hello @ktatar, this is due to padding and to the fact that MFCC and CQT operate on centered frames. 
See the center keyworg argument in STFT documentation: https://librosa.org/doc/latest/generated/librosa.stft.html#librosa.stft

To put it simply:
```
the 1st vector is centered around sample 0
the 2nd vector is centered around sample 256
the 3rd vector is centered around sample 512
...
etc.
...
the 10th vector is centered around sample 2304
the 11th vector is centered around sample 2560
```

If you need 10 vectors, you can do this outside of librosa with custom code for padding / truncating the input and post-processing the result.


If you care strongly about getting the exact same length after a round trip of cqt and icqt, make sure to pass `length=len(y)` to icqt: https://librosa.org/doc/latest/generated/librosa.icqt.html#librosa.icqt

**Comment by ktatar** [comment]
Thanks for the reply @lostanlen.

I see, so the 1st vector is padded on the left with the reflection of the signal and the last vector is padded at the end, which gives the extra CQT vector. My issue is that I just need to know exactly which samples the CQT vector is calculated from. 

As a possible solution, I guess I could just add a zero-padding in the beginning of the signal with a size hop_size / 2, and omit the first vector of the CQT matrix calculated from librosa.cqt. Do you think that would work?

**Comment by bmcfee** [comment]
> As a possible solution, I guess I could just add a zero-padding in the beginning of the signal with a size hop_size / 2, and omit the first vector of the CQT matrix calculated from librosa.cqt. Do you think that would work?

The padding is not a function of the hop size, so this probably would not work.

What I would recommend for this, as recently mentioned on the discussion forum, is to calculate the filter lengths for the CQT using librosa.filters.constantq_lengths , which will not *exactly* correspond to the cqt as implemented (due to recursive downsampling), but should be close enough to tell you how many samples each basis filter touches.  As all filters responses for frame index `t` are centered at `sample = hop_length * t`, this should give you everything you need.
