### ISSUE TITLE
Strange Viterbi (discriminative) decoding results (including probabilities greater than 1)

### ISSUE THREAD

**Issue by mlaugharn** [librosa/librosa#1268]
**Describe the bug**
Trying to do Viterbi decoding and ran into the decoding algorithm producing results that both contradict common sense and also produces log-probabilities greater than 0 (ie probabilities greater than 1).

**To Reproduce**
```

import numpy as np

transition_matrix = np.array(
    [[.999, 0.001],
     [0.001, .999]])
p_state = np.array([0.9, 0.1])
probs = np.array([0.4, 0.07, 0.2, 0.3, 0.1])
probs = np.stack((1-probs,probs))

import librosa

states, logp = librosa.sequence.viterbi_discriminative(probs, transition_matrix, p_state, p_init=probs[:,0], return_logp=True)

print(states)
print(f"probability {np.exp(logp)}")

>>> [1 1 1 1 1]
>>> probability 6.693160293126715

```

**Expected behavior**
Probability should be at most 1? (Also, isn't state 0 more likely than state 1?)

**Software versions***

Please run the following Python code snippet and paste the output below.
```
Darwin-19.6.0-x86_64-i386-64bit
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.18.1
SciPy 1.4.1
librosa 0.8.0
INSTALLED VERSIONS
------------------
python: 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]

librosa: 0.8.0

audioread: 2.1.9
numpy: 1.18.1
scipy: 1.4.1
sklearn: 0.22.1
joblib: 0.14.1
decorator: 4.4.1
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.48.0

numpydoc: 0.9.2
sphinx: 2.4.0
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 5.3.5
pytest-mpl: None
pytest-cov: None
matplotlib: 3.1.3
presets: None
```

**Comment by bmcfee** [comment]
This is not a bug, but I do think the documentation could be clearer.

Discriminative Viterbi differs from standard Viterbi in that it's trying to maximize `P[state | obs]` rather than `P[obs | state]`.  You can use Bayes' rule to convert between these two, which will introduce a normalization factor of `P[obs]`.  Since this is constant with respect to the choice of the state sequence (it's marginalized out), it is not included in the calculation.  The resulting "log probabilities" are unnormalized, and may be better thought of as energy than log-probability, as is common in the conditional random fields literature.

Probably we should document this more clearly -- any takers?
