### ISSUE TITLE
Possibility to save a mel-spectrogram as an image, and then load that image back as a mel-spectrogram.

### ISSUE THREAD

**Issue by DerpyMan101** [librosa/librosa#1282]
I know you can use librosa.feature.melspectrogram() to generate mel-spectrograms of audio, but what about being able to save the mel-spectrogram as an image, and then being able to load that image back as a mel-spectrogram. So you can reconstruct audio from mel-spectrogram images?

**Comment by bmcfee** [comment]
If you're using a lossless image encoding format, there's no reason it shouldn't work, notwithstanding any quantization artifacts that arise when converting from floating point to 8 bit intensity values.

If you're using a lossy format (eg, jpeg), there will be additional artifacts due to compression.

You probably shouldn't expect it to sound great, but it's definitely possible.

**Comment by amirhmk** [comment]
This would be a great feature to have, as working with `Matplotlib` and `savefigure` is very costly and inefficient. Is there another way of achieving this?
