### ISSUE TITLE
Maybe I found and fix a bug in librosa.display

### ISSUE THREAD

**Issue by unbadfish** [librosa/librosa#1283]
Hi, Librosa Team:
As I mentioned in Issue  #1261 and Issue  #1243, the fig with a `cqt_note` y-axis didn't behave as I expect. So I read the code and matplotlib's document. Then I found some mistakes. After that, I use some code to correct them:

1. In `/librosa/display.py#L216` (the formatter of y-axis), the contributor wrote:https://github.com/librosa/librosa/blob/a53fa56bdb6695a994008d5b6ccd0100870a6036/librosa/display.py#L216, with a `int(x)` , in fact, this made the ticks away from where they should stay. My suggest is to delete the `int()` and use the float data instead.

2. In `/librosa/display.py#L1064`(the locator of y-axis), the contributor wrote:https://github.com/librosa/librosa/blob/a53fa56bdb6695a994008d5b6ccd0100870a6036/librosa/display.py#L1064, In my opinion, this doesn't make sense. I think we should use `FixedLocator(librosa.cqt_frequencies(85, fmin=librosa.note_to_hz('C1')))` instead, because `cqt_frequencies` is designed to compute the center frequencies of Constant-Q bins. See: https://github.com/librosa/librosa/blob/a53fa56bdb6695a994008d5b6ccd0100870a6036/librosa/core/convert.py#L1105-L1140

My full code:
```python
def set_axis(ax) -> None:
    """call AFTER you draw!!
    =========================
    Args:
        ax : Axes
    Returns:
        None
    """
    from matplotlib.ticker import LogLocator, FixedLocator
    from matplotlib.ticker import FuncFormatter

    def _major_fomatter(x, pos):
        """Fomatter for major ticks"""
        # print('MAJOR  ' + str(x) + '  ' + str(librosa.hz_to_note(x, octave=True, cents=True)))
        if x <= 0:
            return ""
        else:
            return librosa.hz_to_note(x, octave=True, cents=True)  # necessary for cents
            # return librosa.hz_to_note(x, octave=True, cents=False)

    def _minor_fomatter(x, pos):
        """Fomatter for minor ticks"""
        # print('MINOR  ' + str(x) + '  ' + str(librosa.hz_to_note(x, octave=True, cents=True)))
        if x <= 0:
            return ""
        vmin, vmax = ax.yaxis.get_view_interval()
        if vmax > 4 * max(1, vmin):
            return ""
        # return librosa.hz_to_note(x, octave=True, cents=True)  # debug
        return librosa.hz_to_note(x, octave=True, cents=False)
    """=Set Locator & Fomatter="""
    # log_C1 = np.log2(librosa.note_to_hz("C1"));
    # offset = 2.0 ** (log_C1 - np.floor(log_C1))
    offset = librosa.note_to_hz("C1") / 32
    ax.yaxis.set_major_locator(LogLocator(base=2.0, subs=(offset,)))
    ax.yaxis.set_minor_locator(
        FixedLocator(librosa.cqt_frequencies(
            85, fmin=librosa.note_to_hz('C1')))
    )
    ax.yaxis.set_major_formatter(_major_fomatter)
    ax.yaxis.set_minor_formatter(_minor_fomatter)
    return None
```

I didn't read the source code so carefully, and that's why I don't want to put my code into the librosa package by a PR.
If anyone have a good idea, feel free to make your own PR, just remember @unbadfish in you PR.

@bmcfee , I think I fix the "bug" I found

**Comment by bmcfee** [comment]
Thanks for the deep dive into this bit of code!

>     1. My suggest is to delete the `int()` and use the float data instead.

I agree that `int()` here is weird. I'm not sure why it was ever in there.  It looks like it crept in when I converted everything from using `image` to `pcolormesh`, but for no good reason.



>     2\. I think we should use `FixedLocator(librosa.cqt_frequencies(85, fmin=librosa.note_to_hz('C1')))` instead, because `cqt_frequencies` is designed to compute the center frequencies of Constant-Q bins.

LogLocator was a convenience choice here, more than anything else, and it works because in 12TET with A440, every `C` lands near an integral power of 2.  If you look a few lines up though, we do actually correct for the deviation here: https://github.com/librosa/librosa/blob/a53fa56bdb6695a994008d5b6ccd0100870a6036/librosa/display.py#L1060  so that ticks are evenly spaced over the octaves starting at `C1`; I think this part is correct as is.

**Comment by bmcfee** [comment]
Quick follow-up: the benefit of log-locator over fixedlocator is that it when you zoom in, it will mark up the in-between positions.  Eg:

![image](https://user-images.githubusercontent.com/1190540/108869245-018da800-75c5-11eb-926b-6a2860a78793.png)

If you use a FixedLocator, it won't be able to handle zooming.

**Comment by unbadfish** [comment]
@bmcfee If the LogLocator is better, we can provide `LogLocator(base=2.0, subs=offset * (2.0 ** (np.arange(1, 12) / 12)))` to y-axis.
Here is how it behave:(`*` was added for debug)
![Figure_1](https://user-images.githubusercontent.com/61961263/109311458-d2a35a80-7880-11eb-9a4a-9ae82fa59e28.png)
So my func should be changed to:
```python
def set_axis(ax) -> None:
    """call AFTER you draw!!
    =========================
    Args:
        ax : Axes
    Returns:
        None
    """

    def _major_fomatter(x, pos):
        """Fomatter for major ticks"""
        # print('MAJOR  ' + str(x) + '  ' + str(librosa.hz_to_note(x, octave=True, cents=True)))
        if x <= 0:
            return ""
        else:
            return librosa.hz_to_note(x, octave=True, cents=True)
            # return librosa.hz_to_note(x, octave=True, cents=False)

    def _minor_fomatter(x, pos):
        """Fomatter for minor ticks"""
        # print('MINOR  ' + str(x) + '  ' + str(librosa.hz_to_note(x, octave=True, cents=True)))
        if x <= 0:
            return ""
        vmin, vmax = ax.yaxis.get_view_interval()
        if vmax > 4 * max(1, vmin):
            return ""
        # return '*' + librosa.hz_to_note(x, octave=True, cents=True)  # debug
        return librosa.hz_to_note(x, octave=True, cents=False)
    """=Set Locator & Fomatter="""
    # log_C1 = np.log2(librosa.note_to_hz("C1"));
    # offset = 2.0 ** (log_C1 - np.floor(log_C1))
    offset = librosa.note_to_hz("C1") / 32
    ax.yaxis.set_major_locator(LogLocator(base=2.0, subs=(offset,)))
    ax.yaxis.set_minor_locator(
        # FixedLocator(librosa.cqt_frequencies(
        #     85, fmin=librosa.note_to_hz('C1')))
        LogLocator(base=2.0, subs=offset * (2.0 ** (np.arange(1, 12) / 12)))
    )
    ax.yaxis.set_major_formatter(_major_fomatter)
    ax.yaxis.set_minor_formatter(_minor_fomatter)
    return None
```
Also I suggest that we could simplify `log_C1 = np.log2(librosa.note_to_hz("C1"));offset = 2.0 ** (log_C1 - np.floor(log_C1))` to `offset = librosa.note_to_hz("C1") / 32`, they are EXACTLY the same.

**Comment by bmcfee** [comment]
@unbadfish looks like we're hacking this at the same time today! :grin: 

Thanks for catching the missing offset in the minor locator!  That indeed looks like the key issue here.  Curiously, the cqt_svara decorator has this correct, but the cqt_note and hz versions do not.  I can roll this into a PR.


I dropped the `int(x)` in hz_to_note, with the following result:
![image](https://user-images.githubusercontent.com/1190540/109312201-c2ee2c80-7814-11eb-8b10-eff5bc21f110.png)

At this point, the bottom ticker looks correct, but you might think the intermediate ticks look strange.  Here's what's going on::

- For CQT spectra, the mesh coordinates are specified as boundaries of each frequency band, not the center frequencies.  This is because `flat` shading mode in pcolormesh (the default) requires coordinates in this format. 
- To calculate the mesh coordinates, we generate n+1 cqt frequencies, starting one half bin below fmin.  This should locate the center of each bin at the correct frequency in the data coordinate space.
- If we use `nearest` format, we could have centered bins without all this half-bin nonsense.  `nearest` mode was only added in matplotlib 3.3, and it would be my preference to switch over to this, but it does require a bump to the minimum matplotlib version we can require.  I'm not opposed to that, but it should wait for the 0.9 release of librosa, at which point we can probably simplify a lot of this code.


> Also I suggest that we could simplify `log_C1 = np.log2(librosa.note_to_hz("C1"));offset = 2.0 ** (log_C1 - np.floor(log_C1))` to `offset = librosa.note_to_hz("C1") / 32`, they are EXACTLY the same.

We could, but since they're exactly the same, it wouldn't change anything.  OTOH, there is a similar bit of logic for `cqt_svara`, where it is actually helpful for readability (in my opinion) to have the calculation broken out in this way.  For parity across the different cqt display modes, I'd prefer to keep it as is.
