### ISSUE TITLE
Vocal separation example code has an issue with playable audio reconstruction

### ISSUE THREAD

**Issue by interactiveaudiolab** [librosa/librosa#1285]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
The website tutorial for "https://librosa.org/doc/main/auto_examples/plot_vocal_separation.html" shows doing masking on the magnitude spectrogram, which is fine for display...but if you reconstruct the audio from the masked magnitude spectrogram, you get distortions because the phase is gone. 

**To Reproduce**
Just have a look at the page: https://librosa.org/doc/main/auto_examples/plot_vocal_separation.html

The mask is applied to the S_full variable, which is the magnitude spectrogram. You should show how to reconstruct the audio from applying the mask to the complex-value spectrogram.

**Comment by bmcfee** [comment]
Audio reconstruction was not included in the demo because, to the best of my knowledge, sphinx-gallery doesn't provide a mechanism for capturing and rendering audio output within the demo.

However, I agree that it would be nice to expand the demo to explain how one would go about recovering the audio, even if it can't be rendered directly to the browser.  In this case, it should be as simple as adding a line:

```python
y_foreground = librosa.istft(S_foreground * phase)
```

**Comment by bmcfee** [comment]
Just a heads up that i'll roll this change into the general documentation audit PR for the 0.8.1 release.
