### ISSUE TITLE
Memory usage is growing with the iterations

### ISSUE THREAD

**Issue by vincent-powder** [librosa/librosa#1286]
**Describe the bug**

Memory usage is growing with iterations.

**To Reproduce**

It should work with any kind of audio file but I can send the considered file if needed.

```
import librosa
import matplotlib.pyplot as plt
import os
import psutil

def foo():
    y, sr = librosa.load("clip_04.wav", sr=22050, offset=600, duration=60)
    spec_mag = abs(librosa.stft(y, n_fft=2048, hop_length=1024))
    spec_db = librosa.amplitude_to_db(spec_mag)
    return 42

def main():

    process = psutil.Process(os.getpid())

    array = []

    for i in range(100):
        print(i)
        foo()
        m = int(process.memory_info().rss / 1024**2)
        array.append(m)

    plt.figure()
    plt.plot(array)
    plt.xlabel('iterations')
    plt.ylabel('MB')
    plt.show()

if __name__ == '__main__':
    main()
```

**Expected behavior**

Memory usage should be constant.

**Screenshots**

<img width="642" alt="Screenshot 2021-02-21 at 15 47 46" src="https://user-images.githubusercontent.com/71759178/108687283-d3419700-74f6-11eb-9fee-06443e6463f7.png">

**Software versions**

```
Darwin-19.6.0-x86_64-i386-64bit
Python 3.7.9 (default, Aug 31 2020, 07:22:35) 
[Clang 10.0.0 ]
NumPy 1.19.5
SciPy 1.5.2
librosa 0.8.0
INSTALLED VERSIONS
------------------
python: 3.7.9 (default, Aug 31 2020, 07:22:35) 
[Clang 10.0.0 ]

librosa: 0.8.0

audioread: 2.1.8
numpy: 1.19.5
scipy: 1.5.2
sklearn: 0.23.2
joblib: 0.17.0
decorator: 4.4.2
soundfile: 0.10.2
resampy: 0.2.2
numba: 0.51.2

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.2
presets: None
```

**Comment by bmcfee** [comment]
Thanks for reporting this.  I haven't been able to reproduce your plot on my machine, but this may be because there are several variables at play that may be confounding the results.  Specifically:

- I don't have your input file, and it's not clear if it's natively at 22K or some other rate.  This matters because if it's already at 22K, the sample rate conversion code will be bypassed, and that might be a source of leakage.
  - I doubt this is the issue though, since I modified your example to force resampling on my machine, and get a flat memory curve as expected.
- The `offset` parameters may or may not be responsible here, depending on which audio decoding backend is being used.  I don't think this is an issue here, since you're using wav and have the `soundfile` package installed.
  - If you were using a different format (`mp3`), then librosa would revert back to `audioread` as a decoder, which forces decoding up to `offset` rather than seeking to the appropriate point in the file.  This too could be a source of memory consumption, though python should handle this for us.
- Do you still see increasing memory consumption if the STFT and dB lines are removed, so you're just loading the file and returning immediately?  My hunch is yes, given that my local copy retains those features and has flat consumption.  If so, that means we can isolate the problem within the audio loading part.

Assuming that the problem can be reduced to `load`, my hunch is that it's not librosa's fault, but instead due to `soundfile` not cleaning up its memory allocations.  This is just a guess, though, based on the fact that librosa is (numba aside) purely python, and does not deal with memory allocation directly at any point.  You could test this more specifically by calling `soundfile.read` directly instead of going through `librosa.load`.  

If the problem cannot be reduced to `load`, then we'll have more digging to do.

**Comment by vincent-powder** [comment]
Thanks for investigating the problem. 

First, let me say that I'm on a macbook pro.

To answer your questions.

The input file is at 22050 HZ:

```
(ml) ➜  debug_librosa ffprobe /path/to/the/clip_04.wav 
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with clang version 10.0.1
  configuration: --prefix=/Users/vincent/opt/anaconda3/envs/ml --cc=x86_64-apple-darwin13.4.0-clang --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, wav, from '/path/to/the/clip_04.wav':
  Metadata:
    encoder         : Lavf58.45.100
  Duration: 00:16:40.00, bitrate: 352 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, 1 channels, s16, 352 kb/s
```

First, I'm going to comment the stft and amplitude_to_db portion of the code.

All of the following values are for a 1000 iterations.

- `soundfile.read("clip_04.wav")` -> flat memory usage at 313MB

- `librosa.load("clip_04.wav", sr=22050, offset=600, duration=60)` -> increasing memory usage up to 210MB (can vary)

- `librosa.load("clip_04.wav", offset=600, duration=60)` -> increasing memory usage up to 190MB

- `librosa.load("clip_04.wav", sr=22050, duration=60)` -> increasing memory usage up to 190MB

- `librosa.load("clip_04.wav", sr=22050, offset=600)` -> flat memory usage at 187MB

So, the duration option seems to have an impact.


Now, if I add the stft function, memory goes up to 273MB. And if I add the amplitude_to_db function, memory goes up to 417MB.

**Comment by bmcfee** [comment]
> So, the duration option seems to have an impact.

It's also worth testing `soundfile.read()` with offset and duration constraints, eg as done inside load:
https://github.com/librosa/librosa/blob/790690cc604eec6092ad9a603c5e99be2b3f923b/librosa/core/audio.py#L146-L157

FWIW, my local run with duration parameter still exhibits a flat memory curve.  I'm on linux (I don't have an osx device to test with), so there may be platform-specific things at play here.


> Now, if I add the stft function, memory goes up to 273MB. And if I add the amplitude_to_db function, memory goes up to 417MB.

This makes sense because it's allocating output arrays.  But is it growing over time with successive calls?

At this point, I have two guesses to what's going on:

1. Soundfile is somehow leaking memory, eg by leaving open file descriptors. (This has happened before, but AFAIK there are no current issues with this.)
2. Old output arrays are still occupying space, but no longer referenced.  If this is the case, calling the python garbage collector in between runs would flatten the curve (probably with significant slow-down).

Librosa generally does not maintain state across function calls, except when streaming (obviously) and when using the cache interface, so I'm pretty confident that if there are leaks, it's outside of our jurisdiction.  But it would be good to know where exactly.

**Comment by vincent-powder** [comment]
I'll try to use `soundfile.read()` with offset and duration constraints.
I'll post here the results of my findings.
Thanks again for helping me on this.

**Comment by vincent-powder** [comment]
Hello @bmcfee,
I've used the code you've sent to read the wav file and here are my findings:
- If I read the entire wav file, the memory usage is constant
- If I use an offset, the memory usage is constant
- If I use a custom duration, the memory usage increases
As you pointed out, the problem is probably not related to Librosa.
Thanks again for investigating.
