### ISSUE TITLE
Add a normalize flag for librosa.onset.onset_detect

### ISSUE THREAD

**Issue by jrobchin** [librosa/librosa#1291]
**Is your feature request related to a problem? Please describe.**
`librosa.onset.onset_detect` normalizes the onset_envelope by default, which means that I get different results based on how much of a clip I use. Although I understand the purpose of this, in my case I don't want this normalized.

**Describe the solution you'd like**
Add a flag, e.g. `normalize` to `librosa.onset.onset_detect`, defaulting to True for backwards compatability.

```
def onset_detect(y=None, sr=22050, onset_envelope=None, hop_length=512,
                 backtrack=False, energy=None,
                 units='frames', normalize=True, **kwargs):
    # First, get the frame->beat strength profile if we don't already have one
    if onset_envelope is None:
        if y is None:
            raise ParameterError('y or onset_envelope must be provided')

        onset_envelope = onset_strength(y=y, sr=sr, hop_length=hop_length)

    # Shift onset envelope up to be non-negative
    # (a common normalization step to make the threshold more consistent)
    onset_envelope -= onset_envelope.min()

    # Do we have any onsets to grab?
    if not onset_envelope.any():
        return np.array([], dtype=np.int)

    # Add check for normalize flag
    if normalize:
        # Normalize onset strength function to [0, 1] range
        onset_envelope /= onset_envelope.max()

    ...

    return onsets
```

**Describe alternatives you've considered**
I currently reimplement `onset_detect` without the normalize step.

**Additional context**
I'd be happy to make a PR for this.

**Comment by bmcfee** [comment]
Thanks for raising this issue.  I agree that this should be optional.  A couple of points though:

- The `peak_pick` method is almost entirely relative, with the exception of the `delta` parameter.  A global scaling of the envelope should not change its behavior if we scale delta accordingly.
- If you're seeing different results for different subsequences of a signal, this might be a scaling issue, but it might also just derive from how the peak picker is defined.  It's not a purely local operation, and there is some suppression that happens around detected peaks.
- The line a few steps up from normalization (min-subtraction) should not be an in-place operation, since oenv can be passed in by reference from the user.  This is independent of the current issue, but if we're fixing normalization, we should fix this one too.



>  I'd be happy to make a PR for this.

That would be very much appreciated!

**Comment by jrobchin** [comment]
In my case, I'm setting parameters for peak picking, so I got different results depending on the section if the sample. Maybe it's a bit of an edge case but there was no indication of why that was happening without looking at the source.

I'll take a look at your point 3 as well and work on a PR when I get a chance. :)

**Comment by bmcfee** [comment]
It occurs to me that this in-place modification is actually a bug that we should fix in the short term.  I'll roll up a PR for this issue and slide it into the 0.8.1 release.
