### ISSUE TITLE
Self-similarity plots in docs are not square

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#1299]
**Describe the bug**
Small nitpick, but it's a bit upsetting that the self-similarity plots in our [specshow docs](https://librosa.org/doc/latest/auto_examples/plot_display.html#non-spectral-data) page have a default rectangular aspect ratio instead of being enforced as squares.

**To Reproduce**
![Screenshot 2021-04-02 at 17 10 00](https://user-images.githubusercontent.com/3943142/113428128-85ae2900-93d6-11eb-86f4-1cdd115de974.png)

and likewise for chroma covariance right below:
![Screenshot 2021-04-02 at 17 10 06](https://user-images.githubusercontent.com/3943142/113428137-88a91980-93d6-11eb-8807-06e4e0765a90.png)

(while we're at it, it would be good to make sure that the colorbar is zero-centered on that second plot)

**Software versions***
Librosa 0.8

**Additional context**
good first issue for librosa newcomers

**Comment by bmcfee** [comment]
I wonder if it makes sense in `specshow` to set `aspect='equal'` when the x- and y- axes are the same scale? (eg, chroma-by-chroma or time-by-time)

**Comment by lostanlen** [comment]
ooh, yes, having `specshow` take care of aspect rartio automatically would be really neat. 👍🏻

**Comment by dorukhansergin** [comment]
Hi, is anyone working on this? If not, I can work on it.

**Comment by lostanlen** [comment]
your contribution is welcome, @dorukhansergin !

**Comment by dorukhansergin** [comment]
@lostanlen thank you! I did some work on this. Before I proceed with the PR, I want to clear a few things up.

First, there is one more example in that docs page that needs to be squared, which is the second chroma cov plot under the [Color Maps](https://librosa.org/doc/latest/auto_examples/plot_display.html#color-maps) section. I consider that too as a target of this PR, right?

This brings us to the following comment:
> (while we're at it, it would be good to make sure that the colorbar is zero-centered on that second plot)
I don't think we should do this because the second chroma cov plot I mentioned above does this already to demonstrate how to pass `matplotlib.pyplot.pcolormesh` kwargs to specshow. So the first chroma cov plot should intentionally be left non zero-centered.

Second, is about the following comment from @lostanlen :
> ooh, yes, having specshow take care of aspect rartio automatically would be really neat. +1

Normally, I'd fix this problem by making necessary changes only in [`./docs/examples/plot_display.py`](https://github.com/librosa/librosa/blob/ceb862f/docs/examples/plot_display.py), because I think putting too much responsibility into the `specshow` function is not a good practice. But I assume you think this is the best API experience so I propose the following addition to the function:
```python
# If the plot is a self-similarity plot, square it
if (x_axis == y_axis) and (x_axis is not None):
    axes.autoscale(tight=True)
    axes.set_aspect('equal')
```

My assumption is that **if the two axes are semantically the same, we consider that as a self-similarity**. I could not think of a counterexample so let me know if there is any. I'm also unpleasantly surprised to find out that `None == None` returns `True` in Python 😃 so I added that to the if clause too, should the user won't pass these arguments and they default to `None`.

The updated plot looks like this. I fitted a square on the lower right post-screenshot for sanity check. That won't appear in the docs.
![image](https://user-images.githubusercontent.com/11355765/115964955-b700ad00-a4db-11eb-9f7e-69f7908e0732.png)

**Comment by lostanlen** [comment]
> First, there is one more example in that docs page that needs to be squared, which is the second chroma cov plot under the Color Maps section. I consider that too as a target of this PR, right?

Yes. Basically, every covariance/correlation/self-distance/self-similarity/adjacency matrix that appears in the docs should appear square.

> I don't think we should do this because the second chroma cov plot I mentioned above does this already to demonstrate how to pass matplotlib.pyplot.pcolormesh kwargs to specshow. So the first chroma cov plot should intentionally be left non zero-centered

Ah, yes, that's a good observation. I hadn't seen that. My bad.

> My assumption is that if the two axes are semantically the same, we consider that as a self-similarity. I could not think of a counterexample so let me know if there is any. 

Yes, that's also my understanding of @bmcfee's comment. 

I can think of a case where we could go one way (square) or another (rectangle): dynamic time warping with sequences of different lengths. Not sure if it's a counterexample but something worth debating.

**Comment by dorukhansergin** [comment]
> I can think of a case where we could go one way (square) or another (rectangle): dynamic time warping with sequences of different lengths. Not sure if it's a counterexample but something worth debating.

That's a great point. I tried to see how it looks like.

Before:
![image](https://user-images.githubusercontent.com/11355765/115971108-7fa1f880-a4fb-11eb-8a9b-631232786ec6.png)

After:
![image](https://user-images.githubusercontent.com/11355765/115971081-5a14ef00-a4fb-11eb-982b-045a471c3538.png)

I find the older version better. And if the lenghts of two clips differ wildly, it will look even worse. What do you think? In that case, we can use square aspect only if `xlim` and `ylim` are equal, which are explicitly set in `specshow`.

**Comment by lostanlen** [comment]
Thanks for trying it both ways and showing us the result, @dorukhansergin . This is a good way to keep the conversation going.

I am also inclined toward the former, and thus to only set the aspect ratio to square in specshow after checking that xlim and ylim are equal.

@bmcfee thoughts?

**Comment by bmcfee** [comment]
> My assumption is that **if the two axes are semantically the same, we consider that as a self-similarity**. I could not think of a counterexample so let me know if there is any.

This isn't necessarily the case.  For example, a cross-similarity matrix would have time on both axes but different dimensions.  (This is essentially what the DTW example above is showing.)  It's a relatively unusual case, but one that we should handle gracefully.

I think we could refine the logic to be `x_axis == y_axis and data.shape[0] == data.shape[1]` (or, as suggested later, compare the xlims and ylims so that we can handle data covering the same extent in different units, eg mels and fft bins).

All that said, I think this should be logic that we can bypass easily, perhaps by adding a new parameter `auto_scale=True`, where a user can set `auto_scale=False` to bypass this logic.

> I'm also unpleasantly surprised to find out that `None == None` returns `True` in Python smiley

[wat](https://www.destroyallsoftware.com/talks/wat)

**Comment by dorukhansergin** [comment]
Alright then, I'll submit a PR soon with the following:

- `display.specshow` updates:
    - `auto_scale` parameter and its explanation in the docstring of `specshow`
    - a helper function to check if the plot should be square (with axes name and limit checks)
    - the test of that helper function in the test suite
    - the plot squaring procedure that is hit only if the helper function returns true and `auto_scale=True`
- Briefly mentioning in one of the chroma cov plots in `plot_display.py` that the plots are automatically squared in certain cases and can be bypassed with the `auto_scale` parameter. (I don't think it's necessary to replot with the bypass option, it'd look ugly in the docs.)

**Comment by lostanlen** [comment]
Many thanks @dorukhansergin for solving my issue :)

**Comment by dorukhansergin** [comment]
My pleasure @lostanlen ! I love librosa, happy to help in future issues as well.
