### ISSUE TITLE
It would be nice if librosa.load(path, sr) would support a format-kwarg.

### ISSUE THREAD

**Issue by Lavair** [librosa/librosa#1349]
**Is your feature request related to a problem? Please describe.**
I am currently dealing with python inmemory file objects (`io.BytesIO` etc.). They don't have a file extension which is why `librosa.load()` cannot recognise them properly as paths and I get: `RuntimeError: Error opening <_io.BytesIO object at 0x7f1ed40ff090>: Format not recognised.`

**Describe the solution you'd like**
`librosa.load()` uses a `SoundFile` object internally which in fact already supports format as a `kwarg`. Please propagate that `kwarg` to the function call so that a user can define the extension of the file manually (=> `librosa.load(path, sr, format)`)

**Describe alternatives you've considered**
At the moment, I am using `pydub.AudioSegments` for that. But it is not as clean as that one `librosa` call would be.

**Comment by bmcfee** [comment]
I'm generally for this. We might need to be careful of compatibility issues though, since it's possible that not all of the soundfile api options will work with librosa.load.

**Comment by bmcfee** [comment]
To put in a bit more context here, the current call to `sf.read` looks as follows:
https://github.com/librosa/librosa/blob/d9b72af964820fc796425c55d3dccd7f6b908bf9/librosa/core/audio.py#L160

We force `frames` to handle pre-determined duration loading, `dtype` for numerical precision, and `always_2d=False` so that mono buffers collapse to 1d arrays by default.

The remaining parameters to `sf.read` (at present) are:
- `fill_value` (pad out the array if `frames` exceeds the available signal length)
- `out` - preallocated buffer space
- `samplerate, channels, format, subtype, endian, closefd`

Of these, I think it makes sense to support everything except `out`, `samplerate`.

- `out` would be confusing from the perspective of `librosa.load`, since we don't return the loaded buffer directly in most cases.  Instead, we return a transposed, possibly downmixed, and resampled version of the signal.  In this case, the `out=` given to load should not be the same as the `out=` given to `sf.read`.
- `samplerate` would be confusing as it conflicts with `sr` in `librosa.load`.  However, I could see a case for it if we want to handle `RAW` files.  This has never come up for us before, so I don't think there's much need to worry about it, but it's something to consider.

**Comment by bmcfee** [comment]
I'm looking more into this now, and I'm not actually sure what there is to do here.  @Lavair can you provide a more complete example to demonstrate the proposed use case?

Soundfile (and therefore librosa) can correctly infer the format from most open byte streams:

```python
In [18]: fd = open('The Megas - Skulls - 01 Cracked Skulls.ogg', 'rb')

In [19]: x, fs = sf.read(fd)

In [20]: x.shape
Out[20]: (10751950, 2)

In [21]: fs
Out[21]: 48000

...

In [26]: fd = open('The Megas - Skulls - 01 Cracked Skulls.ogg', 'rb')

In [27]: y, sr = librosa.load(fd, sr=None)

In [28]: y.shape
Out[28]: (10751950,)

```

The only exception, as far as I'm aware, is when using raw format.  However, in this case, you would need to specify all of the decoding parameters (channels, samplerate, etc).  As stated above, I don't think it's a good idea to support the `samplerate` parameter here because it will be easily confused with the `sr` parameter we already have.

Rather than extend the librosa wrapper for this case, I think it would be generally better for people that really need to work with raw-format audio to use the soundfile object directly.  This would of course limit some functionality, eg resample-on-load and overlapping block streams.

Probably the best workaround here would be to allow `load` and `stream` to accept an existing soundfile object instead of a file path or bytestream.  This way, you can configure exactly the decoding that you would need without losing out on our (admittedly small) added functionality.  This also reduces the amount of new API we'd need to add and maintain.

**Comment by bmcfee** [comment]
If the soundfile object idea sounds good, I think we can implement it more or less easily 

Eg, in `load`:

https://github.com/librosa/librosa/blob/fc77834f8efd16e063f91af62dd876c7c133bf28/librosa/core/audio.py#L149-L160

would become something like:

```python
if isinstance(path, sf.SoundFile):
    cm = path
else:
    cm = sf.SoundFile(path)

with cm as sf_desc:
    ...
```

`stream` is a little more convoluted, but not too bad:

https://github.com/librosa/librosa/blob/fc77834f8efd16e063f91af62dd876c7c133bf28/librosa/core/audio.py#L404-L413

Which we may as well just rewrite to construct a soundfile object instead of using `sf.blocks()` to do it for us.

**Comment by Lavair** [comment]
Hmm, sorry that I didn't respond earlier. You must know that I finished the project where I used librosa somewhere around July and don't have access to it anymore. 

As you can image, I forgot the exact situation I had here and I cannot reasonably comment on it, sorry :grimacing:  ..but apparently, you already made a pr anyway.

**Comment by bmcfee** [comment]
@Lavair thanks for checking back, and sorry that it's taken so long to get to this one.  But I'm glad you were able to work around it.

To put it simply, the (in progress) PR and proposed resolution would have resulted in something like the following for you:

```python
sfo = sf.SoundFile(path, format=format, [... other kwargs])
y, sr = librosa.load(sfo)
```
Not quite as slick as promoting all soundfile parameters up to the librosa API, but much easier to maintain and not too much more difficult to use.  It does sound to me like your original issue was a bit subtler than just specifying format, but I think the proposed solution should otherwise sufficiently resolve things.
