### ISSUE TITLE
How to set the parameter to get the mfcc with the dimention I need

### ISSUE THREAD

**Issue by kli017** [librosa/librosa#1354]
I was extract mfcc features by librosa. The input is 72000 samples and I set the hop_length to 480 and the n_mfcc to 13. According to my calculation the output should be (13, 72000/480) which is (13, 150) however I got (13, 151) instead. Below is the prameters I set. Anyone help me figure out what wrong here?

mfcc = librosa.feature.mfcc(raw, sr=16000, n_fft=4096, n_mfcc=13, hop_length=480, n_mels=40, fmin=0, fmax=None, htk=False)

**Comment by lostanlen** [comment]
(related: https://github.com/librosa/librosa/issues/997 )

Nothing is wrong. By default, `librosa.feature.mfcc` calls `librosa.stft`, which has the `center=True` keyword argument. With `hop_length=480`, this implies that the MFCC frames are _centered around_ the following time samples

0, 480, 960, 1440, 1920 ... 71520, 72000.

Because both the start (0) and end (72000) points are included, the number of such frames is (1 + 72000/480) = 151.
You can know which times these frames point to via the `times_like` function: https://librosa.org/doc/main/generated/librosa.times_like.html

If you want to make the output length exactly 150, my advice would simply be to drop the last frame:
`mfcc = mfcc[:, :(-1)]`
This can be useful when processing audio streams by blocks and concatenating the MFCC matrices of each block.

For more advanced solutions on how to process audio stream, see `librosa.stream`
https://librosa.org/blog/2019/07/29/stream-processing/

If your use case is to analyze a full-length audio recording, my advice would be to stop worrying and use the default behavior.

**Comment by kli017** [comment]
@lostanlen Thanks for the help and seguesstions. I was doing voice activity detection using mfcc features and set each frame to 30ms(480 samples).
So I need align the features to each frame. I found If I set center=false and n_fft=480 here can get exactly 150. 
Because I'm not analyze the full-length auido here and I was wondering if I just drop the last frame, can the features aglin with the frame? Or better to use the n_fft=480 here to get 150 frames?

**Comment by lostanlen** [comment]
@kli017 What do you mean by "align the features to each frame"?

If what you mean is retrieving onset-offset times (in seconds) from the output of your voice activity detector, you can use `librosa.frames_to_time`:
https://librosa.org/doc/main/generated/librosa.frames_to_time.html

```python
onset_time = librosa.frames_to_time(onset_frame, sr, hop_length, n_fft)
offset_time = librosa.frames_to_time(offset_frame, sr, hop_length, n_fft)
```

**Comment by kli017** [comment]
@lostanlen The 72000 samples are from 4.5s audio and it in fact already been segment to 30ms for each frames at first(so 150 in total).  So the original dimension of raw is (480, 150). Because I found that librosa does not surpport 2d input? so I flat the input back to 1d vector. "align the features to each frame" means that I want get the mfcc features for those frames.

**Comment by lostanlen** [comment]
@kli017 you don't need to manually segment the signal into frames. Just pass the full waveform (72000 samples) to `librosa.mfcc` and it will work out of the box.
You can control overlap between frames with `hop_length`. By default `hop_length = win_length // 4` and `win_length = n_fft`. You're free to modify these values via the keyword arguments of mfcc (which are passed to `librosa.stft` internally)

https://librosa.org/doc/main/generated/librosa.stft.html

**Comment by kli017** [comment]
@lostanlen Ok Thanks for the help
