### ISSUE TITLE
get_duration can not work on generated audio <int16>

### ISSUE THREAD

**Issue by snowyu** [librosa/librosa#1360]
**Describe the bug**

```bash
Traceback (most recent call last):
  File "tts/tts.py", line 223, in <module>
    timeDuration = librosa.get_duration(y=result, sr=sr)
  File "python3.7/site-packages/librosa/core/audio.py", line 722, in get_duration
    util.valid_audio(y, mono=False)
  File "python3.7/site-packages/librosa/util/utils.py", line 290, in valid_audio
    raise ParameterError("Audio data must be floating-point")
librosa.util.exceptions.ParameterError: Audio data must be floating-point
```

**To Reproduce**

Example:

```python
import librosa
from tts import textToSpeech
import soundfile as sf

wav, sr = textToSpeech("hello world") # wav numpy int16 array
sf.write("result.wav", wav, sr) # it's ok.
timeDuration = librosa.get_duration(y=wav, sr=sr) # raise error
print("timeDuration",timeDuration)
```

**Expected behavior**

Get the duration from the int16 audio data.

**Software versions***
Please run the following Python code snippet and paste the output below.

```
Linux-5.4.0-80-generic-x86_64-with-debian-bullseye-sid
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0]
NumPy 1.18.5
SciPy 1.7.0
librosa 0.8.1
INSTALLED VERSIONS
------------------
python: 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0]

librosa: 0.8.1

audioread: 2.1.9
numpy: 1.18.5
scipy: 1.7.0
sklearn: 0.24.2
joblib: 1.0.1
decorator: 4.4.2
soundfile: 0.10.3
resampy: 0.2.2
numba: 0.48.0

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: None
pytest-mpl: None
pytest-cov: None
matplotlib: 3.3.4
presets: None
```

**Additional context**

**Comment by bmcfee** [comment]
Thanks for the report.  This, I think, is intended but perhaps counterintuitive behavior.

Throughout the library, we made a conscious decision to support only floating point representations of signals for processing, since it simplifies much of the type logic when generating features.  Putting this check into the helper that validates audio buffers seemed reasonable at the time, and I still think it is.  However, this means that functions like this one might be over-restricted.

This does present an inconsistency though, as `get_duration` will work with integer-coded signals stored in files, just not in memory.  I'd be fine with dropping the validation requirement here, since I don't think it's doing much anyway, and has no bearing on the duration of a signal.

**Comment by tcelox** [comment]
I will do, Please assign.
