### ISSUE TITLE
Unable to properly reconstruct audio from MFCCs using `librosa.feature.inverse.mfcc_to_audio`

### ISSUE THREAD

**Issue by anferico** [librosa/librosa#1366]
I'm trying to convert a set of Mel-frequency Cepstral Coefficients (MFCCs) back to an audio signal using `librosa.feature.inverse.mfcc_to_audio`, but the reconstructed audio is very low-quality.

As a sanity check, I tried to:

1. Take one of librosa's sample audios (“Trumpet”)
2. Compute its MFCCs
3. Convert the MFCCs back to the original audio

Even in this case, the audio that I reconstruct sounds very different than the original, yet I'm using nothing more than librosa functions. Here's the code to reproduce the issue:

```python3
import librosa
import soundfile

trumpet, sr = librosa.load(librosa.example('trumpet', hq=True), sr=None)
soundfile.write(file='original.wav', data=trumpet, samplerate=sr)

mfcc = librosa.feature.mfcc(trumpet, sr=sr, n_mfcc=25, n_mels=128)
trumpet_reconstr = librosa.feature.inverse.mfcc_to_audio(mfcc, n_mels=128)
soundfile.write(file='reconstructed.wav', data=trumpet_reconstr, samplerate=sr)
```

What am I missing here?

**Comment by bmcfee** [comment]
> What am I missing here?

MFCCs are extremely lossy features.  Perfect reconstruction here is not going to be possible in general.

Remember what happens inside MFCC computation:

1. STFT -> magnitude spectrum (phase is discarded)
2. Mel projection (frequency information is lost)
3. Decibel scaling (relatively easy to recover from, though numerical precision issues can creep in for signals with high dynamic range)
4. Discrete cosine transform and truncation (cepstrum information is lost)

The inverse function reverses each of these steps, and introduces approximations (typically least squares solvers) wherever approximation is done (step 4->3 IDCT, step 2->1 non-negative least squares, step 1->0 griffin-lim).

If you want to better understand the effects going on here, try setting `n_mfcc=n_mels` (so that the DCT can be inverted), and/or increasing `n_mels` closer to `n_fft` (so that the non-negative least squares doesn't have to guess so much).

**Comment by anferico** [comment]
Thank you very much for the info, I guess it shows that I'm no expert in these topics. I've tried following your suggestions, but the reconstruction is still kinda poor. Based on what you've explained, I've tried computing just the magnitude spectrum (step 1) and inverting that, and I must say that now the reconstruction given by Griffin-Lim is definitely satisfactory.
