### ISSUE TITLE
Autocorrelation off-by-one error

### ISSUE THREAD

**Issue by PhilStem** [librosa/librosa#1425]
https://github.com/librosa/librosa/blob/381efbd684c01ae372220526352d34fd732d3b1d/librosa/core/pitch.py#L402

The flipped array `y_frames[..., win_length::-1, :]` has length `win_length+1` at axis -2. I think the line should be `b = np.fft.rfft(y_frames[..., win_length:0:-1, :], frame_length, axis=-2)`. The code I tried seems to produce more accurate results:

```python
sr = 44100
y = np.sin(100*2*np.pi*np.linspace(0, 1, sr, endpoint=False))
res = yin(y, 60, 1000, sr=sr, center=False)
print(res)
```

Before:
```
[100.00016561  99.98214417 100.00800707 100.00344982  99.98128853
 100.00550897 100.00639164  99.9812107  100.00265195 100.00886901
  99.98193343  99.99954079 100.01079017  99.98343062  99.99629365
 100.01209364  99.98562683  99.99304064 100.01274637  99.98840202
  99.98992114 100.01274092  99.99160123  99.98707952 100.01209245
  99.99504764  99.98465883 100.01083594  99.998557    99.98279243
 100.00902398 100.00195128  99.98159414 100.00672526 100.00506986
  99.98114769 100.00402355 100.00777726  99.98149702 100.00101708
 100.00996745  99.98263923  99.99781788 100.01156496  99.98452163
  99.99455075 100.01252378  99.98704407  99.99135116 100.01282489
  99.99006641  99.98836181 100.0124733   99.99342027  99.98572728
 100.01149502  99.99692308  99.98358661 100.00993467 100.00039234
  99.98206405 100.00785359 100.0036581   99.98125865 100.00532858
 100.00657243  99.981234   100.00245121 100.00901523  99.98200972
  99.99932716 100.0108968   99.98355639  99.99607547 100.01215761
  99.98579538  99.99282693 100.01276643  99.98860398  99.98972145
 100.0127174   99.99182533  99.9869035 ]
```

After:
```
[100.00016561 100.00033933 100.00027569 100.00015915 100.00032482
 100.00029493 100.00015733 100.00030679 100.00031272 100.00016005
 100.00028612 100.00032835 100.00016701 100.00026388 100.00034112
 100.00017777 100.00024128 100.00035042 100.00019176 100.00021953
 100.00035573 100.00020834 100.0001998  100.00035666 100.0002268
 100.00018308 100.00035298 100.00024641 100.00017017 100.0003447
 100.00026642 100.00016159 100.00033207 100.00028609 100.00015761
 100.00031559 100.00030465 100.00015823 100.00029603 100.00032137
 100.00016326 100.00027438 100.00033555 100.00017231 100.00025179
 100.00034655 100.00018487 100.0002295  100.00035378 100.00020032
 100.00020869 100.00035679 100.00021799 100.00019045 100.00035528
 100.00023716 100.00017568 100.00034913 100.00025708 100.00016503
 100.00033848 100.000277   100.00015889 100.00032372 100.00029617
 100.00015738 100.00030548 100.00031384 100.00016038 100.00028467
 100.00032929 100.00016762 100.00026237 100.00034185 100.00017861
 100.00023979 100.0003509  100.00019279 100.00021814 100.00035593
 100.00020952 100.00019858 100.00035656]
```

**Comment by bmcfee** [comment]
Oh interesting.  I wonder if this is replicated from the original yin / pyin implementation.  Maybe @bshall can chime in here?

As I understand it, the idea here is to do a time-bounded autocorrelation

https://github.com/librosa/librosa/blob/381efbd684c01ae372220526352d34fd732d3b1d/librosa/core/pitch.py#L401-L404

where `a` has the full frame observation, and `b` only has the first `win_length` samples.  The latter is accomplished by the slice `win_length::-1`, but as you correctly note, this takes samples:

```python
y_frames[..., win_length, :]
y_frames[..., win_length-1, :]
y_frames[..., win_length-2, :]
...
y_frames[..., 0, :]
```
I think your proposed fix
```python
b = np.fft.rfft(y_frames[..., win_length:0:-1, :], frame_length, axis=-2)
```
 isn't quite right, as that would take the slice starting from index 1 instead of 0.  I think the following would be more correct:
```python
b = np.fft.rfft(y_frames[..., win_length-1::-1, :], frame_length, axis=-2)
```

**Comment by bmcfee** [comment]
Following up on this: I tried out my suggestion, and it does seem to behave worse than the proposed `win_length:0:-1` slice.

For context, it might be helpful to link up to the discussion on this bit of the code in the CR from #1063 : 

https://github.com/librosa/librosa/pull/1063#discussion_r435443422

**Comment by bmcfee** [comment]
Spent some time digging into this, and I'm pretty well baffled.  In principle, this really shouldn't matter very much -- indeed, it doesn't seem to, since we're talking about hundredths of a Hz here, and the difference in autocorrelation is +- 1 sample value -- but it is pretty strange that omitting the 0th sample within the frame improves consistency for a stationary tone.  I have replicated this locally with various frequencies in an attempt to see if this is just a quirk of the particular configuration reported initially here (100hz tone + 44.1K rate + standard framing), but it does appear to be a real effect and I'd like to understand it.

Note that the `win_length:0:-1` slice doesn't completely eliminate frame modulation effects, but it does seem to reduce their magnitude.

**Comment by bmcfee** [comment]
I'd like to resolve this before the next release, but would appreciate input from anyone else more familiar with the guts of yin.
