### ISSUE TITLE
Incorporating new Audio feature - CQCC

### ISSUE THREAD

**Issue by ShubhankarKG** [librosa/librosa#1433]
**Is your feature request related to a problem? Please describe.**

It's not related to a problem. We are using librosa as our go-to tool for audio feature extraction. We love that we get an API to extract STFT and MFCC. We would like to have CQCC incorporated into the core feature subset of librosa.

**Describe the solution you'd like**
Maybe a new API like `librosa.features.cqcc`

**Describe alternatives you've considered**
Currently, we are trying to write the conditions ourselves, but as is the case always, we may have a fix, but the library would have better standards.

**Additional context**

CQCC was introduced here: https://www.asvspoof.org/papers/CSL_CQCC.pdf. Since then, multiple papers have incorporated the use of CQCC for their own research purposes.

Additonally, the authors of CQCC have an open source implementation in MATLAB here: http://audio.eurecom.fr/content/software

A general block diagram listing the steps used to generate CQCC:
![image](https://user-images.githubusercontent.com/50791000/149459979-40283433-1aaf-4160-a564-bb3bff0c85e2.png)

**Comment by bmcfee** [comment]
I don't think this would be a very high priority feature, but it seems interesting.  If someone (you?) wants to open a pull request for this feature, I'd be happy to help you get it into shape.

The method itself seems pretty easy to implement: if not for the "uniform resampling" block, I'd say it's trivial to compose out of existing elements.  I'd expect it to look pretty similar to our `mfcc` function.

The uniform resampling block shouldn't be too difficult to implement either, it just takes a bit of familiarity with the CQT interface and scipy interpolators.  (Looking at the `interp_harmonics` function would be a good place to start.)

I haven't looked at the matlab implementation,  but I expect it will be pretty difficult to get these to line up exactly.  Probably there will be significant differences in the CQT implementation, as well as in the implementation of log compression and resampling.  The paper you linked doesn't provide much information on these details (ie handling numerical underflow in the log, or what specific spline interpolation they're using), though I guess this could be pulled out of the code.  I mention this mainly because when it comes to testing an implementation, it would be nice if it can be compared to a prior version, but I don't think that's going to be very fruitful in this case.

**Comment by lostanlen** [comment]
Hi @ShubhankarKG 

Your issue reminds me of this ISMIR 2016 paper by Mi Tian and Mark Sandler:
http://m.mr-pc.org/ismir16/website/articles/032_Paper.pdf
Music Structural Segmentation Across Genres with Gammatone Features
Those Gammatone Features were arranged along an ERB scales (~ VQT with `gamma=None`) and were shown to outperform MFCC on a dataset of Beijing Opera music.

**Comment by bmcfee** [comment]
> Your issue reminds me of this ISMIR 2016 paper by Mi Tian and Mark Sandler:

Right - near as I can tell, the main difference between the two methods (aside from the filter shape) is that the feature requested here involves interpolating the frequency range back to a linear scale after the CQT/dB scaling but before the DCT.  I find this step somewhat puzzling, and I'm not quite sure why it would be an improvement over a vanilla cepstrum.  It mainly seems like a roundabout way to do a cepstrum with some non-uniform time and frequency smoothing, but perhaps I'm missing something important here.

**Comment by ShubhankarKG** [comment]
Thanks for all the inputs everyone! I'll close this issue out now since it's not related to librosa per se. Thanks for your time everyone!
