### ISSUE TITLE
dependency issues

### ISSUE THREAD

**Issue by pyquest** [librosa/librosa#1440]
ERROR: imageio 2.14.0 has requirement pillow>=8.3.2, but you'll have pillow 7.2.0 which is incompatible.
ERROR: audio-to-midi 2020.7 has requirement cffi==1.12.3, but you'll have cffi 1.15.0 which is incompatible.
ERROR: audio-to-midi 2020.7 has requirement numpy==1.16.3, but you'll have numpy 1.22.2 which is incompatible.
ERROR: audio-to-midi 2020.7 has requirement SoundFile==0.10.2, but you'll have soundfile 0.10.3.post1 which is incompatible.
ERROR: numba 0.55.1 has requirement numpy<1.22,>=1.18, but you'll have numpy 1.22.2 which is incompatible.

however i am running other packages that require an up to date vesion of numpy

**Comment by bmcfee** [comment]
It looks like your problem is audio-to-midi, not librosa.  It's impossible to tell really since you didn't fill out the issue template or provide any other information about your environment.

Does it work if you try installing the current pre-release on pypi (0.9.0rc0)?  For the record, our current dependency spec is as follows:

```python
install_requires =
    audioread >= 2.1.5
    numpy >= 1.17.0
    scipy >= 1.2.0
    scikit-learn >= 0.19.1
    joblib >= 0.14
    decorator >= 4.0.10
    resampy >= 0.2.2
    numba >= 0.45.1
    soundfile >= 0.10.2
    pooch >= 1.0
    packaging >= 20.0
```

And our CI builds run on both [minimal pinned](https://github.com/librosa/librosa/blob/main/.github/environment-minimal.yml) and [current](https://github.com/librosa/librosa/blob/main/.github/environment-ci.yml) dependencies without trouble.
