### ISSUE TITLE
Option to force audioread to use ffmpeg

### ISSUE THREAD

**Issue by jhuus** [librosa/librosa#1450]
When loading an mp3, librosa calls audioread. On my system audioread then calls gstreamer instead of ffmpeg, but gstreamer does a poor job decoding the file. It decodes much better with ffmpeg. When I call audioread.available_backends(), the output is:

```
[<class 'audioread.rawread.RawAudioFile'>, <class 'audioread.gstdec.GstAudioFile'>, <class 'audioread.ffdec.FFmpegAudioFile'>]
```
So I'd like an option that forces audioread to prefer ffmpeg. Or even better, always just force it to use ffmpeg if it is available. The audioread audio_open method has a backends argument you can use for that. Or a change could be made in audioread so it checks for ffmpeg before checking for gstreamer. That's probably the simplest solution.

**Comment by bmcfee** [comment]
Interesting.  I'm sympathetic to the issue, but also keeping in mind that the eventual plan is to deprecate and remove audioread entirely.  My preference is to avoid building in new API that will be removed in the near future unless it's absolutely necessary.

In the specific case of mp3 support, this will be obviated by the next libsndfile release, which includes mp3.

How much of the `load` functionality are you using here?  It might make more sense in your case, for the time being at least, to  use audioread directly with a forced backend and then resample / downmix manually.

**Comment by jhuus** [comment]
I've been able to work around it with some "manual" code along the lines you suggested, but it would be nice to have a neater solution, and to save other people from running into this in future.

**Comment by bmcfee** [comment]
> The quick change I suggested to audioread would avoid any API changes.

It would necessitate expanding our API to support it as a pass-through, followed by deprecating the new API when we remove audioread in the future.

A similar discussion arose from #1349 , where the requested API extension was for soundfile.  In that case, we opted against adding parameters and in favor of accepting pre-constructed SoundFile objects instead of filenames.  Most of this decision came from not wanting to add API that only works on one backend but not the other, but it also spares us from having to maintain API parity with backend functionality.  I wonder if a solution like that could work for your problem?  That is, if we made it possible for you to initialize an audioread object however you see fit, and then we read from that instead of constructing a new one?

**Comment by jhuus** [comment]
Sorry, I don't understand how the isinstance statement above fits in.

**Comment by bmcfee** [comment]
The idea is that you could do something like:

```python
>>> ar_obj = audioread.audio_open(path, [whatever audioread options you like])
>>> y, sr = librosa.load(ar_obj, [librosa options])
```
We would detect `path` as an audioread object, using the aforementioned check, and then bypass creating a new audioread object.

**Comment by jhuus** [comment]
Thanks - makes sense!
