### ISSUE TITLE
More options for bandwidth estimation in similarity/recurrence matrix construction

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1462]
**Is your feature request related to a problem? Please describe.**

At present, the recurrence_matrix function provides a rudimentary bandwidth estimator, which uses the median k'th nearest neighbor distance.  A user can also provide an explicit value for bandwidth, but doing anything else turns out to be a bit of a pain.

**Describe the solution you'd like**

We could expand out the functionality for the bandwidth parameter to support a few different options.  Median-to-k is one option, another would be the pairwise adaptive method used by `Bo Wang, Jiayan Jiang, Wei Wang, Zhi-Hua Zhou, and Zhuowen Tu, “Unsupervised metric fusion by cross diffusion,” in Computer Vision and Pattern Recognition (CVPR), 2012 IEEE Conference on. IEEE, 2012, pp. 2997–3004.` (and later in the paper I coauthored with @ctralie), which essentially averages the distance D(i, j), the mean distance among i's nearest neighbors, and the mean distances among j's nearest neighbors.

One hiccup here, compared to the reference paper(s), is that we should ideally support arbitrary distance functions and not just euclidean distance.  This doesn't matter too much, except where squares of distances are concerned, and how that might interact with averaging.  (Squaring or not squaring distances has no effect on median calculation, since squaring is a monotonic-up function, but it will slightly change other aggregators like mean.  Just making a note of it here.)

**Describe alternatives you've considered**
We can always do this kind of thing by hand, but it's tedious and should be easier.

**Additional context**

We could probably come up with a few other recipes to include here.  I'm thinking of identifying them by name/string.

Additionally, we might want to consider adding a parameter `full=False` (by default) which controls whether the recurrence matrix is a k-nearest-neighbor matrix or a full matrix.  Right now we hack it by setting `k=N`, but this messes with the use of `k` in bandwidth estimation.  Setting `full=True` would essentially bypass the knn step and build the full affinity / kernel / distance matrix.

I'm including this idea in this issue mainly because it's relevant to bandwidth estimation, but we could also handle it separately.

Tagging @tomxi here because he's expressed interest in working on implementing the bandwidth issue.

**Comment by tomxi** [comment]
Documenting some of the discussions that happened off-line:
We want to support more options for bandwidth estimation. Currently, bandwidth estimation supports only a scalar input or `None` in which case it would estimate a scalar bandwidth (Median-to-K).

A couple of other bandwidths would make sense besides Median-to-K: 
- we can estimate the bandwidth independently for each time point, which could be the distance to the K'th nearest neighbor, or the average distance to the first KNNs. These would have a bandwidth with `bandwidth.shape = (N,)`. In these cases, since a pair of points will have two different bandwidths coming from each point, both geometric mean and arithmetic mean can be appropriate for combining different bandwidths associated with each of the N time points.
- We can also estimate the bandwidth independently for each time point pair, in the style of Bo et al. (2012) mentioned above. These would have a bandwidth with `bandwidth.shape = (N,N)`.

To expand the functionality of the bandwidth parameter to support these options without breaking the current API, I propose to keep `bandwidth=None` as the flag for Median-to-k, allow for a set of strings to indicate which other bandwidth estimation methods to use, and allow for vector or matrix bandwidth with `bandwidth.shape = (N,N)` or `bandwidth.shape = (N,)` in the case users want to compute their bandwidth manually.

Couple of issues I see with this approach: there seems to be a need to supply additional parameters for some of the bandwidth estimation methods (eg. `mu` in Tralie's implementation of Bo et al., 2012), and perhaps for a user to choose which bandwidth aggregator (geometric/arithmetic mean) to use in the case they supply a vector bandwidth with `bandwidth.shape = (N,)`. 
What we can do is to only allow users to supply a full matrix bandwidth or a scalar, but not a vector. The 'mu' parameter in the pairwise adaptive method can also be achieved by raising the resultant matrix to 'mu', and folding the choice of bandwidth aggregators into the string-based flags for `bandwidth`; that way, no new parameter needs to be added to the function signature after all, besides the 'full=False' flag suggested above.
