### ISSUE TITLE
dimension issue spectral_flatness

### ISSUE THREAD

**Issue by spyroot** [librosa/librosa#1488]
Hi Folks,

I'm not 100 sure I understand the logic so maybe it issues on my end.
Input (80, 513),  here 80 filters are used to generate mel.

Now let's say, I pass that spectral_flatness, according to the doc it should accept that. 
So I can pass spectrogram input.

Now if I don't flatten input I don't have any issue since it already has 80 filters.

```
librosa.feature.spectral_flatness(y=mel_numpy,
                                                       n_fft=1024,
                                                       hop_length=self.hop_length,
                                                       win_length=self.win_length,
                                                       center=True)
```

Now If pass spectral_flatness input I am already in a spectral form MEL.  In a shape (80, 513) dim.
(80 MEL channels, win length 1024, and hop length 256)
 
```
UserWarning: n_fft=1024 is too small for input signal of length=513
  return f(*args, **kwargs)
```

-> so if it is already _spectrogram do you need to pass it again or is it no-op?
```
    S, n_fft = _spectrogram(
        y=y,
        S=S,
        n_fft=n_fft,
        hop_length=hop_length,
        power=1.0,
        win_length=win_length,
        window=window,
        center=center,
        pad_mode=pad_mode,
    )
```

Now, I tried to understand why you doing axis=-2 i.e n what dim you computing that ratio and 
what relation input signal.

```
    S_thresh = np.maximum(amin, S ** power)
    gmean = np.exp(np.mean(np.log(S_thresh), axis=-2, keepdims=True))
    amean = np.mean(S_thresh, axis=-2, keepdims=True)
    return gmean / amean
```

**Comment by spyroot** [comment]
Oh, I see,  because I was trying to make sense of the mean value on each column space.
If I have a magnitude phase, I tried to use spectral_flatness, and I had the same issue.

Do you have any suggestions on how to do it in the most efficient way ? 

Because in matlab you can do it from MEL
https://www.mathworks.com/help/audio/ref/spectralflatness.html
A second example.

In essence, it just means it should make sense to measure in MEL as well no?

**Comment by bmcfee** [comment]
@spyroot you can absolutely provide a magnitude or power spectrogram as input to spectral flatness by using the `S=` argument instead of `y`.  The examples in the documentation for this function should be enough to explain how to use it.

> The utility function `librosa.mel_frequencies` can help you compute these arithmetic and geometric means.

This is a subtle point, and perhaps worth discussing a bit.  Our flatness implementation assumes linear frequency spacing, which for the purposes of flatness calculation, amounts to a uniform weighting in the arithmetic and geometric means (measured against a linear spacing).  If you provide a different frequency scale (mel, cqt, whatever), it will still apply a uniform weighting, so the resulting flatness measurement may be very different.  It's a bit more subtle than this actually - different transforms will have variable filter bandwidths, which is really what will matter when it comes to weighting things properly for a flatness calculation.

Now, maybe this is all fine.  But I wonder if it's worth considering extending the API to support frequency axis weighting here if the user wants to override the default assumptions?  It would take a bit of thought, and I'm not sure there's much demand as flatness is not very often used anymore, but it's worth considering.  (FWIW, many of our other feature transforms support overriding the frequency axis for similar reasons, allowing for stft/mel/cqt/etc inputs to be supported.)

**Comment by spyroot** [comment]
Hi,   @bmcfee 

Thank you very much. ! very much appreciated both responses. 
 I was thinking specifically about your second point and what precisely that formula measures in different domains. i.e. MEL. I currently use MEL in my model to compute loss during reconstruction. So now, I want to use additional features to measure reconstruction loss.    i.e., other loss terms are probabilistic, so I decided first to use the simplest one. Plus, it has a lovely property. It is a probability. You can pad to a fixed size (i.e., zero doesn't change anything ) to have a nice shaped matrix.

**Comment by bmcfee** [comment]
I'm not sure I follow what you're saying about probabilities here, and I don't think it would be correct to interpret flatness as a probability.  It is true that it will always be between 0 and 1 by the arithmetic-geometric mean inequality, but there's no plausible generative story here that would lend itself to a probabilistic interpretation.  Padding with zeros is not a no-op here, as we do generally threshold the values at `amin` to prevent numerical underflow in the log.



> If you use MEL as per your suggestion, do you need re-parameterization?

This all depends on how you want to weight the contributions from each mel frequency band in the averaging operations.  If you think each mel band should contribute equally, then no change is necessary.  If you want the average to be taken with respect to linearly spaced frequencies, then you'll either need to incorporate some kind of weighting scheme into the arithmetic and geometric means, or interpolate / transform the mel energies back onto the linear frequency spacing.

**Comment by spyroot** [comment]
Thank you very much.  I think I can close this issue.
