### ISSUE TITLE
Deprecating librosa.load() default sr and mono

### ISSUE THREAD

**Issue by dofuuz** [librosa/librosa#1573]
**Is your feature request related to a problem? Please describe.**
Using librosa.load() without care will cause unexpected resampling and channel merging.
It may silently spoil results. (It really happned :facepalm:)

**Describe the solution you'd like**
Change default of librosa.load() to
```
librosa.load(..., sr=None, mono=False, ...)
```

**Describe alternatives you've considered**
1. Deprecate `sr=22050, mono=True` default, and add warning about default 22050Hz samplerate and mono merging.
1. Remove default value of sr, mono in future release.
1. Change default value to `sr=None, mono=False` in more future release

something like
```
def load(path, *, sr=-1, mono=-1, ...):
    if sr == -1:
        sr = 22050
        warnings.warn("Implicit default 22050Hz resampling is deprecated. Set samplerate in Hz to resample or use None to disable resampling.", DeprecationWarning)

    ...
```

**Additional context**

**Comment by bmcfee** [comment]
I'm open to dropping `mono=True`, but probably not until after a 1.0 release.

I don't think defaulting to the native sampling rate is a good idea though.  Our reasoning for this design choice is [well documented](https://librosa.org/blog/2019/07/17/resample-on-load/#resample-on-load).  You're correct that using this without care can lead to errors, but I think there would be far more errors popping up from using the native sampling rate without care.

**Comment by bluenote10** [comment]
> First, we wanted it to be relatively simple to use, and have consistent default parameters shared across all functions. As [Gael Varoquaux](https://www.youtube.com/watch?v=eVDDL6tgsv8&t=2406s) reiterated in his keynote at SciPy 2017: consistency, consistency, consistency! Having standardized default parameters means that a user is less likely to be surprised by unexpected behavior when working with different parts of the library. This makes the software easier to learn and use.

I can only speak for myself, but to me the fact that `sr` does not default to `None` was **very** unexpected. It feels inconsistent with how optional parameters typically operate and also file loading semantics in general (post-processing / transformations are typically opt-in), especially since `sr` is an return value. I somehow missed that `sr` had this default, and spend a long time debugging why loading an mp3 suddenly become super slow after updating dependencies (apparently a regression in resampy) -- of course, a very silly mistake in retrospect, but just to mention it in that context.

**Comment by bmcfee** [comment]
> I can only speak for myself, but to me the fact that `sr` does not default to `None` was **very** unexpected.

Yes, I understand that and appreciate that position.  However, I think the opposite situation would lead to far more unexpected behaviors in the broader context of the package.  (This is unfortunately impossible to test in hindsight, but knowing what kinds of things novice users are likely to do, I'm quite certain that this would be the case.)

If you accept that default parameters are a good thing in general, eg for things like frame and hop lengths, then it follows that a standardized sampling rate is necessary for internal consistency.  Propagating the native sampling rate by default -- silently, I might add! -- would lead to inconsistent behavior across tracks that would be nearly impossible to detect as a user.  The fact that we haven't had to deal with hundreds of bug reports derived from incorrect parametrizations across tracks makes me think that this decision was the best compromise.

The only viable alternative here would have been to define default parameters in natural units (seconds) so that they are not sensitive to the choice of sampling rate.  However, this comes with its own can of worms arising from things like round-off error in floating point conversions.  We determined pretty quickly that this would have been a bad design.

We also could have eliminated default parameters entirely, forcing the user to specify everything at every call.  This feels very unpythonic, and probably would have resulted in a bunch of stack-overflow copypasta with incorrect parametrizations anyway.

I'll also note that if you don't want sample rate conversion, there's no requirement (or, argurably, any benefit!) to using librosa.load instead of soundfile.read.  If we were to deprecate rate conversion and downmixing, we may as well deprecate the entire function.  As much as I'd love to deprecate all IO functionality (joking-not-joking here), I don't think it's feasible, and people do use this pretty frequently.
