### ISSUE TITLE
Have the percentage of similarity between two audio sources

### ISSUE THREAD

**Issue by Impre-visible** [librosa/librosa#1599]
**Is your feature request related to a problem? Please describe.**

A function that could be called ``similarity_match()`` having two parameters, NDArray from librosa.load, that computes the percentage of similarity between two audio sources

**Describe the solution you'd like**
I would see something like that:
```py
Audio1 = librosa.load("audio1.wav")
Audio2 = librosa.load("audio2.wav")

similarity = librosa.util.similarity_match(Audio1[0], Audio2[0])
# similarity return 0.9 if the accuracy is 90%
```

**Describe alternatives you've considered**
I tried to get a hash from the NDArray to check if they were the same, so it forces to have exactly the same sources, which is not the case when you use this function

**Comment by bmcfee** [comment]
This is not a well-specified request.  "Similarity" can mean many different things depending on situation and application, and most of the definitions with practical application (eg recommender systems or fingerprinting) would additionally require a backing database and some kind of data-driven model, both of which would be out of scope for librosa.

If I'm misinterpreting this, and you mean something much more specific, please let me know.  Otherwise I'll leave this as a `wontfix`.

**Comment by Impre-visible** [comment]
i'm not the best in audio analysis, but you can add a variable to select the similarity you like

**Comment by yogendra-yatnalkar** [comment]
Hi @Impre-visible @bmcfee I am very new to the audio processing and analysis domain. I have 2 audio files of equal length and same properties. My task is the measure if these 2 audio files are nearly identical or not.

Is there a way I can do that using Librosa ?

Like I know I can generate different spectrographs from my audio signals but not sure what to do after that. I was also not able to find much on the web regarding how to do this task using librosa.

If possible, please guide me on how to approach this problem.
Thank you in advance.
