### ISSUE TITLE
TypeError: guvectorize() missing 1 required positional argument: 'signature'

### ISSUE THREAD

**Issue by baipeng0110** [librosa/librosa#1600]
in librosa0.7.2
TypeError: guvectorize() missing 1 required positional argument: 'signature'
请问该如何解决？

**Comment by bmcfee** [comment]
1) Please use the bug report template.
2) This is almost certainly coming from an environment inconsistency with upstream packages (probably resampy and numba) and not librosa.  There is nothing to fix from the librosa side, but we don't know if you don't fill out the report template and provide information about your environment.
3) Your librosa version is several years out of date, and it would probably help to upgrade that as well.

**Comment by baipeng0110** [comment]
您的邮件我已经收到，会尽快回复，谢谢。

**Comment by Soonmok** [comment]
suddenly `resampy==0.4.2` is used in `librosa==0.6.3` package.
it should downgrade it's version to `resampy==0.3.1`

**Comment by bmcfee** [comment]
> suddenly `resampy==0.4.2` is used in `librosa==0.6.3` package.

We do not put upper version pins on dependencies, nor could we go back in time to change the requirements for a release from 4 years ago.  (See https://iscinumpy.dev/post/bound-version-constraints/ for extensive details about this.)

If you want to cap package versions in your own environment, that's fine and totally possible to do, but it should not be done from the package maintainer's side.

That said, I would encourage you to upgrade librosa rather than downgrade resampy.
