### ISSUE TITLE
librosa can't load wav file in aws lambda docker

### ISSUE THREAD

**Issue by lukasavic1** [librosa/librosa#1609]
I have an AWS Lambda function created using Docker. I have librosa installed, ffmpeg installed using the solution from this question: [install ffmpeg on amazon ecr linux python](https://stackoverflow.com/questions/73660917/install-ffmpeg-on-amazon-ecr-linux-python/73823267#73823267)

I checked in a Lambda function with `os.system("ffmpeg -version")` and I managed to get valid output, stating different versions and parts of ffmpeg.

Problem is that when I do `librosa.load(wav_file) `it gives the following error:

```
/your/path/.venv/lib/python3.9/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs) 
```

From what I've read, librosa should natively support .wav files, even without ffmpeg, and even though I have ffmpeg installed, it doesn't work.

One more information, .wav file was downloaded, player, and loaded with librosa on my local PC without any problems. I tried also on different wav and mp3 files, and the problems were still there.

Windows-10-10.0.19044-SP0
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
NumPy 1.21.5
SciPy 1.7.3
librosa 0.9.2

**Comment by bmcfee** [comment]
> Problem is that when I do `librosa.load(wav_file) `it gives the following error:

That's a warning, not an error.  Are you sure it's not working?

**Comment by bmcfee** [comment]
> I use scipy.io.wavfile.wavread, it gives and error:
> File format b'####' not understood. Only 'RIFF' and 'RIFX' supported.

Ok, I think you've found the problem then.  The wav file in question uses an unsupported format by the decoding libraries that librosa uses.

In older versions of soundfile, it wasn't possible for the upstream caller (ie librosa) to distinguish this kind of error from other errors, hence falling back to audioread.

Audioread will probably not go to ffmpeg in this situation, since it's a .wav file.  You can force this by using audioread's ffmpeg class directly, but it's not obvious that ffmpeg will handle the wav in question either.

**Comment by lukasavic1** [comment]
I just did some ffmpeg transformations, and it started working.

It was a problem with an audio file, you were right, thanks.
