### ISSUE TITLE
Missing information in documentation of librosa.feature.chroma_cqt

### ISSUE THREAD

**Issue by si-timme** [librosa/librosa#1610]
In the documentation of librosa.feature.chroma_cqt the tuning parameter is described as follows:

```
tuning : float
    Deviation (in fractions of a CQT bin) from A440 tuning
```

This left me somewhat wondering about the automatic tuning estimation offered in librosa.cqt. After inspecting the code it seems that this parameter is only used for passing it to the librosa.cqt or librosa.hybrid_cqt functions. There this parameter is described as follows:

```
tuning : None or float
        Tuning offset in fractions of a bin.
        If ``None``, tuning will be automatically estimated from the signal.
        The minimum frequency of the resulting CQT will be modified to
        ``fmin * 2**(tuning / bins_per_octave)``.
```

In addition, the default parameter for tuning in chroma_cqt is None while the default parameter for it in cqt and hybrid_cqt is 0.0.

From my point of view, the description of the tuning parameter in the chroma_cqt function should be the same and therefore be extend with the information about what None actually means.
I'm however not sure about the default values, since it would make sense to me to make those equal, but this may introduce some problems with old code.

**Comment by bmcfee** [comment]
I'm all for clarifying the documentation, so thanks for raising this point.


> In addition, the default parameter for tuning in chroma_cqt is None while the default parameter for it in cqt and hybrid_cqt is 0.0.
> 
> From my point of view, the description of the tuning parameter in the chroma_cqt function should be the same and therefore be extend with the information about what None actually means.
> I'm however not sure about the default values, since it would make sense to me to make those equal, but this may introduce some problems with old code.

This is a rare case where I think having different defaults is the right thing.  The issue comes from the distinction between *pitch* (A, A♯, B, ...) and *frequency* (440, 466, 494, ...).  Chroma is intrinsically a function of pitch, so it makes sense in most cases to automatically align the CQT basis frequencies to the tuning of the signal.  Not all recordings have standard tuning, but for most uses of chroma, a user would expect invariance to small tuning deviations.

More generally though, CQT is a function of *frequency*, and my sense is that there are more applications where the user would expect the frequency grid to remain fixed across signals (i.e. `tuning=0`) than not (`tuning=None`).
