### ISSUE TITLE
How to normalise a wav file with PCEN and export it as wav too ? 

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [librosa/librosa#1611]
Hi,

I initialy posted my question on the wrong project (soundfile) so I post it here again. 

I want to compare PCEN (per channel energy normalisation) to usual normalisation. I found this [example] (https://librosa.org/doc/main/generated/librosa.pcen.html) and now I want to export the normalised signal to a wav file.

```
y, sr = librosa.load(input_wav_file)

    # We recommend scaling y to the range [-2**31, 2**31[ before applying

    # PCEN's default parameters. Furthermore, we use power=1 to get a

    # magnitude spectrum instead of a power spectrum.

    S = librosa.feature.melspectrogram(y=y, sr=sr, power=1)

    log_S = librosa.amplitude_to_db(S, ref=np.max)

    pcen_S = librosa.pcen(S * (2**31))

   sf.write(log_filename, log_S, sr, format="wav", subtype = 'PCM_24')
   sf.write(log_filename, pcen_S, sr, format="wav", subtype = 'PCM_24')
```

I tried to `sf.write()` `pcen_S` variable (or even log_S) but it is nonsense since it is a spectrogram so I got `output format not recognized`. I could try to convert the spectrogram to audio but I already tried to convert the original S (before applying the normalisation) and the output was not good (as expected with griffin lin). But there may be a handier way to do this.

So how can I apply PCEN to an input audio wav file and export it to wav ?

Thanks in advance for your advice

**Comment by bmcfee** [comment]
> I tried to `sf.write()` `pcen_S` variable (or even log_S) but it is nonsense since it is a spectrogram so I got `output format not recognized`.

This is because `pcen_S` or `log_S` are spectrograms, not time-domain audio signals.

> I could try to convert the spectrogram to audio but I already tried to convert the original S (before applying the normalisation) and the output was not good (as expected with griffin lin).


The example above is using mel spectrograms, so reconstructing audio would halve to take the following steps:

1. map Mel PCEN back to linear STFT magnitudes
2. invert the magnitude spectrogram (ie griffin-lim)

You can do both of these in one shot with [mel_to_audio](https://librosa.org/doc/latest/generated/librosa.feature.inverse.mel_to_audio.html), but you'll need to set `power=1`.  I tested this out with the `libri1` example track and it sounds okay - obvious phase recovery artifacts due to griffinlim, and the usual noise that comes with inverse mel projection, but otherwise about what you should expect from PCEN processing (exaggeration of transients).

You could also do PCEN directly on the STFT magnitudes, and use the original phase.  Something like:

```python
D = librosa.stft(y)

mag, phase = librosa.magphase(D)

pcen_S = librosa.pcen(mag* (2**31))

Dpcen = phase * pcen_S

y_pcen = librosa.istft(Dpcen, length=len(y))
```
This of course won't be exactly the same as using pcen on mel bands, but it is not subject to phasing or basis artifacts.

**Comment by Ca-ressemble-a-du-fake** [comment]
Thank you Brian for your clear instructions. I found an answer on stackoverflow about pcen while I was looking for a "neural" normaliser. Because my goal is to amplify differently the different parts of wave files so that the loudest parts remain untouched while the quietest parts reach the same amplitude as the loudest parts.

For example in the beginning the speaker is very close to the microphone and yells and then he whispers very far away from the mic. In an audio editor (eg Audacity), I select the part after the begining and apply some amplification. I want to automate this in my script (the loudest parts can be anywhere) before applyong speexh recognition program. 

I gave your examples a try and it was worse than the original (the spectrum is spread equally for all fresuencies). So I guess this pcen method does not fit my needs. Anyway your answer has helped me better ubderstand how it works !

**Comment by bmcfee** [comment]
> my goal is to amplify differently the different parts of wave files so that the loudest parts remain untouched while the quietest parts reach the same amplitude as the loudest parts.

What you want is a dynamic range compressor, not pcen.  Sox's compand function ought to do everything you need, see https://sox.sourceforge.net/sox.html

**Comment by Ca-ressemble-a-du-fake** [comment]
Thanks again Brian! I am going to reroute my search to dynamic range compressor. FWIW in the mean time I found an interesting python library that claims to use PCEN. So for anyone landing on that question it's  [noisereduce](https://pypi.org/project/noisereduce/).
