### ISSUE TITLE
Overflow in `feature.rms` when dtype='int16'

### ISSUE THREAD

**Issue by ajwrigley** [librosa/librosa#1656]
Edit - I guess this is because you're supposed to only use float with librosa?

```
In [1]: import numpy as np
In [2]: from librosa import feature
In [3]: y = np.random.randint(-32768, 32768, 10000, dtype='int16')
In [4]: feature.rms(y=y, frame_length=256, hop_length=32)
venv/lib/python3.8/site-packages/librosa/feature/spectral.py:981: RuntimeWarning: invalid value encountered in sqrt
  return np.sqrt(power)
```

The `RuntimeWarning` is because it's trying to compute the sqrt of a negative (overflowed) number.

**Comment by bmcfee** [comment]
That's a good question.  Nothing in the docs or definition suggests that small int inputs are *not* supported, but I think it's sane to expect a floating point conversion at some point in the computation.  That's not happening because `util.abs2` preserves dtype implicitly for real-valued inputs (including int):

https://github.com/librosa/librosa/blob/bd4cd2009c126da744780d4f4b04a7efc32fd618/librosa/util/utils.py#L2509-L2514

Probably the easiest fix here is to extend the `abs2` function to support an output dtype, and replacing `x**2` by `np.power(x, 2, dtype=dtype)`.  It might take a little finagling to make this square with the numba-accelerated implementation for complex inputs, but I think it's doable.

Shorter term: you could obviously resolve this from the user side by casting to float first.
