### ISSUE TITLE
Should librosa retrieve its own DOI on the web?

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#1674]
Since #1666 (which closed #1659), we're doing a better job than before at crediting Librosa contributors on Zenodo: see `scripts/create_author_list.py` and its result `.zenodo.json`.

And what a nice result: https://zenodo.org/record/7650421

But i'm a little concerned of human errors in credit attribution. The Zenodo webpage is not super intuitive: one has to scroll down to the "Cite as" panel or access a suffix page (`/export/hx`) to view the corresponding BibTeX entry.

Besides, the fact that we have a DOI for the latest version + a separate DOI for every version (including release candidates) is nice but makes things even more complicated for users: they need to look up their version of librosa, visit Zenodo, scroll to the appropriate version, and eventually download the appropriate resource (BibTeX or something else).

Hence my proposal: a utility function (say, `librosa.cite()`) which returns all the metadata information (DOI, author list ...) of the currently installed version. This is not entirely obvious because the DOI is not included in the release. It's the other way around: the creation of a GitHub tag triggers a new, random DOI. So implementing `librosa.cite()` would necessarily involve an Internet query.

I have begun to look into the feasibility of this, and found the `pyzenodo3` package. This works:

```python
import ast
import pyzenodo3

zen = pyzenodo3.Zenodo()
record = zen.find_record_by_github_repo('librosa/librosa')
record_dict = ast.literal_eval(str(record))
```

Unfortunately, the `record.get_versions()` method is broken. So i anticipate that we're going to have to write some in-house code for this. Ideas welcome But i would also like to hear everyone's thoughts on what the inputs and outputs of `librosa.cite()` should be, and whether it's a good idea at all.

**Comment by bmcfee** [comment]
I'd rather not add a zenodo dependency to librosa directly.  Instead, I propose that we have a script that can run offline / post-publication, which queries zenodo for the DOI and persists the relevant citation data (in any/all formats) to a data file.

This data file can then be pushed up to https://github.com/librosa/data under a `cite/` folder.

We can then implement `librosa.cite()` to use pooch (already a dependency) to grab the DOI from our store rather than querying zenodo directly.  We can also allow `librosa.cite` to take a `version=` parameter to get historical DOIs (default will be current release version).

A couple of caveats here:

1. We'll need to store the citation data for each version in its own file to avoid cache staleness.
2. We might need to add a `latest_release` field to the `librosa.version` submodule.  Using the version string directly will get us into trouble when working on, say, `0.10.1dev` (which will not have a release / DOI), and we'll need to fall back.
3. In the above case (dev / rc), we should issue a warning.
4. It would be nice, but not necessary, to automate the DOI fetching from zenodo through a github action, just to cut down on things I/we need to do on each release.  It should be possible, but it seems like a low priority to me.

**Comment by lostanlen** [comment]
Thanks for your answer @bmcfee and for scheduling this for 0.10.1
I agree with 1/2/3/4

One thing that remains to be discussed is what should be the output of `cite()`, exactly? String, dict, other?

**Comment by bmcfee** [comment]
I think having cite() print the result to the console is reasonable and consistent with other related helpers (show_versions, example_ibfo, etc).

What format gets printed is a question though.  I could imagine storing several citation formats (bibtex, mla, whatever) in the data files and allowing the user to select by an argument (format=...).

**Comment by bmcfee** [comment]
Note: for this scheme to work with asynchronous updates to the citation registry, we'll need to disable hash checks https://www.fatiando.org/pooch/latest/hashes.html#bypassing-the-hash-check

**Comment by bmcfee** [comment]
Looking into this one again, I'm not sure it will be easy to add a citation format parameter here.  At least not without adding a lot of dependencies.

How about as an alternative, we have it print out the DOI / Zenodo URL?  That will bring the user to the correct page for exporting citation data.  A little clumsier than a direct printout, but probably easier to maintain.

**Comment by bmcfee** [comment]
Ok, after a bit of fiddling, I have a reasonable script working that can pull all zenodo DOIs for us and save them in a msgpack file to push over in librosa-data.  I'll get a PR going for this feature today.
