### ISSUE TITLE
First call of a function slower than subsequent calls

### ISSUE THREAD

**Issue by LChouraki** [librosa/librosa#1697]
Hi,

I have a program that uses librosa and several of its functions. I noticed that the first function called takes much longer to execute than the subsequent ones. Simply put, if I call the same function with the same arguments in a loop, the first execution will take longer than all the following ones. 

On my Mac, the variations are on the order of several hundred milliseconds, and on my Raspberry Pi, several seconds. I tested this with several functions including librosa.feature.chroma_stft and librosa.yin, and I observe the same phenomenon. The problem only seems to appear with the 0.10.x version. With older ones, the first execution is only 30ms longer so it is ok I guess.

**To reproduce**

```
import librosa
import numpy as np
from time import time

sr = 44100
audio = np.zeros(20 * sr)
n = 5
times = np.zeros(n)
'''dummy = librosa.yin(np.zeros(2048), fmin=50, fmax=4186, sr=sr,
                    frame_length=2048, hop_length=256)'''

for i in range(n):
    start = time()
    yin_frames = librosa.yin(audio, fmin=50, fmax=4186, sr=sr,
                                         frame_length=2048, hop_length=256)

    print(time() - start)
```

If you uncomment the dummy call to librosa.yin, you will see executions last the same time. If you change the dummy function to another librosa function (like times_to_frames), you could see that the first execution in the loop last longer than the others but it still a bit faster than if no dummy fucntion was called.
I tried different python versions and the problem is still there. 

I also noticed that if I have several processes running the same function in which there are calls to a  few librosa functions, each thread will have its first function slowed. But if I do a dummy call before starting my threads, every of them will run the functions normally. So maybe it is a memory related. 

Actually, I don't know if this behaviour is expected but I don't think so since it is not present in older version. 
In any case, I would like to know what is happening so thank you in advance for your response.

**Software versions**

macOS-13.0.1-arm64-arm-64bit
Python 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ]
NumPy 1.23.5
SciPy 1.10.0
librosa 0.10.0.post2

INSTALLED VERSIONS

python: 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ]

librosa: 0.10.0.post2

audioread: 3.0.0
numpy: 1.23.5
scipy: 1.10.0
sklearn: 1.2.0
joblib: 1.2.0
decorator: 5.1.1
numba: 0.56.4
soundfile: 0.12.1
pooch: v1.6.0
soxr: 0.3.4
typing_extensions: installed, no version number available
lazy_loader: installed, no version number available
msgpack: 1.0.5

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
matplotlib: 3.6.2
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib.rsvgconverter: None
pytest: None
pytest_mpl: None
pytest_cov: None
samplerate: None
resampy: 0.4.2
presets: None
packaging: 22.0

**Comment by bmcfee** [comment]
There are two causes for this kind of thing:

1. We use lazy_loader to speed up module import time for the main package, and avoid loading submodules and dependencies until they are actually requested.  (Many libraries do this now, e.g. scikit-image.)  Basically this shifts the latency that you would normally see at import time until the first function call - this is latency that you will see no matter what, it's just a question of when it happens.
2. numba jit compilation.  Many of the functions in librosa use numba to just-in-time (jit) compile helper routines so that they run faster.  Like lazy-loading, this does not happen until the first time the function is requested, and the additional time is due to the compiler.  Subsequent runs of the same function will use the already compiled version of the function.

For (2), we try to amortize this compilation cross across sessions by using `cache=True` on numba files.  This stores the compiled functions to disk, so they can be reused in the future.  But the first call will always cost something.



> I also noticed that if I have several processes running the same function in which there are calls to a few librosa functions, each thread will have its first function slowed. But if I do a dummy call before starting my threads, every of them will run the functions normally. So maybe it is a memory related.

This to me suggests that you're seeing the effect of lazy loader.  If you have a control process that forces the import before spawning new threads, then the submodules will have been imported already and no subsequent loading is necessary.


If you want to bypass lazy loading in your environment, you can do so by setting the `EAGER_IMPORT` environment variable before starting your python process (or within python but before importing librosa the first time).  See https://scientific-python.org/specs/spec-0001/#usage

**Comment by LChouraki** [comment]
Thanks for the explanation! I will take a look at the EAGER_IMPORT variable
