### ISSUE TITLE
Web frontend plays audio stream generated by 'librosa.stream + yield' from the backend, but experiences stuttering.

### ISSUE THREAD

**Issue by x1982** [librosa/librosa#1729]
**Describe the bug**
As stated in the title, my code is as follows: 
```
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from flask import Flask, Response
import librosa, os, io, soundfile

app = Flask(__name__)

@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def process_audio(path):
    audio_path = '/mnt/path/to/' + path

    def generate():
        sr = librosa.get_samplerate(audio_path)

        block_length = 1024
        stream = librosa.stream(audio_path,
                                block_length=block_length,
                                frame_length=512,
                                hop_length=512,
                                mono=False)

        for audio in stream:
            buffer = io.BytesIO()
            soundfile.write(buffer, audio.T, sr, format='mp3')
            yield buffer.getvalue()

    file_size = os.path.getsize(audio_path)
    headers = {
        'Accept-Ranges': 'bytes',
        'Content-Type': 'audio/mpeg',
        'Content-Length': file_size,
    }
    return Response(generate(), mimetype='audio/mpeg', headers=headers)    


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8081, debug=True)
```

Please note the variable "block_length" in the code, its current value is 512. Based on the observation, the audio played in the frontend will experience a brief stutter every 6 seconds.

If you modify block_length to 1024, the music will experience a brief stutter every 12 seconds. This phenomenon occurs due to the segmentation performed by librosa.stream().

During testing, it was observed that when using librosa.load() to read a file in chunks, the same issue occurs, while reading the entire file at once works fine.

**To Reproduce**
1. Configure a website in Nginx and set up a location block. 
```
 location  /storage/music {
       proxy_pass              http://127.0.0.1:8081;
 }
```
2. Create a directory named app in the project's root directory and place a file named test.py inside it, containing the mentioned code.
3. Run the following command in the project's root directory: 'python -m app.test'.
4. The file test.mp3 should exist in /mnt/path/to/storage/music.
5. You can open "http://xxx.xxx/storage/music/test.mp3" in Chrome to listen to the music. If you listen carefully, you may notice brief stutters at certain moments.

When comparing with native code, there is no stuttering issue observed. The native code is the same as mentioned before, but with the generate() function replaced with the following code. Everything else remains unchanged.
```
    def generate():
        with open(audio_path, 'rb') as f:
            while True:
                data = f.read(10240)
                if not data:
                    break

                time.sleep(0.5)
                yield data
```

**Additional context**
The project is running in a Python 3 virtual environment.

**Comment by bmcfee** [comment]
Thanks for the thorough report.


There's a lot going on here, but I don't think anything in `librosa.stream` is at fault here.  `librosa.stream` is a reasonably simple wrapper around `soundfile.blocks` that exists mainly to simplify the API for stream-processing overlapping frames.  Since you have `frame_length=hop_length` here, `blocks` will be called with `overlap=0`, and the `stream()` generator is not actually doing any non-trivial work.  That is to say, you could rewrite this entirely without using librosa and will very likely still see the same stuttering effect.

Now, there could be a couple of other things to blame here.  My first hunch is that it has to do with how you're encoding each frame separately.  Do you also see the stuttering behavior if using wav or ogg as your output encoding?  It may be that encoding short blocks of mp3 in this fashion can create some frame alignment issues.

You could also simplify this by pulling this entirely out of a web server context, and dumping the output buffer out to a binary file.  This would help isolate the problem to either the flask streaming part or the output encoding part of your application.

On the topic of flask and audio streaming, I have in the past encountered some issues with flask doing this kind of thing.  The LSDViz package has some reusable code for hacking around this that might be useful to you:
https://github.com/bmcfee/lsd_viz/blob/426f9e03e9bcf3418ce0c3937b1ed8f5f3a4f67b/lsdviz.py#L48-L96
(attribution is from https://blog.asgaard.co.uk/2012/08/03/http-206-partial-content-for-flask-python )

**Comment by x1982** [comment]
Thank you for reading carefully and providing an excellent response.

Actually, my original requirement was to use librosa for sound processing, which can be time-consuming. Therefore, I had a new requirement for "streaming" support. The link you provided is great, but once I use "open() + read()", librosa cannot intervene, which means I cannot use librosa.stft() or librosa.fft_frequencies().

**Comment by bmcfee** [comment]
> I have a rough understanding of this stuttering issue, and it seems unrelated to `librosa`. It is likely a problem with `soundfile`.

Ok, thanks for confirming that.  I think there's nothing to do from our side then, as it seems strictly related to stream encoding (soundfile's job) and not analysis (librosa's job).



> Actually, my original requirement was to use librosa for sound processing, which can be time-consuming. Therefore, I had a new requirement for "stream" support. The link you provided is great, but once I use "open() + read()", `librosa` cannot intervene, which means I cannot use `librosa.stft()` or `librosa.fft_frequencies()`.

I don't see why this should be the case.  I'm sure the full application is more complex than your initial issue, but it's unclear to me why you need to re-encode the audio stream after analysis instead of just streaming the file directly.  Your example code does not modify the audio buffer, so you could get away with decoupling the analysis and audio streaming parts of the application, and that would likely resolve the problem for you.

**Comment by x1982** [comment]
When opening `http://xxx.xxx/storage/music/test.mp3` in a browser, apply audio enhancement using `librosa.stream()`, `librosa.stft()`, and `librosa.fft_frequencies()` functions. The enhancement involves increasing the gain of several low-frequency and high-frequency components. If the entire file is processed and outputted as a whole, it takes around a dozen seconds for a song to reach the browser. Hence, streaming processing is employed, where the code example provided is annotated as follows:
```
for audio in stream:
    # The processing of audio using librosa.stft() and librosa.fft_frequencies() here takes some time.
    
    # Outputting the data in a streaming manner using yield.
    buffer = io.BytesIO()
    soundfile.write(buffer, audio.T, sr, format='mp3')
    yield buffer.getvalue()
```
Previously, I considered that sharing too much code upfront might affect your reading, so I simplified the code to only include the essential parts that illustrate the issue. Thank you for your patient response. I will further investigate the problem caused by soundfile on my own. Of course, if you are willing to assist me, thank you in advance.

**Comment by bmcfee** [comment]
Gotcha, that makes sense.

It does sound like for what you're doing (low- and high-boost filtering) librosa might be overkill.  If you know the frequency ranges in advance, you could probably do this whole thing more effectively just via scipy.signal tools (sosfiltfilt with a pre-designed elliptic notch filter).  That ought to be fast enough to avoid the need for block-based processing.

**Comment by x1982** [comment]
Due to my limited technical knowledge and unfamiliarity with "scipy.signal," I sought help from ChatGPT, but most of the code suggestions provided were incorrect. In the end, it still recommended using "librosa." I appreciate the outstanding open-source library "librosa" for enabling me to achieve the equalizer effect similar to desktop or mobile music players using librosa.stft() and librosa.fft_frequencies(). This way, I don't have to rely on whether the playback device has an equalizer or not. Instead, I rely solely on the web server output, which provides a better audio experience. Although it is not perfect so far, it is sufficient for personal enjoyment. I apologize for the inconvenience caused over the past few days, and I am truly grateful for your assistance.

**Comment by bmcfee** [comment]
> I sought help from ChatGPT, but most of the code suggestions provided were incorrect. In the end, it still recommended using "librosa."

The bot isn't always right :smile: - I do think scipy.signal would be entirely sufficient (and better) for what you're doing.  If you want a bit more of a primer on using it for filtering, you might want to check out [chapter 11](https://brianmcfee.net/dstbook-site/content/ch11-iir/intro.html) of my book.  It shows how to do a basic low-pass filter, but once you have that down, the scipy filter constructors make it pretty simple to extend it to a band-stop design.

**Comment by x1982** [comment]
Where can I find your book? Please provide the URL. I'll make an effort to give it a try 😄
