### ISSUE TITLE
Parameter Error when replicating the Vocal Separation tutorial

### ISSUE THREAD

**Issue by prateek-joshi** [librosa/librosa#1733]
**Describe the bug**
I am trying to run the [vocal separation tutorai](https://librosa.org/doc/latest/auto_examples/plot_vocal_separation.html#sphx-glr-auto-examples-plot-vocal-separation-py) on a short audio in colab environment. But I keep running into a Parameter error on the following line:
```python
S_filter = librosa.decompose.nn_filter(S_full,
                                       aggregate=np.median,
                                       metric='cosine',
                                       width=int(librosa.time_to_frames(2, sr=sr)))
```
```
ParameterError                            Traceback (most recent call last)
<ipython-input-21-d6c0be7d8ffb> in <cell line: 1>()
----> 1 S_filter = librosa.decompose.nn_filter(S_full,
      2                                        aggregate=np.median,
      3                                        metric='cosine',
      4                                        width=int(librosa.time_to_frames(2, sr=sr)))

1 frames
/usr/local/lib/python3.10/dist-packages/librosa/segment.py in recurrence_matrix(data, k, width, metric, sym, sparse, mode, bandwidth, self, axis, full)
    591 
    592     if width < 1 or width >= (t - 1) // 2:
--> 593         raise ParameterError(
    594             "width={} must be at least 1 and at most (data.shape[{}] - 1) // 2={}".format(
    595                 width, axis, (t - 1) // 2

ParameterError: width=86 must be at least 1 and at most (data.shape[-1] - 1) // 2=24
```

**To Reproduce**
Run the code as given in the tutorial and use the following [audio](https://drive.google.com/file/d/1NWybU3Bpp_CxnEs0ca69BSJw1eoTLEWP/view?usp=sharing)

**Additional context**
The audio is in stereo format and only ~2 sec long, not sure if that is relevant here

**Comment by bmcfee** [comment]
> The audio is in stereo format and only ~2 sec long, not sure if that is relevant here

Yes, this is the problem.  The demo notebook uses a 2-second window to suppress local nearest-neighbor connections:

```
width=int(librosa.time_to_frames(2, sr=sr)))
```
So if your entire clip is only two seconds long, then this will prevent the method from identifying *any* repetitions.  You can drop that `2` to something more appropriate for your clip, say, 0.25 or something, but this is fundamentally a limitation of the repet-sim method since the whole idea is to identify repeating (musical) structures.  If your clip is too short to contain repetitions, the method will not be appropriate.

**Comment by prateek-joshi** [comment]
Understood. I will explore other options. Thanks.
