### ISSUE TITLE
Basic Question on Principle of Spectral Feature Extraction - librosa

### ISSUE THREAD

**Issue by melisasaygin** [librosa/librosa#1774]
I am aware of what the different spectral descriptors as given by librosa are referring to, though I have seen some other Python packages and MATLAB directly derive (for ex. spectral centroid) by taking 1 FFT of the whole specified window, and then getting one spectral centroid directly. However, librosa finds the spectral centroid via short term Fourier transform for the window I gave (so many of them, one for every short term window of my initial window). I am assuming if I take the average of those, it will still be similar to what I would get if I did one FFT and calculated spectral centroid from that, right? Also, is there any advantage in taking a bunch of STFTs instead of just doing 1 FFT? And if so, is this a major advantage (or is the 1-time FFT good enough)? (I am trying to do voice activity detection with accelerometers).

**Comment by bmcfee** [comment]
The short answer is that these are generally not going to be the same thing.

Remember that the DFT integrates over all time to compute the spectrum.  If your frequency content changes over time - as is the case in speech / VAD, for example - then you will get different results when looking at short time slices (STFT) than when integrating over the whole signal.

Additionally, if you use a DFT over the whole signal, then two signals of different lengths will not produce directly comparable spectra because their frequency resolutions will be different.  For a signal of N samples, the DFT carves up the frequency range (± sampling rate / 2) into N pieces, or 1 + N//2 if you're only considering the non-negative frequencies (as we usually do).  This isn't a huge problem if you're only looking at one signal at a time, but when you want to start working this into machine learning applications where you're generalizing over multiple signals, it can present problems.  Using the STFT in this case fixes the frequency resolution so that different signals will produce comparable spectra (though the number of frames will of course vary with the duration of the signal).

**Comment by melisasaygin** [comment]
I want to train and also detect per every 30 second block (I have blocks of no speech and continuous speech). So, the signals would be of almost the same length for every block. But then still, doing a bunch of STFTs and then averaging that (the output I get from librosa) is better, I assume?

**Comment by bmcfee** [comment]
> So, the signals would be of almost the same length for every block.

"Almost" here is the kicker.  If the signals are not of exactly the same length, then a single DFT approach would still not produce outputs of compatible dimension.

One piece of advise that I often give about setting up STFT parameters is to try to reason about it from the perspective of the data.  What's the lowest frequency you care about capturing?  The lowest (nonzero) frequency in an N-point DFT is `f = [sampling rate] / N`.  It's okay for this frequency to be a little below what you actually care about; think of this as giving your DFT enough time to observe a few cycles of the frequency you care about.

For example, a 30-second DFT (e.g., `N= 30 * sampling_rate`) would give you a minimum measurable frequency of `sr / (30sr) = 1/30 [Hz]` - well below what humans can perceive.  Is this frequency important to capture for your application?  (I'm guessing it's not.)
