### ISSUE TITLE
librosa.load performance degradation when switching from version 0.9.1 to version 0.9.2 or later. 

### ISSUE THREAD

**Issue by cpuheater** [librosa/librosa#1777]
**Describe the bug**
Experiencing performance degradation when switching from version 0.9.1 to version 0.9.2 or later, 
wav file is encoded using the u-law algorithm.

**To Reproduce**

```
import librosa
import numpy as np
import time

emulated_sr=8000
audio_path = "some.wav"
start_time = time.time()
audio_signal, _ = librosa.load(
    audio_path,
    sr=emulated_sr,
    mono=True,
    offset=None,
    duration=None,
    dtype=np.float32,
    res_type="polyphase",
)
print(time.time() - start_time)
```
**output:**
0.002964 ms using librosa==0.9.1
0.09288 ms using version librosa==0.9.2

**Expected behavior**
Execution time should be similar

```
Linux-5.13.0-1031-aws-x86_64-with-glibc2.10
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
NumPy 1.23.4
SciPy 1.10.1
librosa 0.9.1
INSTALLED VERSIONS
------------------
python: 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

librosa: 0.9.1

audioread: 2.1.9
numpy: 1.23.4
scipy: 1.10.1
sklearn: 0.24.2
joblib: 1.1.0
decorator: 5.1.1
soundfile: 0.12.1
resampy: 0.2.2
numba: 0.57.0

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 7.0.0
pytest-mpl: None
pytest-cov: None
matplotlib: 3.4.1
presets: None
```

**Comment by bmcfee** [comment]
Can you include a dependency list for both versions of librosa you're trying here?

From a quick read of the changelog, there's nothing between 0.9.1 and 0.9.2 that should cause significant changes in file loading.

However, doing timing as you are is not entirely stable. It would be better to use the timeit utility to do multiple runs and amortize any startup costs than to just run once with time().

**Comment by cpuheater** [comment]
Here is a dependency list for version 0.9.2:

Linux-5.13.0-1031-aws-x86_64-with-glibc2.10
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
NumPy 1.23.4
SciPy 1.10.1
librosa 0.9.2
INSTALLED VERSIONS
------------------
python: 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

librosa: 0.9.2

audioread: 2.1.9
numpy: 1.23.4
scipy: 1.10.1
sklearn: 0.24.2
joblib: 1.1.0
decorator: 5.1.1
soundfile: 0.12.1
resampy: 0.2.2
numba: 0.57.0
pooch: v1.6.0
packaging: 21.3

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib-svg2pdfconverter: None
pytest: 7.0.0
pytest-mpl: None
pytest-cov: None
matplotlib: 3.4.1
samplerate: 0.1.0
soxr: 0.3.6
contextlib2: None
presets: None

**Comment by bmcfee** [comment]
Thanks for the additional environment details.

For reference, https://github.com/librosa/librosa/compare/0.9.1...0.9.2#diff-a049e12bb4a0916876dafe207b2943bcb904796584478f19a2a350f0f979bcf1 shows the changes to load between 0.9.1 and 0.9.2 releases.  There's a bit of refactoring here to support reading existing audioread objects, but otherwise no substantial changes in how things are processed.

I'm trying to replicate in my own environment and a wav (natively at 44100), first with 0.9.1:

```python
In [8]: print(librosa.__version__)
0.9.1

In [9]: %%timeit
   ...: audio_signal, _ = librosa.load(
   ...:     audio_path,
   ...:     sr=emulated_sr,
   ...:     mono=True,
   ...:     offset=None,
   ...:     duration=None,
   ...:     dtype=np.float32,
   ...:     res_type="polyphase",
   ...: )
   ...: 
   ...: 
6.41 ms ± 38.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
and without resampling:
```python
In [6]: %%timeit
   ...: audio_signal, _ = librosa.load(
   ...:     audio_path,
   ...:     sr=None,
   ...:     mono=True,
   ...:     offset=None,
   ...:     duration=None,
   ...:     dtype=np.float32,
   ...:     res_type="polyphase",
   ...: )
   ...: 
   ...: 
234 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
Now with 0.9.2:
```python
In [6]: %%timeit
   ...: audio_signal, _ = librosa.load(
   ...:     audio_path,
   ...:     sr=emulated_sr,
   ...:     mono=True,
   ...:     offset=None,
   ...:     duration=None,
   ...:     dtype=np.float32,
   ...:     res_type="polyphase",
   ...: )
   ...: 
   ...: 
6.48 ms ± 42.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
and without resampling:
```python
In [7]: %%timeit
   ...: audio_signal, _ = librosa.load(
   ...:     audio_path,
   ...:     sr=None,
   ...:     mono=True,
   ...:     offset=None,
   ...:     duration=None,
   ...:     dtype=np.float32,
   ...:     res_type="polyphase",
   ...: )
   ...: 
   ...: 
249 µs ± 3.39 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

So I think this is all exactly as expected.  The deviation you initially reported is probably due to taking only a single timing measurement, which as mentioned above, is susceptible to random fluctuation (due to varying system load), as well as initial startup cost.  I expect that if you repeat these measurements using the timeit utility, the reported difference should vanish.

I'll close this issue out, but feel free to reopen if you still see substantial differences after doing repeated measurements.
