### ISSUE TITLE
The feature module of version 0.10.x has bugs.

### ISSUE THREAD

**Issue by keylxiao** [librosa/librosa#1794]
when I am using librosa0.10.1，my pycharm can't detect the feature module and mfcc function，and I changed the version to 0.10.0 and the problem still exist. When I call the.py file directly from python on the command line, I get an error:

MFCCs = librosa.feature.mfcc(signal, n_fft=n_fft, hop_length=hop_length, n_mfcc=13)
TypeError: mfcc() takes 0 positional arguments but 1 positional argument (and 1 keyword-only argument) were given

Then I changed the version to 0.9.2, and the program worked fine, I checked the update announcement for version 0.10.x and it doesn't seem to mention changes to the feature module and mfcc function.

**Comment by bmcfee** [comment]
There are several unrelated things here, but as far as I can tell, there is no problem from the librosa side.

First:


> when I am using librosa0.10.1，my pycharm can't detect the feature module and mfcc function

This sounds like pycharm not cooperating properly with lazy loading and type annotations.  A quick googling turns up https://stackoverflow.com/questions/47267105/how-to-force-pycharm-to-evaluate-tensorflow-contrib-lazyloader-so-it-auto-comple - which appears to be the same problem.  I don't know how to fix this, not being a pycharm user, but you might be able to trick it by explicitly importing `librosa.feature` at the top of your script.  This shouldn't be necessary, but IDEs are sometimes not as clever as they try to be and need a little help.



> When I call the.py file directly from python on the command line, I get an error:
> 
> MFCCs = librosa.feature.mfcc(signal, n_fft=n_fft, hop_length=hop_length, n_mfcc=13) TypeError: mfcc() takes 0 positional arguments but 1 positional argument (and 1 keyword-only argument) were given

The error message tells you exactly what the problem is: you need to explicitly parametrize the function call, eg `mfcc(y=signal, ...)` and not `mfcc(signal, ...)`.


> I checked the update announcement for version 0.10.x and it doesn't seem to mention changes to the feature module and mfcc function.

This is noted in the changelog under "deprecations" at the 0.10.0 release.  FWIW, it wasn't "working fine" in 0.9.2 - it should produce warnings telling you that the behavior will change in the upcoming 0.10 release.  If you're not seeing these warnings, it's probably because your warning filter is set too high.
