### ISSUE TITLE
Question: Spectrogram magnitude and summing back to rms

### ISSUE THREAD

**Issue by sammlapp** [librosa/librosa#1795]
Hi, this question stems from lack of understanding rather than an issue with Librosa. Thanks for any input you can provide @bmcfee or others

In various applications, it makes sense to create a spectrogram, perhaps manipulate the values, then restore the time-windowed rms values presumably by summing the columns of the spectrogram. 

I found this documentation of `librosa.rms`, which successfully restores the original rms value after stft: 
https://github.com/librosa/librosa/blob/8dae20c66353190749486abf6b332d93c4ab2b46/librosa/feature/spectral.py#L852-L853

and this returns a similar rms value even when the window size is changed, as long as its changed in all places (see example below). However, changing the `window` parameter in `librosa.stft` (for example, using the default window instead of `np.ones`) dramatically changes the value computed by `rms(stft(y))`. This was surprising to me, as I expected the window functions to be normalized in a way that doesn't change the average output magnitude. 

Q1: Is using a rectangular window (`np.ones`) necessary to retain the original signal level?

Q2: Additionally, could you please explain briefly why the rms is calculated like this:
https://github.com/librosa/librosa/blob/8dae20c66353190749486abf6b332d93c4ab2b46/librosa/feature/spectral.py#L896-L904

Specifically, why the multiplication by 2 and division by `frame_length**2` in L904? And why does finding the rms of the total signal involve performing a root mean square across frequency components, rather than a sum or mean? Sorry for being a signal processing newb here. 

Q3: Reproducing the same values in scipy.signal.spectrogram?
If I use `scipy.signal.spectrogram` with the same parameters, the value returned are equivalent to librosa.stft _divided by frame_length_, rather than being the same values. Why does this difference of a factor of `frame_length` arise? Do these functions intentionally return values with different scaling for some specific reason? 

(Side note, I was surprised that the mean of rms actually gets slightly lower as window length decreases, but I imagine there's some mathematical explanation for it)
```python
w = []
r=[]
for i in range(5,13):
    win_len = 2**i
    w.append(win_len)
    S = librosa.magphase(librosa.stft(a.samples, window=np.ones, center=False,win_length=win_len,n_fft=win_len,hop_length=win_len//2))[0]
    ri = librosa.feature.rms(S=S,frame_length=win_len,hop_length=win_len//2).mean()
    r.append(ri)
    print(f"window len: {win_len}: rms {ri:.3f}")
plt.scatter(w,r)
plt.semilogx()
```
prints
```
window len: 32: rms 0.182
window len: 64: rms 0.184
window len: 128: rms 0.187
window len: 256: rms 0.189
window len: 512: rms 0.190
window len: 1024: rms 0.192
window len: 2048: rms 0.193
window len: 4096: rms 0.194
```

**Comment by bmcfee** [comment]
> Q1: Is using a rectangular window (`np.ones`) necessary to retain the original signal level?

Basically, yes.

Windowing is nothing more than element-wise multiplication following by a DFT.  Ignoring everything about framing here (which will be the same process for each frame independently), we'd have `dft(window * x)`.  We make no assumptions about `window` - these need not be normalized, and a user can provide any appropriately shaped array as a window if they like.  Even if windows were normalized, that is not enough to produce a Parseval-like result, that the L2 norm in the frequency domain would be equivalent to that of the time-domain.

As simple example, consider a 4-point Hann window: `w = [0. , 0.5, 1. , 0.5]` and let x be an impulse (`x = [1, 0, 0, 0]).  From the DFT's perspective, the input `w*x` will be an all zeros array, and there's nothing really you can do (eg in terms of normalization) to recover from that.


> Q2: Additionally, could you please explain briefly why the rms is calculated like this:

A couple of things are going on here (and this relates to your next question).  First, we're using the "standard" unnormalized DFT here.  So the norm in the frequency domain is actually scaled by √N compared to the norm in the time domain (for a frame length of N samples).  So to recover the time-domain norm, we need to divide out by the length of the frame.

The second thing going on is that we're using rfft, that is, retaining only the non-negative frequencies instead of all N analysis frequencies.  Since we only have half as many frequencies as we would with a full spectrum, we exploit conjugate symmetry to double-count each frequency since the magnitude associated with frequency k would be equal to that of frequency N-k (its conjugate pair).  This is done implicitly by doubling the magnitude measurements (the `2*` in line 904), but there are two exceptions we need to handle.  First, the 0 frequency is self-conjugate (0 is equivalent to N-0 modulo N), so it does not need to be double-counted; this is why we divide it by 2 up front.  Second, the Nyquist frequency is also self conjugate (N/2 = N - N/2) **if it exists** - but it only exists when the frame length is even.  If the frame length is odd, we do not have a bin for Nyquist, hence the condition at line 900.

> Q3: Reproducing the same values in scipy.signal.spectrogram?
> If I use scipy.signal.spectrogram with the same parameters, the value returned are equivalent > to librosa.stft divided by nfft, rather than being the same values. Why does this difference of a factor of nfft arise? 

This is related to the above - we use unnormalized Fourier transforms in our STFT, and scipy's spectrogram does not.  There are good arguments for either way of doing it - we opted for consistency with a vanilla (single-frame, unnormalized) DFT; scipy opted for consistency as frame length varies.



> Side note, I was surprised that the mean of rms actually gets slightly lower as window length decreases, but I imagine there's some mathematical explanation for it

Hard to say without knowing what your input example is.  You'd probably have a better grip on it by looking at the disaggregated (per-frame) RMS values rather than just the mean.

**Comment by sammlapp** [comment]
Thanks @bmcfee for your detailed answer, this is super helpful! Feel free to close the issue

**Comment by sammlapp** [comment]
One additional question. Scaling scipy.signal.spectrogram by `window` results in equivalent output _except_ for the first (0 Hz) bin, which differs drastically. Is this some difference in implementation related to removing a DC output? (manually removing the DC offset lowers the 0 Hz bin value of librosa's output below but it's still non-zero)

```python
np.random.seed(0)

sr = 48000
x = np.random.uniform(0,1,sr*3)
# x = x-x.mean()

w=512
f,t,spec=scipy.signal.spectrogram(
    x=x,
    fs=sr,
    mode='magnitude', #not psd, just amplitude
    scaling='spectrum', #units will be V, not V/Hz
    nperseg=w,
    nfft=w,
    noverlap=w//2,
    window=np.ones(w),
    return_onesided=True,
)
print((spec*w).mean(1)[0:5])
S=librosa.magphase(librosa.stft(x, window=np.ones, center=False,win_length=w,n_fft=w,hop_length=w//2))[0]
print(S.mean(1)[0:5])

```
prints:
```
[1.69608831e-14 5.91338736e+00 5.91960365e+00 5.77714518e+00 5.89774409e+00]
[256.1256804    5.91338736   5.91960365   5.77714518   5.89774409]
```

or, with `x=x-x.mean()`:
```
[5.13463306e-15 5.91338736e+00 5.91960365e+00 5.77714518e+00
 5.89774409e+00]
[4.87985961 5.91338736 5.91960365 5.77714518 5.89774409]
```

**Comment by bmcfee** [comment]
> Scaling scipy.signal.spectrogram by `window` results in equivalent output _except_ for the first (0 Hz) bin, which differs drastically.

Try adding `detrend=False` to scipy.  Your input samples are non-negative, so the DC component should be a strictly positive number (as librosa's produces).  Scipy is giving you a numerically zero value for DC probably because it is detrending each frame.

**Comment by sammlapp** [comment]
Thanks! For future reference to myself/others, scipy.signal.spectrogram will produce the same (very close) values to librosa.stft, up to the multiplication of `window_size` in the librosa result, using these settings:

```python
import numpy as np
import scipy
import librosa

np.random.seed(0)

sr = 48000
x = np.random.uniform(0,1,sr*3)+0
w=512
f,t,spec=scipy.signal.spectrogram(
    x=x,
    fs=sr,
    mode='magnitude', #not PSD V**2, just amplitude V
    scaling='spectrum', #units will be V, not V/Hz
    nperseg=w,
    nfft=w,
    noverlap=w//2,
    window=np.ones(w), #rectangular window
    return_onesided=True,
    detrend=False, # default of True results in different value for 0 Hz bin
)

S=librosa.magphase(librosa.stft(x, window=np.ones, center=False,win_length=w,n_fft=w,hop_length=w//2))[0]

# scipy's spec * w is equal to librosa's S 
print((spec*w).mean(1)[0:5])
print(S.mean(1)[0:5])

print(f"all values similar? {(np.abs(spec*w-S)<1e-6).all()}") # prints True
```
