### ISSUE TITLE
Allow kwargs for stft/istft in `effects.hpss`

### ISSUE THREAD

**Issue by th0ger** [librosa/librosa#1804]
**Is your feature request related to a problem? Please describe.**
I needed to apply HPSS on a source `y` with non-default `n_fft`, `hop_length`, `win_length`, and wanted to use [effects.hpss](https://librosa.org/doc/0.10.1/generated/librosa.effects.hpss.html)
But it only allows supplying kwargs to `decompose.hpss`.

**Describe the solution you'd like**
Add parameter `kwargs_stft` (dictlike) that will be unpacked/passed on to `stft` and `istft` function calls.

**Describe alternatives you've considered**
Manually apply `stft` -> `decompose.hpss`, -> `istft`, but that undermine the purpose of the convenience function `effects.hpss`.

**Comment by lostanlen** [comment]
Thanks @th0ger. Indeed this would be good to have in my opinion.

Implementing it is not obvious since we're already passing `**kwargs' to `decompose.hpss` inside `effects.hpss`. So that would require routing `decompose.hpss` arguments separately from those of STFT.

Arguments to `decompose.hpss`:
* `kernel_size=31`
* `power=2.0`
* `mask=False`
* `margin=1`

Arguments to STFT:
* `n_fft=2048`
* `hop_length=None`
* `win_length=None`
* `window='hann'`
* `center=True`
* `dtype=None`
* `pad_mode='constant'`
* `out=None`

**Comment by th0ger** [comment]
I have seen other python libraries in the same situation that solves this by defining an extra variable, say `kwargs_stft`, that is a dict of all kwargs for stft. You just pass this directly though   without hardcoding any parameter names of any of functions.

Of course you can also explicitly define each variable to pass through if you prefer that API style ;-)

**Comment by bmcfee** [comment]
> say `kwargs_stft`, that is a dict of all kwargs for stft. You just pass this directly though without hardcoding any parameter names of any of functions.

I'd prefer we avoid that if possible.  It's clunky to use, and makes things like type annotations, documentation, and tab completion a real pain.

Otherwise, I'm okay with extending the API in the effects module as proposed (except `out=`, which is probably nonsensical in this case).  My original intent with the effects module was to keep the API as simple as possible, as it's mainly convenience wrappers around other core functions, but at this point I think things are stable enough that it makes some sense to open up pass-through parameters to make it more flexible.

**Comment by th0ger** [comment]
Well, I hate kwargs as well for the reason of type annotation/code completion 😂 Just suggested it because you currently use kwargs.
Thanks for a great library!

**Comment by bmcfee** [comment]
Looking at this now, I think the simplest thing to do is just rip out the kwargs and make all parameters explicit.  This shouldn't break any existing user code, and it will make everything much more readable.

I don't anticipate the parameters to stft or hpss changing any time soon, but if they do, we'll need to remember to update in the effects module as well.
