### ISSUE TITLE
Actual use of DTW for syncing signals

### ISSUE THREAD

**Issue by nopium** [librosa/librosa#1810]
Having calculated the dtw warping path between x1 and x2 how do I actually use it for syncing x1 signal to x2 ? 

Should I time_stretch every sequence in path ? By what duration? I can't figure out the actual code.

**Comment by bmcfee** [comment]
This isn't something that librosa does directly, since the phase vocoder implementation only supports constant rate. (See related issues: #517, #1700)  I have in the past done this by slicing up the input into portions where the rate is stretched uniformly, and then mixing the results back together, but it's pretty cumbersome to do it this way.

You're likely better off using DTW to determine the alignment path, and then use a different package like https://github.com/KAIST-MACLab/PyTSMod or https://github.com/bmcfee/pyrubberband to implement the stretching.  Both of these support non-linear time warping and will do the job well.

**Comment by nopium** [comment]
Thanks for the reply! 
I do not mind slicing up the input. Do I understand correctly that path contains the indeces to slice by?

**Comment by bmcfee** [comment]
> What are the units in path? Are they indeces or milliseconds or smth else?

The units in `path` are frame indices.

> And how do I calc the rate of stretching for each slice?

It's rise-over-run, essentially.  For each segment in the input array (say, frame s to frame t), you'd have to work out how long that segment should be in the output (s' to t').  The rate would then be `(t'-t)/(s'-s)`.

The absolutely ancient code I have for this kind of thing is here: https://github.com/bmcfee/musichacks/blob/master/2013yyz/frankenmash/mangler.py - it's from 2013, so no guarantees that it will work at all by now (many API changes in the intervening decade), but it might give you an idea of how to think about it.

I really would recommend that you use pyrubberband or pytsmod though.  They have direct APIs for exactly what you want to do, and much better time-stretching algorithms as well.
