### ISSUE TITLE
`key_to_notes` with an option to return only the notes from the scale

### ISSUE THREAD

**Issue by marcevrard** [librosa/librosa#1828]
I was a bit surprised at first when I used `key_to_notes` as I expected the default behavior to return only the seven notes of the scale (with possibly the option for pentatonic scales). I reckon it would be more consistent with the `key_to_degrees` function.

```python
>>> librosa.key_to_notes("C:min")
['C', 'D', 'E♭', 'F', 'G', 'A♭', 'B♭']
```

Of course, it's possible to obtain the same result by resorting to an extra step with the `key_to_degrees` function:
```python
>>> key = "C:min"
>>> degs = librosa.key_to_degrees(key)
>>> np.array(librosa.key_to_notes(key))[degs].tolist()
['C', 'D', 'E♭', 'F', 'G', 'A♭', 'B♭']
```

**Comment by lostanlen** [comment]
Related: https://github.com/librosa/librosa/issues/1760 (now closed)

**Comment by bmcfee** [comment]
The documentation does explicitly say in the first line:

https://github.com/librosa/librosa/blob/8ba6d8d93276c2ee1439fb006d8869ef525b8c54/librosa/core/notation.py#L607-L609

Is there some way this could be made more clear?

The general idea in the API here is, as you've correctly identified, to separate the functionality of identifying the scale degrees belonging to a key (`key_to_degrees`) from the problem of spelling notes.  This makes it possible, for example, to spell notes outside of the key, which would not be possible if the function behaved as you initially expected.

**Comment by lostanlen** [comment]
@marcevrard note that this works out of the box in music21

```python
>>> from music21 import key
>>> key.Key('Cm').pitches
[<music21.pitch.Pitch C4>, <music21.pitch.Pitch D4>, <music21.pitch.Pitch E-4>, <music21.pitch.Pitch F4>, <music21.pitch.Pitch G4>, <music21.pitch.Pitch A-4>, <music21.pitch.Pitch B-4>, <music21.pitch.Pitch C5>]
```

https://web.mit.edu/music21/doc/usersGuide/usersGuide_15_key.html

**Comment by bmcfee** [comment]
I've been mulling this one over a bit, and considering the option of adding a shortcut to implement the degree slicing logic to return only the in-key notes.  Having thought about it though, I suspect it's asking for trouble.

Think the potential confusion here stems from the fact that `key_to_notes` is not just returning a set of strings - it is a mapping of pitch class index to note names, i.e. order matters.

This distinction gets muddled a bit when using C as the tonic (eg in @marcevrard's original post).  If we instead use a different tonic:

```python
In [2]: librosa.key_to_notes("G:min", natural=True)
Out[2]: ['C', 'D♭', 'D', 'E♭', 'E♮', 'F', 'G♭', 'G', 'A♭', 'A', 'B♭', 'B♮']
```
Note that the result still starts on C (pitch class 0).

If we slice out the degrees of interest,
```python
In [9]: degs = librosa.key_to_degrees("G:min")

In [10]: np.array(librosa.key_to_notes("G:min", natural=True))[degs]
Out[10]: array(['G', 'A', 'B♭', 'C', 'D', 'E♭', 'F'], dtype='<U2')
```
Note that it now starts on `G` because `degs == [ 7,  9, 10,  0,  2,  3,  5]` changes the order.

In plenty of applications, this is fine.  However, we've now subtly changed the definition of what's being returned beyond just taking out a subset: the result is not valid as a mapping of pitch-class to name.  (The fact that it *was* defined thusly before is what lets us get away with degree slicing in the first palce.)

This is a subtle point, but I think we should err on the side of keeping it simple and well-defined.

It may be worth expanding the documentation to more clearly state the intent of the function and add an example entry that shows how to slice degrees out for just the in-key notes.  Does that seem reasonable?

**Comment by bmcfee** [comment]
Taking the :+1: as endorsement to not expand functionality, but instead add documentation.  Putting it on the 0.11 docket.
