### ISSUE TITLE
norm argument in MFCC used in 2 different functions

### ISSUE THREAD

**Issue by ssslakter** [librosa/librosa#1842]
**Describe the bug**
I was trying to get consistent results from MFCC in torchaudio and librosa but found inconsistencies. These were related to the issue with normalization in Mel spectrograms discussed in this issue https://github.com/pytorch/audio/issues/1058. The solution was to use `'slaney'` norm in the `MelSpectrogram` method as explained in [this comment](https://github.com/pytorch/audio/issues/1058#issuecomment-778476093). However, if you try to pass the `norm` parameter for MFCC as a MelSpectrogram parameter in kwargs, it is also used as a `norm` parameter for `scipy.fftpack.dct`, which has different valid values.

**To Reproduce**
Use `norm='slaney'` in the MFCC function:
```python
librosa.feature.mfcc(
    y=y,
    sr=sr,
    n_mfcc=n_mfcc,
    n_fft=n_fft,
    hop_length=hop_len,
    win_length=win_len,
    pad_mode="reflect",
    n_mels=n_mels,
    htk=True,
    norm='slaney')
```
This will show an error.

**Expected behavior**
It should be possible to use MFCC with the 'slaney' norm for MelSpectrogram.

**Possible solution**
The simplest solution is to rename the norm for the DCT so that there are no name collisions in function arguments. 
You can see the proposed changes in my fork: https://github.com/ssslakter/librosa/commit/65d2e2bbabee2a0c9fe83baf0f3fb6daffaea380

**Comment by bmcfee** [comment]
Thanks for catching this!  I'm a little confused by the bug report though:



> It should be possible to use MFCC with the 'slaney' norm for MelSpectrogram.

This is the default behavior.  In fact, if you're calling MFCC, there's no direct way to use any Mel basis normalization *other than* slaney, since setting the `norm` parameter will pass to the DCT instead of the mel spectrogram.

The error that you're seeing is becuase DCT doesn't know what to do with "slaney" normalization.  Note that there is no ambiguity here in terms of code: `norm` in MFCC will always go to DCT, `norm` in melspectrogram will always go to the filter constructor.  The variable name collision is an unfortunate accident, but the behavior is well specified.


> The simplest solution is to rename the norm for the DCT so that there are no name collisions in function arguments.

We could also rename the mel basis normalization, but I agree that renaming the DCT norm parameter is probably an overall simpler change.

Meanwhile, you can work around this by building your MFCC in two steps:

```python
>>> S = librosa.feature.melspectrogram(..., norm=2)  # Or 'slaney' or whatever
>>> M = librosa.feature.mfcc(S=S, norm='ortho')  # Or whatever DCT norm you like
```

**Comment by ssslakter** [comment]
Thank you for the workaround!
I see, so `mfcc` is designed such that it's not supposed to have any other normalization than `slaney` for melspectrogram, right?
I'm new to the domain of sound processing, so I'm not sure if it's right to allow passing different `norm`s for the melspectrogram in the mfcc, but I think if we allow it, that would be consistent with the torchaudio.

Yeah, my formulations were not the best one😅, but my point was exactly about the name collisions!
Also, another possible solution would be to replace kwargs for the melspectrogram with a dictionary, like `melkwargs` argument in the torchaudio

**Comment by bmcfee** [comment]
> I see, so `mfcc` is designed such that it's not supposed to have any other normalization than `slaney` for melspectrogram, right?

Not exactly.  What happened is that we originally implemented `mfcc` to pass through all kwargs to `melspectrogram`, and norm could be supplied there.  We then later added the `norm` parameter to control DCT setting, having forgotten that it was also a valid kwarg to melspectrogram, and ... here we are. :sweat_smile: 

I believe torchaudio forked off of our implementation (perhaps not literally forking, but cloning API parts at least) before the DCT control was added, hence the discrepancy.



> Also, another possible solution would be to replace kwargs for the melspectrogram with a dictionary, like `melkwargs` argument in the torchaudio

I'd really like to avoid that kind of solution if possible.  It is commonly done in python packages, but it makes documentation and type annotation much messier than they otherwise would be.
