### ISSUE TITLE
logging.DEBUG causes stack trace in librosa.load

### ISSUE THREAD

**Issue by jhuus** [librosa/librosa#1852]
The following code (regardless of the audio path) triggers a stack trace in librosa. If you change DEBUG to INFO there is no stack trace. This is with librosa 0.10.2.

import logging
import librosa

logging.basicConfig(level=logging.DEBUG, format='%(asctime)s.%(msecs)03d %(message)s', datefmt='%H:%M:%S')
librosa.load("file.mp3")

**Comment by jhuus** [comment]
I see now that it's really just debug output being generated. There's an awful lot of output though, which makes it hard for me to use debug logging in my own code. Suggestions?

**Comment by jhuus** [comment]
And now I see that the following works:

                saved_log_level = logging.root.level
                logging.root.setLevel(logging.INFO)
                self.signal, _ = librosa.load(path)
                logging.root.setLevel(saved_log_level)

**Comment by bmcfee** [comment]
It sounds like you've landed on a solution that works for you here, so that's good!  I'm just chiming in to confirm that this is a little out of scope for us here. 

Warnings generated by librosa are, to the best of my knowledge, consistent with standard (or at least, idiomatic) scientific python usage.  Logging is handled through the standard python logging and warnings modules, which provide functionality for filtering or exposing warnings from different packages (and at different levels).

We did recently do an audit for warning stacklevel settings #1436, so stack traces should be hitting at the call site or entry point into the librosa package.  Sometimes this gets ambiguous (eg when decorators and jit compilation is involved), but for the most part, this should work as you expect.  If a specific warning is not tracing correctly here, please let us know.
