### ISSUE TITLE
Running without numba

### ISSUE THREAD

**Issue by ewen-lbh** [librosa/librosa#1854]
**Is your feature request related to a problem? Please describe.**
I'm currently part of a research team developing an android app through Kivy, that makes use of Librosa. To my knowledge, [it is not possible](https://github.com/kivy/python-for-android/issues/1865#:~:text=No%20support%20for%20numba) to use Numba on Android (I tried running the app with it anyways, but I get a missing library file error on import from llvmlite,  a numba core dep)

The functions we use from librosa are the following:

- `stft`
- `istft`
- `effects.time_stretch`
- `mel_to_stft`

**Describe the solution you'd like**
I looked a bit at the source code of Librosa, and it seems that, in most cases, you just put the `@jit` or `@guvectorize` decorator on functions. The ideal solution to me would be to gate the numba imports behind an optional dependency, and catch import errors to define stub decorators when librosa cannot be imported.

Managing to make llvmlite work on the android platform might be another solution, but requires considerably more work to me

**Describe alternatives you've considered**
We might look at an alternative to Librosa for Fourier transforms, but as the code has already been written and we're kinda nearing a deadline, forking numba and going for the solution I mentionned above seems like a wiser choice to me. We would of course do that work, I'm posting this issue to 

**Additional context**
Kivy: https://kivy.org
LLVMLite: https://github.com/numba/llvmlite
Termux seems to somehow support it, but bundling the package they install with Kivy might not be feasible: https://github.com/termux-user-repository/tur/issues/147#issuecomment-1310625296

**Comment by bmcfee** [comment]
Prior to version 0.6 (2018), we had numba as an optional dependency, with shim decorators exactly as you describe.  We ended up making it a hard dependency for a few reasons, but the main one at the time was that some upstream dependencies put numba in the dependency chain anyway.  That's no longer the case (since we made resampy optional in 0.9), but it did result in some simplified code paths and opportunities for acceleration that weren't possible before.  I don't think we're likely to revisit that decision.

However, I think you can probably work around this by using [mock](https://docs.python.org/3/library/unittest.mock.html) to create a fake numba module that provides stub decorators as you describe.  This will be easy to do for `numba.jit`, but much more difficult for `guvectorize` calls.  (GUVectorize is a bit more advanced than numpy's vectorize, so you'd need to do a bit of work to get a transparent replacement to work.) I don't think any of the functions you're relying on here would have a `guvectorize` in the call stack though, so maybe you can just try it with a mock `jit` and see if it works?

**Comment by ewen-lbh** [comment]
> I don't think any of the functions you're relying on here would have a guvectorize in the call stack though

yeah i started looking through the source code for this, I haven't finished checking everything. depending on how much work creating a fake module represents I might just test this solution without checking first. 

I also saw somewhere that disabling the numba jit can be done through an env var, but I don't know how to get that env var through the buildozer[^1] build (but it should be doable); and since llvmlite is probably a hard dep of numba it'll still cause the issue anyway.

[^1]: kivy's build system

**Comment by ewen-lbh** [comment]
As another alternative solution, were they breaking changes in any of the functions we rely on since 0.5.1 (I guess so, I mean 2017 is getting close to _10 years ago_ oh my god...).

Asking just in case haha

**Comment by bmcfee** [comment]
> depending on how much work creating a fake module represents I might just test this solution without checking first.

Mocking a module with a single function is a pretty quick job.  I expect chatgpt or copilot could whip this up quickly; here's chatgpt's version:

```python
from unittest.mock import MagicMock
import sys

# Create a mock numba module with a no-op jit decorator
sys.modules['numba'] = MagicMock()
sys.modules['numba'].jit = lambda x: x

# Now you can import librosa without needing numba installed
import librosa

# Test librosa functionality
y, sr = librosa.load(librosa.ex('trumpet'))
tempo, beats = librosa.beat.beat_track(y=y, sr=sr)

print(f"Estimated tempo: {tempo:.2f} BPM")
print(f"First 5 beat frames: {beats[:5]}")
```

This might need a bit of massaging, but it shouldn't be much more work.



> were they breaking changes in any of the functions we rely on since 0.5.1?

... so many.  It's all documented in the changelog though!

**Comment by ewen-lbh** [comment]
Oh nice, thanks a lot for the example, it looked like something more involved since numba is imported in our code through another module, I didn't know about `sys.modules`

We'll try to make this work, I'll update the issue accordingly. I (might) also create a buildozer recipe so that you can mention kivy support in your documentation

Thanks again ^^

**Comment by bmcfee** [comment]
I took the above code for a spin and it fails, but here's a revised version that does seem to work (tested with stft at least):

```python
from unittest.mock import MagicMock
import sys

# Create a mock numba module
sys.modules['numba'] = MagicMock()

# Define a no-op decorator that can accept arguments
def no_op_decorator(*args, **kwargs):
    if len(args) == 1 and callable(args[0]):
        return args[0]  # @jit without arguments
    else:
        def wrapper(func):
            return func  # @jit with arguments
        return wrapper

# Assign the no-op decorator to numba.jit
sys.modules['numba'].jit = no_op_decorator

# Now you can import librosa without needing numba installed
import librosa

# Test librosa functionality
y, sr = librosa.load(librosa.ex('trumpet'))
D = librosa.stft(y)
```
I think this should have you basically set for runtime.  If you're also managing a build system, you'll need to patch out the numba dependency in the package spec.

**Comment by bmcfee** [comment]
I don't think there's anything left to do on this, so I'll close it out.

**Comment by barracuda156** [comment]
@bmcfee @gwennlbh Could you say, what is the current status? I am also interested to have this working without `numba`.

**Comment by bmcfee** [comment]
@barracuda156 Nothing has changed here since the post last year: you can mock around numba using the code I gave above, and it will work pretty much everywhere except for functions relying on stencil ops (eg localmax, parabolic interpolation, zero crossings) and guvectorize (peak picking and beat tracking).  

There are other ops that rely on `numba.vectorize` that should in principle work with `numpy.vectorize`, so if you need those, you may need to make another shim decorator like the jit one above.
