### ISSUE TITLE
[Bug]: librosa.feature.rms is too slow

### ISSUE THREAD

**Issue by ozancaglayan** [librosa/librosa#1863]
### Bug summary

Hi. I was trying to do some silence removal and noticed that this function is for some reason super slow (maybe the numba parts of some functions, abs2, etc?) when a time-series signal is provided.

### Code for reproduction

```Python
def our_rms(signal):
    x = np.lib.stride_tricks.sliding_window_view(signal, window_shape=(2048,))[::512]
    return np.sqrt((x ** 2).mean(1))

%timeit our_rms(x)
29.7 ms ± 112 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit librosa.feature.rms(y=x, frame_length=2048, hop_length=512, center=False)[0]
1.21 s ± 3.15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

>>> np.allclose(
  our_rms(x),
  librosa.feature.rms(y=x, frame_length=2048, hop_length=512, center=False)[0],
  atol=1e-10,
)
True
```

### Actual outcome

Not specified

### Expected outcome

Not specified

### Operating system

Ubuntu

### software versions

Latest stable

### Installation

pip

**Comment by bmcfee** [comment]
I was able to get somewhat close with the following (`sr=22050`):
```python
In [26]: x = np.random.randn(420 * sr).astype(np.float32)

In [27]: %timeit our_rms(x)
30.9 ms ± 503 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [28]: %timeit librosa.feature.rms(y=x, frame_length=2048, hop_length=512, center=False)[0]
290 ms ± 3.01 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

The overhead here isn't quite as bad as you report, but that's likely due to platform differences.


> (maybe the numba parts of some functions, abs2, etc?)

This would only trigger if the input is complex dtype.  For real-typed inputs, it goes directly to `np.power(x, 2)` with a forced dtype, and no numba usage.

I think this is actually the source of the slowdown.  We didn't use `x**2` as this will promote dtype (float32->float64) when we may not want to, hence the use of `np.power`.  However, we could use `np.square` which is just as fast as `x**2` and allows dtype preservation:

```python
In [7]: sr = 22050

In [8]: x = np.random.randn(420 * sr).astype(np.float32)

In [9]: %timeit np.power(x, 2, dtype=x.dtype)
82.6 ms ± 2.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [10]: %timeit (x**2)
5.7 ms ± 84.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [12]: %timeit np.square(x, dtype=x.dtype)
5.72 ms ± 138 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

This would be a very easy fix if anyone wants to make a PR.

**Comment by bmcfee** [comment]
> this will promote dtype (float32->float64)

actually this isn't true in numpy.  But np.square is still a good call here because it makes dtype explicit and is just as fast.

**Comment by bmcfee** [comment]
Implemented the `np.square` patch (PR incoming), and it behaves as expected:

```python
In [4]: sr = 22050

In [5]: x = np.random.randn(420 * sr).astype(np.float32)

In [6]: %timeit our_rms(x)
30.2 ms ± 296 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [7]: %timeit librosa.feature.rms(y=x, frame_length=2048, hop_length=512, center=False)[0]
31 ms ± 272 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by ozancaglayan** [comment]
Thanks!
