### ISSUE TITLE
[question] What is the practical reason behind the win_length limitation being less than or equal to n_fft? 

### ISSUE THREAD

**Issue by benczejrobert** [librosa/librosa#1870]
Let's assume I have a long signal that I want to process into a mel_spectrogram or MFCC, but I don't want lots of FFT coefficients nor many time intervals. 

Let's assume for simplicity, a signal of length 100k, `n_fft`=2048 and I want an output mel_spectrogram of sizes (128,1) or MFCC coefficients of sizes (26,1) **without** losing/ignoring any of the input data.

What I can currently do is to set the hop_length to the size of the entire signal BUT that means losing at least 100k-2048 points from the input signal, which I don't want. I also don't want to set n_fft to equal the length of the signal.

What is the reason behind the `win_length` limitation being less than or equal to `n_fft`?

**Comment by dpwe** [comment]
The size of the FFT, n_fft, determines how many frequency samples it
generates (n_fft / 2 + 1), but it is also the number of input (time-domain)
samples it uses. We can’t put more than n_fft samples into the transform at
once.

We typically apply a window to the input samples. That can be shorter than
n_fft - we will simply pad it out to n_fft with zeros, that doesn’t damage
the FFT output. But we can’t make it longer - we have nowhere to send the
points outside the n_fft we keep.

What you want is to calculate multiple shorter FFTs to include every sample
from your longer signal, then average the FFT outputs to get a single,
short spectrum summarizing your whole signal.

If you average the FFT outputs, you generally want to take the magnitude of
the complex values first, otherwise the phases of each sub window will
interact destructively. (If you go all the way to mel spectrum for each
window, those values are already magnitudes, and fine for averaging.)

Commoy, you’d hop each sub window by window_len/2. The window is usually
pretty small at the edges; with a 50% hop, every sample gets to appear with
a reasonable magnitude in at least one FFT.

I hope this makes sense!

  DAn.
