### ISSUE TITLE
[Bug]: Constant conflicts between libraries

### ISSUE THREAD

**Issue by JohnnyStreet** [librosa/librosa#1877]
### Bug summary

Every library that uses librosa requires a specific version because you change so many things constantly that it has become unreasonable to introduce anything that even uses librosa into *my* projects. I sincerely wish you would consider separate modules for reworked features, and deprecation messages for old ones that won't completely break them. At this point I don't even have a specific issue to report because no matter what library I use, a different version of librosa will be installed, and the authors of those libraries all have horror stories about having to work around a specific version of librosa. Do people not bring this up constantly? What do you tell them?

### Code for reproduction

```Python
pip install <anything that uses librosa>
```

### Actual outcome

<package> installed successfully

### Expected outcome

dependency conflicts

### Operating system

Windows, Ubuntu

### software versions

*

### Installation

pip

**Comment by bmcfee** [comment]
> Every library that uses librosa requires a specific version because you change so many things constantly that it has become unreasonable to introduce anything that even uses librosa into _my_ projects. I sincerely wish you would consider separate modules for reworked features, and deprecation messages for old ones that won't completely break them.


I'm sorry, but I really don't understand what this means.  We have, for many years, provided extremely long runways for feature deprecations (typically 1-year) and only do a few point releases per year.  How does this constitute many things changing constantly?



> At this point I don't even have a specific issue to report because no matter what library I use, a different version of librosa will be installed, and the authors of those libraries all have horror stories about having to work around a specific version of librosa. 

The only reason I can think of for this to happen is if downstream dependencies pin to specific releases.  This happens unfortunately often, and it's almost never necessary.  However, downstream projects typically do this to ensure that their project works as expected without having to do their own forward maintenance when we do make changes.

This is really not something we can control though.  We adhere to best practices for specifying our own dependencies, but we can't control how other people specify *their* dependencies.

> Do people not bring this up constantly? What do you tell them?

You can search the github issues if you like, but no, people do not bring this up constantly.

**Comment by JohnnyStreet** [comment]
> The only reason I can think of for this to happen is if downstream dependencies pin to specific releases.

OF COURSE they do, because it's a miracle if you can find one version whose deps play nice with a reasonable collection of deps in a REAL-WORLD project, not something that is a demo to do one very specific task. Every time I am doing something large with multiple libraries involved, guess which library they are fighting over? I am only here because this is like the 5th time I have been c***blocked from having features that I *already had working* because something I really need is once again fighting with librosa. So you tell me, is it *everyone else's fault* that I have to keep modifying their libraries to work with yours? Or is it *my* fault for expecting it ti just work, like every other library I install from PyPI?

**Comment by bmcfee** [comment]
> So you tell me, is it _everyone else's fault_ that I have to keep modifying their libraries to work with yours?

They're not my libraries to maintain, so... yes?

Seriously, I believe your anger is sorely misplaced here.  If downstream users are unnecessarily pinning to old releases, what am I supposed to do about it?



> EDIT: Like just off the top, it is wild to me to bring up pinning when librosa is pinning new versions of _numpy_. That's like half of your userbase, right in the trash.

I mean this in all honesty: what are you talking about?  We have a few numpy releases that are known to cause compatibility issues, and we block those.  We have a lower version pin to ensure that all required functionality is present, but that's it:

https://github.com/librosa/librosa/blob/460c3352f55affe3409f817f57e0368c9a9af3c8/setup.cfg#L64-L66

**Comment by JohnnyStreet** [comment]
I happen to have been using 1.22 which is how I wound up here. But regardless of that, the number of times "AttributeError" appears in search results for a library is indicative of a more fundamental problem.

**Comment by bmcfee** [comment]
Look, if you want to report an actual problem, please do so. 

If you want to complain about other developers' sloppiness, i suggest you take it up with them. Maybe try being a bit more polite while you're at it.

**Comment by JohnnyStreet** [comment]
You attacking and namecalling other developers for your own breaking changes and calling inevitable criticism "impolite". I mean... Good luck.

**Comment by bmcfee** [comment]
> You attacking and namecalling other developers for your own breaking changes and calling inevitable criticism "impolite". I mean... Good luck.

I'm neither attacking nor namecalling.  Let's clarify what I perceive as the problem you're encountering.  (Not a trivial task since you've provided no actionable details, but I can imagine reasonably well.)

1. We release version A.B.C in, say 2019.  (This happens somewhat infrequently.)
2. Some other party builds a project Foo using release X.Y.Z in 2020. They pin their version spec to `librosa==A.B.C` (exact match).  Probably they didn't need an exact match, but they didn't want to have to maintain Foo into the future. Is this sloppy coding?  Yes, I think so - that's not name-calling, it's just descriptive of the product they've produced.  (This happens relatively often, especially with academic projects.)
3. We release version X.Y.Z in 2022.
4. Some other party releases project Bar in 2023, and now pins to version `librosa==X.Y.Z`.  Same deal as (2) above.
5. You come along in 2024 and want to use both Foo and Bar.  But you can't, because they have incompatible version specs.

What can we do to prevent this situation?  Not much.  We try to signpost upcoming changes as much as possible, and space releases out enough to give people time to adapt.  But if people ignore the signposts or don't maintain their code, I don't know what else can be done.

As I've alluded to earlier in this thread, most of the time when people use an exact pin, it's out of laziness (in the benevolent, Larry Wall sense of the word) or conservatism (you can expect it to work with exactly this version), but it's very rarely necessary.  If it worked on A.B.C, it should also work on A.B.D (with few but documented exceptions related to bug fixes).  So at the very least, a pin to A.B.* would be more appropriate, but we aim for backward compatibility whenever possible: >=A.B.C should do the trick almost always.  

You can look through the [release notes](https://librosa.org/doc/latest/changelog.html) for API changes and deprecations - they're generally confined to *.*.0, and breaking changes are almost always announced (through warnings) at least a year in advance.  To be succinct: you asserted that we constantly make breaking changes, but I don't believe this is true.

Is there something here that you think we should be doing differently?  I'll entertain suggestions, but to my knowledge this is the best we can do.

**Comment by JohnnyStreet** [comment]
You are heavily implying that if it was not for an arbitrary pinning of version requirements that the libraries would be compatible when that is simply not the case. You can write a whole novel about that strawman and you can change the title of my post, but it won't fix stuff like "No librosa.core attribute audio". or "no attribute output" or whatever the error is this week when I try to use just about anything that has librosa as a dep.

**Comment by bmcfee** [comment]
> You are heavily implying that if it was not for an arbitrary pinning of version requirements that the libraries would be compatible when that is simply not the case. You can write a whole novel about that strawman and you can change the title of my post, 


Well you provided zero details in your initial post, so I had to guess what you were talking about. Stats reports on pepy suggest that it isn't a strawman - we still have a disappointing amount of traffic for old version pins: https://www.pepy.tech/projects/librosa?versions=0.10.*&versions=0.9.*&versions=0.8.*&versions=0.7.*&versions=0.6.*

If my guess was incorrect, then let's talk about the problem you're actually having.  But that requires specifics, not vitriol. 

> but it won't fix stuff like "No librosa.core attribute audio". 

Hey, details!  We're finally getting somewhere!

I'm not familiar with the specific error that you're mentioning - do you mean https://github.com/qiuqiangkong/piano_transcription_inference/issues/16 ?  If so, I don't think that issue thread had enough context to debug properly - they didn't report anything about the installed environment -- but I don't believe it was actually a problem on our side.

We did have *some* problems with lazy-loader importing, but those were mostly due to external dependencies #1721 and have long since been resolved.  It may have been a bug upstream of us, e.g. in the lazy_loader package itself, but that's also not our problem to fix.

The closest I can find in our issues is #1546 , which we never got a definitive answer on, but my best guess is that it was due to a broken installation and nothing to do with us.  Original poster never confirmed or followed up, but nobody else had reported it, so I can only assume it's not a widespread issue.

(FWIW, the offending line of code from the issue linked above was `from librosa.core import audio`, and it works fine currently.)

> or "no attribute output" 

The output module was deprecated *five years ago* #917 and removed *four years ago* #1062.  Is that somehow not enough time for folks to catch up?  Was a one-year deprecation cycle not enough?  Should we maintain dead code forever?

> or whatever the error is this week when I try to use just about anything that has librosa as a dep.

I'm not even saying your anger and frustration is invalid, just that it's misdirected.

**Comment by bmcfee** [comment]
... just to follow up on this, having looked into the thread on the issue linked above. The proposed fix there was exactly the problem I described which you called a strawman: unnecessary exact version pinning.

**Comment by JohnnyStreet** [comment]
> Should we maintain dead code forever?

I don't know the right answer, but I do a lot of stuff with audio and every time I am trying to assemble something awesome it's like #%$^#% here we go again with librosa version mismatches. Maybe you should have called it librosa2. Maybe you should have deprecated functions instead of completely renaming/removing. At this point it's not going to be resolved. Tons of great projects that used 0.6 are already lost or relegated to containers, like bytedance's piano transcription library. librosa is a great project which is very tempting to use, but using it is like guaranteeing you will need to containerize later. I know it from how often I see the dependency resolver fighting over it. Again and again, with different new projects that I start, it's always that one name. librosa.

**Comment by bmcfee** [comment]
> I don't know the right answer, but I do a lot of stuff with audio and every time I am trying to assemble something awesome it's like #%$^#% here we go again with librosa version mismatches.

Sure, I get that.  My point though is that this is almost never necessary, and is in fact a result of sloppy version specs and unmaintained code.  If you want to build your awesome stuff on top of someone else's unmaintained package, you're going to run into problems.  That's not unique to us.


> Maybe you should have called it librosa2. Maybe you should have deprecated functions instead of completely renaming/removing.

That's what deprecation **is**: you give a warning that functionality is no longer maintained and will be removed, then you remove it.  Otherwise it lingers as dead code and people complain when it stops working.

> Tons of great projects that used 0.6 are already lost or relegated to containers, like bytedance's piano transcription library.

I rather doubt there's very much that they're using from 0.6 that wouldn't also work in 0.10, and they could put out a new release and properly maintain their version specs.  Bytedance — not to pick on them specifically, pick your favorite corporate player that builds on the backs of under-resourced open source development — could very easily put some effort into maintenance to benefit the greater community.


> I know it from how often I see the dependency resolver fighting over it. Again and again, with different new projects that I start, it's always that one name. librosa.

It still sounds to me like the problems you have are from other packages being under-maintained and not us.  This is the kind of thing that sucks the oxygen out of the room and makes open source development hard to sustain in the long run.

**Comment by JohnnyStreet** [comment]
The bottom line is I am growing tired with forking repos to fix things you could leave aliases for.

**Comment by JohnnyStreet** [comment]
Another example... I wanted to try https://github.com/qiuqiangkong/piano_transcription_inference and ran into the same stuff. I cloned the repo to fix it and it turns out all you changed was making arguments keywords instead of positional for no apparent reason other than you liked it better. And for that, the authors pinned a version and the rest is history. You can keep calling other people sloppy or blaming them for not maintaining their repos but that is such a dumb reason to have to go back.

**Comment by bmcfee** [comment]
> I cloned the repo to fix it and it turns out all you changed was making arguments keywords instead of positional for no apparent reason other than you liked it better.

You really don't need to assume the worst about people's intentions.  We discussed this planned change in #1114 - the entire point of that PR was to improve downstream code (i.e., detect and reduce bugs) by making parameter names explicit.  Folks had **almost two years** to comment on this before it was implemented and released.  This was not an arbitrary decision, but a specific response to seeing bugs crop up in user code due to implicit positional parameters being used incorrectly.

And, once again, we gave plenty of notice for people to update their code - the change was implemented (badly at first, but corrected within a week of release - I'll own that mistake) in the 0.9.x series (Feb 2022) with a deprecation warning cycle, and 0.10 was released removing the backwards compatibility support a year later (Feb 2023).  Again, this seems like plenty of time for maintainers to do some extremely minor cosmetic maintenance.


> You can keep calling other people sloppy or blaming them for not maintaining their repos but that is such a dumb reason to have to go back.

I agree it's a dumb reason to backward-pin.  They should have fixed the code instead, especially if other people are depending on it.  If they're not updating their code to remain usable as upstream dependencies evolve, which they always will, then yes: that is absolutely sloppy coding.  And please bear in mind that I am not calling *people* sloppy - I am calling specific instances of code sloppy.  There is a meaningful difference here.

At any rate, that all is multiple years in the past as well.

You know what would have been a much better use of your time than bickering with me on this issue thread?  Submitting a PR to fix the library that's actually causing you trouble - that way everyone benefits.  Instead we've just wasted a bunch of our own time to nobody's benefit. No actual problems have been raised that can be addressed from our side, and you're still stuck with broken dependencies from somebody else's code.

**Comment by JohnnyStreet** [comment]
I just hope 5 years from now I am not having conflicts between people using 0.10.0 and 0.15.0 over such trivial changes, and I hope this conversation influences the odds of that outcome. Regarding PRs, there were already multiple PRs to support the changes (which took seconds to implement) meaning that MANY people hit a brick wall with this issue and either compromised their requirements or had to jump through the same hoops to arrive at the same solution. I am speaking for everyone submitting ignored PRs to dead repos everywhere. Stop breaking legacy s*** for no reason. Thank you for your time.

**Comment by bmcfee** [comment]
> I just hope 5 years from now I am not having conflicts between people using 0.10.0 and 0.15.0 over such trivial changes, and I hope this conversation influences the odds of that outcome.

And I hope that in five years, you might gain some perspective and maturity, and understand how much of an entitled brat you've been sounding like in this entire thread.

This software is provided free of charge, is clearly identified as `alpha` state --- both in the package metadata and implicitly via the leading 0.x in the version number --- and we consistently provide plenty of runway for people to adapt to changes.

Higher level, we generally follow [intended effort versioning](https://jacobtomlinson.dev/effver/), though that term only came around recently and we've been working more or less in that mode for years.  We do have a roadmap for a [1.x release](https://github.com/librosa/librosa/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0), at which point the API will be stable and we'll be in a place to make more concrete promises about API.  But until then, 0.x is 0.x and you need to act accordingly.

We also have a longer term plan for 2.x #1743, and yes, API will break again at that point.  (Otherwise, we would still call it a 1.x release.)  That's not happening any time soon, but I'm mentioning it here in hopes that you understand that thought and care *does* go into these decisions.

> Regarding PRs, there were already multiple PRs to support the changes (which took seconds to implement) meaning that MANY people hit a brick wall with this issue and either compromised their requirements or had to jump through the same hoops to arrive at the same solution.

Conversely, the fact that there were multiple PRs (apparently not merged?) says to me that the maintainers were not doing their job, and that's where your criticism should be directed.


> I am speaking for everyone submitting ignored PRs to dead repos everywhere.

My dude, if you're going to build your "awesome stuff" on "free as in mattress" software, you have no right to complain at the people one layer back who *are* doing the work to maintain things.  Yes, sometimes APIs change - that's reality.  We do the best we can, but we can't promise that "dead code" will continue to work forever, **especially if they do not properly determine their version dependencies**.

**Comment by JohnnyStreet** [comment]
"It'S sTiLL aLpHa..." It is years old and tons of projects used it which I am sure regret that now. I have already removed most references to librosa in my own repo and have prioritized continuing that effort after this discussion. Take some accountability for the fact that I could throw together 20 demos from huggingface, some with way outdated code, and the only thing giving me trouble is librosa... Over trivial changes. You have not been following good practices. Maybe you are now, and that's great. But projecting your immaturity as a coder onto me because I don't talk like a pretentious linked-in jerkoff isn't addressing the issue.

**Comment by bmcfee** [comment]
You are unbelievably charming.

**Comment by bmcfee** [comment]
Note: OP @JohnnyStreet has been blocked for violation of code of conduct.
