### ISSUE TITLE
Do not import all modules on initial import (especially display)

### ISSUE THREAD

**Issue by nils-werner** [librosa/librosa#281]
This issue is very similar to #258:

Matplotlib 1.5.0 partially broke the Mac OSX backend in virtualenvs so running code that runs `import matplotlib` became non-trivial. Since librosa imports matplotlib in every case, using librosa on Mac OSX becomes non-trivial

[A small library that was merely using librosa for its WAV write/read capabilities](https://github.com/bmcfee/pyrubberband/blob/master/pyrubberband/pyrb.py#L18) basically broke down completely on Mac OSX because of this.

In my eyes two things should be learned from this:

 1. The small library should not depend on librosa but use a different, more isolated wav writing/reading lib. (not our concern here)
 2. Librosa should not import matplotlib even if I don't want to plot things.

The import structure should be changed and users should be trained to import all separate `librosa.*` parts they actually need.

**Comment by dpwe** [comment]
>
>    1. The small library should not depend on librosa but use a different,
>    more isolated wav writing/reading lib. (not our concern here)
>
> I had a similar situation and stripped out just the file reading code. See:

https://github.com/dpwe/audfprint/blob/master/audio_read.py

  DAn.

>

**Comment by bmcfee** [comment]
> The import structure should be changed and users should be trained to import all separate librosa.* parts they actually need.

As mentioned in #258 , I'm not a fan of piece-mealing libraries, but you do make a good point here about isolating (optional) dependencies.  (For the simple submodules with shared dependencies, I don't see the value in breaking the auto-import, since they tend to be interlinked anyway.)

I think making ``display`` optional makes sense, given its explicit dependency on an external library that doesn't occur elsewhere in the code.

For the other submodules, the case isn't so clear.  The biggest other non-core package that we hit is sklearn: in ``segment`` for clustering, ``decompose`` for nmf and decomposer-like modules, and ``util`` for the feature extractor.

(Aside: I wouldn't mind deprecating the feature extractor now that sklearn 0.17 has this functionality, but that's a separate issue.)

* Does it make sense to drop the auto-import on these modules as well?
* Or should we just leave it as is?
* Or refactor things so that all the sklearn dependencies are contained? 

I like the last option least, since it would either fragment the package like crazy, or result in unnatural function groupings.

At any rate, dropping automatic imports would break api, so I'll punt it to 0.5.0.  I'm sorry that this probably won't help your specific problem with mpl1.5.

**Comment by bmcfee** [comment]
#402 implements this for the display module.  The dependency chain for additional submodules is too complex, IMO, to worry about.
