### ISSUE TITLE
Adding piano roll visualization to display module

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#350]
1. It would be neat to be able to plot piano rolls in librosa. Preferably with F-measure displayed as well (preferably by going through @craffel's [mir_eval](https://github.com/craffel/mir_eval)). E.g. something like `librosa.display.piano_roll(path, show_fmeasure=True)`
2. I also think many users could be interested in being able to plot directly from a MIDI file, so I also propose adding utility conversion functions between [MIREX 2013 format](http://www.music-ir.org/mirex/wiki/2013:Discovery_of_Repeated_Themes_&_Sections) and MIDI. Yes, it's old but it's still around (at least in many of my datasets).
3. It would also be pretty cool to have a `librosa.display.onsets(onsets, spectrogram)` that overlays a piano roll on top of the spectrogram, for getting an intuitive feel of how well a melody extraction algorithm is performing for presentations and stuff, but that might be a little too exotic.
4. **Sidebar:** Shouldn't `specshow` and `waveplot` be called `spectrogram`and `waveform` respectively? I.e. call them what they actually display. That they display something is implicit due to being in the module `display` IMHO. Or do people actually top-level import like `from librosa.display import waveplot` etc.?

I could do a pr for 1. and 2. if this seems in line with librosa's ambitions. @bmcfee, thoughts?

**Comment by bmcfee** [comment]
> It would be neat to be able to plot piano rolls in librosa. Preferably with F-measure displayed as well (preferably by going through @craffel's mir_eval). E.g. something like librosa.display.piano_roll(path, show_fmeasure=True)

I'm not sure what you mean exactly by "plot piano rolls".  Can you provide an example?  What's wrong with rendering the piano roll as a matrix and calling specshow with `y_axis='cqt_note'`?  (Or do you mean drawing a literal piano keyboard along the y-axis, which would be cool.)

Otherwise, I'd prefer to not add mir_eval as a dependency, since librosa and mir_eval are really solving two orthogonal problems (analysis and eval).



> I also think many users could be interested in being able to plot directly from a MIDI file,

I think MIDI should stay outside of librosa's scope.  However, the points you're raising might be more relevant over in [JAMS](https://github.com/marl/jams/pull/110).



> It would also be pretty cool to have a librosa.display.onsets(onsets, spectrogram) that overlays a piano roll on top of the spectrogram,

Again, I'm not sure exactly what you mean here.  I think of onsets as timing of note events (not pitch), which would be best done via matplotlib ops like `plt.axvline`.  If you also have pitch information, `plt.scatter` seems appropriate.  In any event, it's in keeping with matplotlib's style to separate the spectrogram visualization from other overlays.



> Sidebar: Shouldn't specshow and waveplot be called spectrogram and waveform respectively?

I try to name functions for what they do, not what their inputs are.  I would expect a function called "spectrogram" to compute a spectrogram, not draw one.

**Comment by bmcfee** [comment]
Does [this PR](https://github.com/craffel/mir_eval/pull/196#issuecomment-222843263) resolve this issue?

**Comment by carlthome** [comment]
Yes, very much so. Neat stuff. :+1:
