### ISSUE TITLE
Trim and split

### ISSUE THREAD

**Issue by carlthome** [librosa/librosa#360]
Would it make sense to add a way of trimming silence when loading audio? Currently I'm doing this silliness, which works alright aside from being performance intensive, but the onset detector surely isn't built for detecting offsets like this, I'd assume.

``` Python
path = ... # Path to an audio file with a bunch of leading and trailing silence.
y, sr = librosa.load(path, sr=None)
onsets = librosa.frames_to_time(librosa.onset.onset_detect(y, sr), sr)
offsets = librosa.frames_to_time(librosa.onset.onset_detect(y[::-1], sr), sr)  # Suboptimal!
leading_silence = onsets[0]
trailing_silence = offsets[0]
total_duration = librosa.get_duration(y, sr)
y, _ = librosa.load(path, sr, offset=leading_silence, duration=total_duration-leading_silence-trailing_silence)
```

Also, perhaps if loading with a set duration longer than the actual file, then there should be the option of padding the sequence to the set length, or at least provide a user warning that less than `duration` was loaded.

**Comment by bmcfee** [comment]
Probably a better way to do this is to call `librosa.feature.rmse`, threshold the result, and retain the first and last non-zero indices.

I don't think we should add this to `load`, which is already a little too complicated IMO.  However, it might be handy to include a `trim` function which simplifies this process.  Anyone else have thoughts?

**Comment by carlthome** [comment]
A `trim` function would be very handy. :+1:

**Comment by dpwe** [comment]
We could have trim accept a dB threshold input, and a flag to choose
between interpreting that relative to the largest energy in the file, or
full-scale.  Maybe default to 60 dB below full-scale (rms sample value < 32
in 16 bit ints).  It accepts n_fft (in lieu of window_length) and
hop_length like the underlying rmse.

(I just noticed that rmse uses spectrogram under the hood.  That's quite
extravagant compared to simply summing squared sample values.)

  DAn.

**Comment by carlthome** [comment]
It would also be useful to have an argument for `trim` that trims _in between_ peaks as well. Trivial extension, and useful in a few machine learning applications when data is abundant, e.g. a signature like this `trim(threshold, mode='beginning'|'end'|'both'|'all')`

**Comment by bmcfee** [comment]
> We could have trim accept a dB threshold input, and a flag to choose
> between interpreting that relative to the largest energy in the file, or
> full-scale.  Maybe default to 60 dB below full-scale (rms sample value < 32
> in 16 bit ints).  It accepts n_fft (in lieu of window_length) and
> hop_length like the underlying rmse.

Yup; I imagine this having a similar signature to `logamplitude`.



> I just noticed that rmse uses spectrogram under the hood.  That's quite
> extravagant compared to simply summing squared sample values.

In general, yes.  I did it this way because you often have the stft kicking around anyway, in which case it will be cheaper to use it than to start over with direct summation.  This is because, for timing consistency with other feature functions, we would want padding and centering of the signal, which dominates the cost of doing it directly.  When the cache is enabled, this comes basically for free.




> It would also be useful to have an argument for trim that removes frames in between peaks as well.

I'm not so sure about this.  I think a more general utility would be a `split` function that separates a signal into an array of signals based on detected silence (using the same logic as `trim`).  Better yet, simply return a list of time/frame intervals corresponding to non-silent regions.  That way, you can slice and conjoin signals directly with `effects.remix` or concatenate them by `np.concatenate`.

**Comment by carlthome** [comment]
On a similar note (https://github.com/librosa/librosa/issues/373) I think it would be neat to also have a padding built into `load()` when `duration` and `offset` exceed the audio file's duration. Perhaps together with a warning in the weirder case when offset is larger than the duration.
