### ISSUE TITLE
Add scatterpoints on a specshow

### ISSUE THREAD

**Issue by Toekan** [librosa/librosa#364]
Hi all,

I'm trying to add markers on a librosa.display.specshow(S) image (to mark peaks in the spectrogram), but plt.scatter(x,y) does not seem to collaborate with the log axis of specshow at all. The log scale of the y-axis doesn't seem to work in a straight forward way? Any easier way of adding markers on the spectrogram? 

I'm quite new to python in general (and github in fact), so sorry if this question has an easy answer somewhere, I didn't find it!

Thanks,
Toekan

**Comment by bmcfee** [comment]
Hi Toekan,

This is a good question.  The problem here is that matplotlib doesn't make it easy to draw an image on logarithmically scaled axes, so we instead warp the image to fit on a linear scale.  A consequence of this is that the axes still look linear to all other operations, so plotting on top of a log-axis image can get weird.

It's possible to work around this by pulling out some of the axis warping logic from the display module.  [This gist](https://gist.github.com/bmcfee/8884c9256e0a9d4dfbacfb13c2cce4c2) demonstrates how to do it; the relevant portion being the last cell.

All you need to do is say 
```python
y_map, y_inv_map = librosa.display.__log_scale(S.shape[0])
```
(assuming that you're log-scaling the vertical axis).  A point at position `i` will then be mapped to `y_map[i]`, so you would then replace `plt.scatter(x, y)` by `plt.scatter(x, y_map[y])`.

The above will work for integer positions.  If you need non-integer positions, I'd recommend fitting an interpolator to `y_map` and using that to re-position your vertical points.  The notebook I posted shows how to do this in the last two cells, but it would basically look like:
```python
y_interp_map = scipy.interpolate.interp1d(np.arange(S.shape[0]), y_map) 
plt.scatter(x, y_interp_map(y))
```

I hope this helps!  Sorry that it's so much more complicated than it probably should be.

**Comment by Toekan** [comment]
Works like a charm! Thanks a lot for the in depth answer :)

**Comment by bmcfee** [comment]
Great, I'll close this one out then.

Note that the next release (0.5) will break this workaround, but makes things much easier overall.  Pr #365  makes specshow plot in natural coordinates (seconds or hz) regardless of the axis scale, so you won't need to explicitly remap data for plotting.
