### ISSUE TITLE
incorrect normalization in write_wav for int types

### ISSUE THREAD

**Issue by woodshop** [librosa/librosa#415]
The `write_wav` function has normalization turned on by default. However normalization does not check the `dtype` of the input and by default normalizes audio to `[-1, 1]`. The normalized range should match the the range of the data type, e.g. `[-32768, +32767]` for `int16`. The current behavior causes `scipy` to write silent audio when the `dtype` is not `float`.

**Comment by bmcfee** [comment]
Good catch.  I guess the implicit assumption in `normalize` is that data is float-typed.

I don't think this should be fixed by changing `util.normalize` -- it does what it's supposed to do.  The incorrect part here is that `write_wav` assumes normalizing to +-1 is correct.

I guess this could be fixed by adding a separate integer-typed normalization function, or just hacking it directly into `write_wav`, but is that the best way?  Casting to float and falling back to `normalize` would be inefficient here.

At this point, given all the [IO issues](https://github.com/librosa/librosa/issues?q=is%3Aopen+is%3Aissue+label%3AIO), I'm getting tempted to deprecate IO functionality and tell people to use pysoundfile instead.

**Comment by woodshop** [comment]
Hey Brian,

I support either:
- deprecation of `write_wav`
- change the `wite_wav` default parameter to `normalize=False` and improve documentation

I see marginal utility to having  having audio output in Librosa if only one file format will be supported. I also think that keeping normalization turned on by default and adding integer-type normalization may lead to some confusion since there will be conflicting implicit definitions of normalization. (Does 'normalization' mean scaling   to `[-1, 1]` or does it mean scaling to the range of the type?)

--Andy

**Comment by bmcfee** [comment]
> I support either:
> 
> deprecation of write_wav
> change the wite_wav default parameter to normalize=False and improve documentation

How about both? :grin:

I'm thinking: 

- drop normalization as default
- add an extra line that only normalizes if `np.issubdtype(y.dtype, np.float)`
- deprecate write_wav in 0.5, remove in 0.6

> I see marginal utility to having having audio output in Librosa if only one file format will be supported.

This isn't so much about file format as assumptions about how audio is represented in memory.
The implicit assumption throughout librosa is that audio data is always floating point, so as to minimize the gap between theory and application.  Integer encodings should never be produced by librosa's processing, so it's not too surprising that this issue hadn't come up until now.

More generally, as I've stated elsewhere, I think we shouldn't be in the codec business at all, but that's getting a little off-topic.
