### ISSUE TITLE
DCT type question

### ISSUE THREAD

**Issue by georgid** [librosa/librosa#437]
Why did you bother to implement the DCT, and not use the scipy's [DCT](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.fftpack.dct.html)  
As far as I see it is used only in the MFCC. Could the reason be that for MFCC a particular detail is not  in scikits implementation?

Also I am wondering, why do you use DCT type III by default and not have the option of DCT type II? DCT type III is used by htk, MFCC,  whereas DCT type II is used in Slaney's MFCC.

**Comment by bmcfee** [comment]
> Why did you bother to implement the DCT, and not use the scipy's DCT

This was inherited from the matlab implementation we were basing the original implementation on.  For backwards compatibility, it was simpler to translate the code directly.

> Also I am wondering, why do you use DCT type III by default and not have the option of DCT type II? DCT type III is used by htk, MFCC, whereas DCT type II is used in Slaney's MFCC.


Sounds like a good idea.  Pull requests are always welcome!

**Comment by bmcfee** [comment]
Circling back on this one: librosa's dct does not match scipy's. For reference: librosa's dct was based on this implementation: https://labrosa.ee.columbia.edu/matlab/rastamat/spec2cep.m in type-3 mode, and these two implementations do match (down to around 6 decimal places).

scipy's dct behaves differently, but it doesn't expose an interface to the basis, so it's not trivial to work out exactly how it's different.

It would be fairly easy to add functionality in `mfcc` to call out to `scipy.fftpack.dct(...)` with pass-through parameters, instead of using the existing one, but making this the default would be a breaking change.  It still seems like a reasonable feature to add though.

**Comment by bmcfee** [comment]
After digging into this a bit more over on #682 -- it seems like the documentation is actually incorrect.  Librosa's dct basis matches scipy to numerical tolerance as type-II with `norm='ortho'`, not type-III as advertised.  I'll clarify this in the PR.

**Comment by georgid** [comment]
Good to know, thank you!
