### ISSUE TITLE
Harmonics basecase

### ISSUE THREAD

**Issue by rabitt** [librosa/librosa#442]
As far as I understand, the harmonic number `1` in `librosa.harmonics` should be the "identity". (i.e. when calling `x_harm = librosa.harmonics(x, freqs, [1])`, `x_harm[0]` should exactly equal `x`)

I tried out a simple example in this [gist](https://gist.github.com/rabitt/ad974d05096971e440d6b92a1cea026a) and it looks like this isn't the case. Any ideas why?

**Comment by bmcfee** [comment]
Looking at that gist, the error is down in the 1e-6 range.  I would chalk this up to rounding error in the  frequency positions of the interpolator.

Technically, any interpolator should pass exactly through the samples, but we should expect some slop if the sample positions require high precision to represent.

Do you get the same thing if you replace `freqs = np.arange(len(S))` so that the positions are integer-valued?  This would eliminate positional rounding as a source of error.

You could also try with `kind='quadratic'` to get a higher precision estimate.

**Comment by rabitt** [comment]
`kind='linear'` and `freqs = np.arange(len(S))` has identical results with the gist I linked to before, which is weird.

However, `kind='quadratic'` and  `freqs = np.arange(len(S))` (or leaving `freqs` as before) gives `S == S_harm[0]`.

**Comment by bmcfee** [comment]
Okay, that seems reasonable to me.  I think there's nothing to be done on librosa's end here.  If it really bothers you, maybe strip it down to a minimal example of `interp1d` and take it up with the scipy folks.

**Comment by bmcfee** [comment]
Also, instead of checking for strict equivalence, I'd check `np.allclose(S_harm[0], S)`.  The raw difference is in the 1e-6 range, but the input amplitudes appear to scale up to 80, so the relative error is in the 1e-8 range.  (I consider that to be acceptable error.)

**Comment by rabitt** [comment]
👍
