### ISSUE TITLE
Warn when filterbanks are empty [was: Vanishing mel filters]

### ISSUE THREAD

**Issue by justinsalamon** [librosa/librosa#478]
Using a combination of a low n_fft, high n_mels, and low fmax, one can obtain a mel spectrogram where some of the bins are always 0. I haven't examined the source code but my guess would be that this combination of parameters results in a mel filterbank that has some filters with a width of 0 (in fft bins).

Here's an example: https://gist.github.com/justinsalamon/c266b7f6d60140bf1ead8ea0593dc8d2

Now sure whether there's a nice numerical solution to this problem (?), but perhaps a warning should be raised when this occurs?

**Comment by justinsalamon** [comment]
A possible solution (from a user perspective) would be to zero pad each frame so that n_fft can be high even if the user desires a small window. But it seems like `librosa.melspectrogram` doesn't support the `win_length` argument? 

So right now this is doable by first computing the `librosa.stft` (which does support different `n_fft` and `window_length` values) and feeding `np.abs(stft)**2` into `librosa.melspectroggram` via the `S` parameter.

**Comment by bmcfee** [comment]
> But it seems like librosa.melspectrogram doesn't support the win_length argument?

That's right.  In general, feature functions expose only the most necessary or commonly modified parameters of underlying representations.  This sort of thing is exactly why there's support for pre-computed spectra (along with efficiency savings).



> Now sure whether there's a nice numerical solution to this problem (?), but perhaps a warning should be raised when this occurs?

I'm not sure there is either.  On the one hand, we can't really expect to capture such low frequencies with that short of a window, but failing silently seems bad.  A sanity check for non-zero filter energy seems like a reasonable feature though.

This may be relevant to #18 and @lostanlen's interests.

> Using a combination of a low n_fft, high n_mels, and low fmax, one can obtain a mel spectrogram where some of the bins are always 0.

FWIW, I only see this when calling with `htk=True`.  Using Slaney's mel frequencies, only the bottom channel gets zeroed out.  I suspect you can probably push the parameters around to make Slaney's fail as well, but it'll be harder since it's actually linear in the problematic band.

**Comment by justinsalamon** [comment]
> That's right. In general, feature functions expose only the most necessary or commonly modified parameters of underlying representations.

Would it be bad to expose `win_length`, though? It's the only way to enforce zero-padding.

> I'm not sure there is either. On the one hand, we can't really expect to capture such low frequencies with that short of a window, but failing silently seems bad. A sanity check for non-zero filter energy seems like a reasonable feature though.

👍 

> FWIW, I only see this when calling with htk=True. Using Slaney's mel frequencies, only the bottom channel gets zeroed out. I suspect you can probably push the parameters around to make Slaney's fail as well, but it'll be harder since it's actually linear in the problematic band.

But you need `htk=True` if you plan to use the mel spectrogram as input to a CNN. I wonder how many people are training CNN's on librosa melspectrograms without htk=True...

**Comment by bmcfee** [comment]
> Would it be bad to expose win_length, though? It's the only way to enforce zero-padding.

I'd rather not.  It's a slippery slope from there to exposing all stft parameters, and if we do it in mel it should be everywhere.



> But you need htk=True if you plan to use the mel spectrogram as input to a CNN. I wonder how many people are training CNN's on librosa melspectrograms without htk=True...

I suspect most people use it that way, and that it probably doesn't matter as much as we think it does.

At the risk of derailing this thread: I'm not sure HTK mel is entirely appropriate for 2D-cnns either.  It's logarithmic (actually log1p, so the low end is more like linear) but the spacing between octave frequencies is not at all constant:
```python
In [23]: np.diff(librosa.hz_to_mel([55, 110, 220, 440], htk=True))
Out[23]: array([  79.24628451,  143.51078797,  241.63867726])
```
so a filter of height `n` will cover different fractions of the octave depending on its vertical position.  OTOH, folks use 2dconv on linear spectra, yolo :suspect:

**Comment by bmcfee** [comment]
I took a stab at implementing an empty-bin warning in the basis construction, but it's not obvious how to go about such a check in general.  The obvious thing is to look for rows of the filter bank with norm `< tiny`, but sometimes that's actually the expected behavior.

Maybe it just has to be special-cased to Mel, and verify that each basis spans at least one FFT bin?  I'm okay with doing this at least as a stop-gap until #18 happens and we can revisit the problem in generality.  @justinsalamon @lostanlen, thoughts?

**Comment by justinsalamon** [comment]
> Maybe it just has to be special-cased to Mel, and verify that each basis spans at least one FFT bin? I'm okay with doing this at least as a stop-gap until #18 happens and we can revisit the problem in generality. @justinsalamon @lostanlen, thoughts?

👍
