### ISSUE TITLE
Clarification in the installation documentation

### ISSUE THREAD

**Issue by kmkinnaird** [librosa/librosa#503]
The additional notes for MacOS X could lead one to believe that you don't *need* ffmpeg. I discovered that one does need it because while waiting it to install, I tried the quickstart example. It clearly failed, but it took a bit of googling to figure out why. 

It would be awesome to clarify that you do need at least one of the audio decoder backends that audiroead depends upon.

**Comment by bmcfee** [comment]
@stefan-balke Can you take care of this one?

**Comment by stefan-balke** [comment]
@bmcfee ffmpeg is now available on conda https://github.com/conda-forge/ffmpeg-feedstock

Will you integrate it in the recipe then I'll update the README.md while I'm at it.

**Comment by stefan-balke** [comment]
Discussion can now take place in #504

**Comment by bmcfee** [comment]
@stefan-balke thanks!  As I recall, ffmpeg was already in conda, but I couldn't add it as a dependency in the librosa feedstock because it wasn't supported on win*, at least, not at the time.

I see no problem in adding instructions for manual conda install of ffmpeg right now though.  (I don't want to go mucking about with the feedstock until the 0.5 release is ready.)

**Comment by stefan-balke** [comment]
I'll try the windows build and let you know. Maybe this could then go together with the 0.5.

**Comment by bmcfee** [comment]
For completeness: the `ffmpeg [not win]` issue cropped up on the audioread feedstock, not librosa's.

https://github.com/conda-forge/audioread-feedstock/blob/master/recipe/meta.yaml#L24

**Comment by bmcfee** [comment]
Implemented in #504
