### ISSUE TITLE
Default sample rate for librosa.core.load is not the native sample rate

### ISSUE THREAD

**Issue by mcartwright** [librosa/librosa#509]
Currently, the default sample rate is 22050 Hz when loading an audio file. In order to use the native sample rate, `sr` must be set to `None`. I often forget to set this to `None` when I want the native sample rate, and I have noticed many students do the same. 

Have others experienced confusion over this? 
Should this change in a later release so that the native sample rate is the default?

**Comment by bmcfee** [comment]
As an aside: we've sometimes discussed wholly doing away with I/O and codec functionality in librosa, and encouraging people to use pysoundfile instead of `librosa.load`.  (Or, audioread if folks really want mp3 support.)

If, at some point, we do deprecate `librosa.load`, this issue would resolve itself.

**Comment by mcartwright** [comment]
I think this could be a good solution as I have had other issues with students when writing sound files (e.g. by default librosa uses the dtype of the array for the output, but a lot of audio players don't support float32 encodings, etc.).

**Comment by bmcfee** [comment]
An alternate solution is to use [presets](https://presets.readthedocs.io/en/latest/) to change the default parameters to load.  I wouldn't recommend this for teaching purposes, but it is sometimes useful when you have a fixed environment and don't want to copy parameters everywhere.

**Comment by mcartwright** [comment]
Yeah, agreed. That's a decent solution for someone like me who is simply forgetful, but not a great solution for teaching. 

Also, it helps for the input side, but not the output, which also has its issues as mentioned above.

**Comment by keunwoochoi** [comment]
Agree that the default should be `None`, seems like that's how people expect it would work when they don't specify `sr`. (people: {me, my friend 1, my friend 2})

**Comment by bmcfee** [comment]
Maybe it's time to start thinking about big changes for a 1.0.0 release...

**Comment by carlthome** [comment]
I too think it would be nice of `sr=None` was the default.

**Comment by dpwe** [comment]
I've had this feeling to, but there are further consequences: librosa uses
a default window length for stft etc in samples, not seconds. This is fine
if the sample rate is essentially always 22050, but is much less pleasant
if you're trying to be sample rate agnostic.

My preference would be for native sample rate by default, and window sizes
etc defined in seconds. But *that* gets ugly because you want 2^R fft
sizes, and it's not trivial to enforce that transparently.

The 22kHz-by-default is quite a neat work around in practice.

  DAn.

**Comment by bmcfee** [comment]
+:100: for @dpwe's comment -- I hadn't considered the implications for the rest of the API when we don't have a consistent expectation of the sampling rate.

I'm not too keen on going to seconds for everything, for exactly the reason mentioned above.  (It would have been really nice if the standard had been set to 32768 or 65536, and not some anthropocentric garbage like 44100, alas...)

Side note: I wonder if 90% of complaints would drop off if we switched the default sampling rate to 44100?

**Comment by keunwoochoi** [comment]
But in which context does it need to be sample rate agnostic? Can't we expect whoever using STFT/etc to know the sampling rate explicitly? For me it seems very natural that sr would be native when I don't set anything while I wouldn't expect any certain value would work well for STFT parameters. For example, does `n_fft=2048` (the current default of STFT) with `sr=22050` have some special meaning?

Site note: I think so. 90% seems a lot though.

**Comment by carlthome** [comment]
How about making `librosa.load`'s sample rate argument positional instead? Then users that want the native sample rate would still have to pass `sr=None` just like today, but no one would accidentally forget to set sample rate and get a resampled return without remembering to check the return value properly.

I get that it's nice to have sensible defaults as much as possible everywhere, but this really feels like a case where requiring arguments would be much cleaner.

On a similar note I'd also argue that the `librosa.load` could return just a ndarray if `sr` is set to anything other than `None`. NumPy and SciPy does it like that a lot.

**Comment by keunwoochoi** [comment]
> On a similar note

That sounds like quite a big change! It may be redundant to get `sr` returned, but I'd up for consistent behaviour whether `sr` is `None` or not.

**Comment by carlthome** [comment]
Yes, it would break pretty much everything.

**Comment by bmcfee** [comment]
> On a similar note I'd also argue that librosa.load could return just a ndarray (not a tuple) if sr is set to anything other than None. NumPy and SciPy does it like that a lot.

Functions that return different types based on input are generally bad news, and I'd prefer to avoid them.

**Comment by carlthome** [comment]
> Functions that return different types based on input are generally bad news, and I'd prefer to avoid them.

Multiple dispatch is only reasonable with typing, I agree, but I would have expected this API:

```python
samples = librosa.load('audio.wav', 44100)

samples, sample_rate = librosa.load('audio.wav')
```

Anyway, how about making `load`'s sample rate positional in 6.0?

**Comment by carlthome** [comment]
Also, I guess there's nothing stopping one from doing this if they wanted to:

```python
def load(path, sr=None, **kwargs):
    r = librosa.load(path, sr, **kwargs)
    return r if sr is None else r[0]
```

**Comment by bmcfee** [comment]
Had a quick chat with @mcartwright and @lostanlen this morning.  I think a reasonable compromise can be struck by doing a deprecation move of `librosa.load -> librosa.rload` (resample-load), and providing a wrapper `librosa.load(...) = librosa.rload(..., sr=None)`.

This way, there's a simple loader that acts as people might expect, and it's a minimal change to recover the current / past behavior and things are more explicit.

I have two major concerns with this though:

1. It'll break things down the road for people that don't update their code to use the new loader,
2. I expect a *lot* of newbie errors resulting from naive use of `load` instead of `rload`, and expecting all the downstream analysis to work at whatever the native sampling rate happens to be.

Maybe it would be better to preserve the current load interface, and provide a second `loadn` that loads at the native sampling rate.

What do folks think?

**Comment by carlthome** [comment]
Hmm, both proposals seem very messy. I'm with @dpwe now too. :stuck_out_tongue_winking_eye: 

Anyway, for me personally, the actual reason why I prefer native is because resampling takes a lot of time. For mono I'd prefer to use 22050 Hz actually, if only the resampling wasn't a bottleneck in my particular pipelines.

**Comment by eduamf** [comment]
I have the same problem. I agree with [bmcfee](https://github.com/bmcfee): to do a deprecation move of `librosa.load -> librosa.rload` (resample-load), and providing a wrapper `librosa.load(...) = librosa.rload(..., sr=None)`

**Comment by lostanlen** [comment]
-1 to `loadn`

`loadn` strikes me as akin to idioms like `kill -9`, where you have to append something to the command so that it ends up doing what it name implies.

**Comment by lostanlen** [comment]
I should add that `rload` is not satisfying either, because, as of now, `librosa.load` does three things:
1. loading
2. converting to mono
3. resampling
(maybe not in that order)

So writing `rload` would expose us to the inevitable issue: "default number of channels in `librosa.rload` is not the native number of channels", leading to the suggestion of inventing `rloadm` for "rload mono", and we'd roll downhill from there into matlabish babble (`etfe` anyone?)

Therefore, the only two viable ways forward are:
(i) status quo,
(ii) deprecating keywords `sr` and `mono`, and removing them in a future version.

The problem of this PR is that the principle of least surprise is IMHO equally balanced between options (i) and (ii).

**Comment by carlthome** [comment]
Both unfortunate and convenient that `librosa.load` does these three things when there are top-level functions for the separate steps (`librosa.to_mono` and `librosa.resample`). Too late to deprecate both `sr` and `mono` args to `load`? It's not 1.0 yet after all. 😉 

```py
y, sr = librosa.load('audio.ogg', sr=44100, to_mono=True)
```
vs.
```py
y, sr = librosa.load('audio.ogg')
y = librosa.resample(y, sr, 44100)
y = librosa.to_mono(y)
```
I'd guess a lot of user code would break (in subtle and catastrophic ways) if `y` is suddenly 2D. 😭

**Comment by bmcfee** [comment]
> Too late to deprecate both sr and mono args to load? It's not 1.0 yet after all.

If anything, I would freeze these in place for a 1.0 but consider dropping for 2.0.


> I'd guess a lot of user code would break (in subtle and catastrophic ways) if y is suddenly 2D.

Yep, especially since we don't meaningfully support multi-channel outside a few limited cases.

I think for now it's best to maintain the status quo.  While a default resample on load might be surprising to some, I suspect that we would have had a lot more usability complaints had we gone the other way.

**Comment by justinsalamon** [comment]
Related: we recently had some team members get bitten by forgetting to set `sr` when calling `melspectrogram` (which also has optional `sr=22050`). 

It's an easy mistake to make since (1) stft doesn't take `sr` so it's easy to forget to add it when switching from linear to mel and (2) it only affects the construction of the mel filterbank, but will still return an output with the expected dimensionality (mel bands and frames) so is easy to miss.

Instead of having a consistent expectation for the sampling rate, what if librosa always required `sr` as a positional argument in all functions where it is used? It would break everything in terms of backwards compatibility, but isn't that what major versions are for? :) More importantly, it would prevent bugs resulting from expected `sr` values by ensuring the user is always explicit about the `sr`.

Just thought I'd throw this in here since it seemed related.

**Comment by bmcfee** [comment]
> Instead of having a consistent expectation for the sampling rate, what if librosa always required sr as a positional argument in all functions where it is used?

I don't think we can do this, and still have a consistent interface that supports `S || (y, sr)`-style overloading.  I don't think it makes sense to have `sr` always be required, e.g., it's not used in `stft` or something like zcr.

As I've said before, if you're really concerned about defaults, there's always [presets](https://presets.readthedocs.io/en/master/).

**Comment by justinsalamon** [comment]
> I don't think it makes sense to have sr always be required, e.g., it's not used in stft or something like zcr.

Sorry if I wasn't clear - I meant make `sr` required everywhere it's actually used (so not for stft, but yes for melspectrogram and load).

> I don't think we can do this, and still have a consistent interface that supports S || (y, sr)-style overloading.

Couldn't you require that the user provide either y or S, and in both cases have `sr` be positional (e.g. first), since in both cases `sr` is needed to correctly interpret `y`/`S`? Or am I missing something?

> As I've said before, if you're really concerned about defaults, there's always presets.

I'm less concerned about the actual values of the defaults, more about there being defaults in the first place, since it seems to be a common source of (human) errors.

Anyway, I realize this is no small design choice and there are many moving parts to consider (and I'm probably not thinking of all of them).

**Comment by NumesSanguis** [comment]
> As an aside: we've sometimes discussed wholly doing away with I/O and codec functionality in librosa, and encouraging people to use pysoundfile instead of `librosa.load`. (Or, audioread if folks really want mp3 support.)
> 
> If, at some point, we do deprecate `librosa.load`, this issue would resolve itself.

I tried `soundfile.read` instead of `librosa.load`, but so far I've identified 2 issues:

- `soundfile.read` doesn't accept a `samplerate` keyword for changing the sample rate at load time (and my Google-fu skills couldn't find how to do it with soundfile at all)
- `soundfile.read` doesn't accept the new [pathlib library](https://docs.python.org/3/library/pathlib.html) included in Python from v3.4.

**Comment by lostanlen** [comment]
Hi @NumesSanguis. Thank you for the feedback.

> soundfile.read doesn't accept a samplerate keyword for changing the sample rate at load time (and my Google-fu skills couldn't find how to do it with soundfile at all)

To be fair, librosa does not really change the sample rate "at load time". It loads the whole file as a numpy array at its native sample rate, and then calls `librosa.resample` to perform resampling of that numpy array. Calling `librosa.load` with `sr=None` simply skips the second step.

So, if `librosa.load` were to be deprecated, the recommended way to perform its default behavior would be:

```python
original_y, original_sr = sf.read("sample.wave")
y = librosa.resample(y, original_sr, 22050)
```

**Comment by bjourne** [comment]
I'm trying to learn audio analysis using librosa and I wonder what the rationale for resampling is? Other audio libraries doesn't do it so it is a little odd to find out that librosa does. I have also noticed that several examples in the docs assume the audio data has been resampled to 22.5 kHz or they will not work verbatim.

**Comment by bmcfee** [comment]
> I'm trying to learn audio analysis using librosa and I wonder what the rationale for resampling is?

The rationale is that it was designed as a frontend to (statistical) analysis pipelines, for which you always want a consistent sampling rate across different tracks.  In that use-case, you would always follow load by resample, so we opted to combine the two to cut down on redundant code and prevent errors in case users forgot to resample.

**Comment by bmcfee** [comment]
A more detailed discussion of this design choice can be found in our development blog: https://librosa.github.io/blog/2019/07/17/resample-on-load/#resample-on-load

Having thought a lot about this over the years, I still think that we gain more than we lose by forcing resample-on-load, and I'm not willing to change that.  (Possibly abusing my executive power here, but :man_shrugging:)

I may reconsider the *choice* of the default target sampling rate going forward, but that's a separate question.

I don't think there's much point to keeping this discussion open, but I do thank you all for your input!
