### ISSUE TITLE
Use of conjugate in stft/istft

### ISSUE THREAD

**Issue by Jonathan-LeRoux** [librosa/librosa#521]
I noticed that librosa uses the conjugate of the FFT in the stft/istft code:
```
        # RFFT and Conjugate here to match phase from DPWE code
        stft_matrix[:, bl_s:bl_t] = fft.fft(fft_window *
                                            y_frames[:, bl_s:bl_t],
                                            axis=0)[:stft_matrix.shape[0]].conj()
```
The code comments say that is "to match DPWE code", and indeed I can see that Dan's [Matlab stft.m code](http://www.ee.columbia.edu/ln/rosa/matlab/pvoc/stft.m) returns the Hermitian transpose `d(:,c) = t(1:(1+f/2))';` instead of the transpose `d(:,c) = t(1:(1+f/2)).';`, but I don't believe I've seen this convention used anywhere else.
Is there a particular reason to do so?

**Comment by dpwe** [comment]
No, it's just a screw-up that got grandfathered in.

Thank you for spotting the .' issue!  I never knew how this happened until
now.

I'd support fixing it in librosa .. except for what it breaks.

  DAn.

**Comment by Jonathan-LeRoux** [comment]
The Matlab .' vs ' is such a classic that I suspected this might be the case :)
The good thing is that as long as the code is self-consistent, I don't think there is much impact if any, so fixing it "should" keep everything working. Except of course when processing data computed with an old pre-fix version...

**Comment by bmcfee** [comment]
> Thank you for spotting the .' issue!

Ahh, matlab syntax is beautiful!

I would also support fixing this at some point, but it does introduce backwards compatibility issues, so it would have to wait for a major revision.  That said, since most of the downstream analysis is either on magnitude spectra, or otherwise invariant to global conjugation, it shouldn't have any substantial impact, as @Jonathan-LeRoux says.

Thanks for pointing this out!
