### ISSUE TITLE
error when computing spectral contrast

### ISSUE THREAD

**Issue by darktrial** [librosa/librosa#524]
I had problem getting spectral contrast when loading 8Khz wave file.  
```python
import librosa
import numpy as np

X, sample_rate = librosa.load("8k-6-1-2.wav",sr=8000)
print(sample_rate)
stft = np.abs(librosa.stft(X))
contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
print(contrast)
```

The error is 
```
> line 372, in spectral_contrast
    current_band[idx[0] - 1] = True
IndexError: index 0 is out of bounds for axis 0 with size 0
```
The wave file's location is at
[http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/a2002011001-e02-8kHz.wav](url)

**Comment by bmcfee** [comment]
The problem is that under the other default parameters, `n_bands=6, fmin=200`, the contrast bins will cover the ranges:

- 200-400
- 400-800
- 800-1600
- 1600-3200
- 3200-6400
- 6400-12800

and the last two are above nyquist for your sampling rate, hence the error.  If you lower `fmin` to `0.5 * sample_rate * 2**(-6)`, which in your case is 62.5, it ought to work.  (You might go down to 60 just to be safe.)

Alternately, you can lower the number of bands from 6 to 4. and it should work.

This is a bug in the API though, as the function should check for safety of the parameter ranges and give you a more meaningful error message.
