### ISSUE TITLE
YIN fundamental frequency estimator

### ISSUE THREAD

**Issue by karlhugle** [librosa/librosa#527]
Can anyone please tell how to get Fundamental frequency (F0) feature using Librosa?

thank you!

**Comment by stefan-balke** [comment]
Hi,

there are some features which correlate to the F0 (e. g., zero crossing rate) but it highly depends on your signal. Are you having a mixture or a monophonic signal?

For monophonic signals go with YIN (or pYIN https://github.com/ronggong/pypYIN), for more complex mixtures with a predominant melody you can try out MELODIA (Salamon et al.), available in essentia or as a VAMP plugin.

- Stefan

**Comment by faroit** [comment]
>For monophonic signals go with YIN (or pYIN https://github.com/ronggong/pypYIN), for more complex mixtures with a predominant melody you can try out MELODIA (Salamon et al.), available in essentia or as a VAMP plugin.

Also you find some more f0 estimators in [aubio](https://aubio.org)

**Comment by rabitt** [comment]
Documenting an offline conversation with @bmcfee -

After #639 is implemented, the plan is to build a generalized version of pYIN. Some ideas/considerations:
1) The viterbi emission probabilities can be likelihoods computed from the yin correlation function.
2) What should the windowing function over the yin correlation function look like?
3)  The state space has to include an "unvoiced" state, and its emission probabilites should be computed separately (e.g. using a "pitchyness" feature)
4) The first half of what we want to implement is pretty similar to the `tempogram` implementation

**Comment by bmcfee** [comment]
[tagging @tomxi]

**Comment by lostanlen** [comment]
OP @karlhugle it is worth noting that @jongwook from MARL has just released CREPE (Convolutional Representation for Pitch Estimation), which is about twice as accurate as pYIN. That might fit your use case until pYIN makes it into librosa.
https://github.com/marl/crepe

**Comment by bmcfee** [comment]
Bumping this to 0.6.2 (or later) -- we can get viterbi into 0.6.1 without stalling for pitch tracking, which will take considerably more work.

**Comment by Jackiexiao** [comment]
A better pitch estimator [Google Reaper](https://github.com/google/REAPER)

**Comment by bmcfee** [comment]
Thanks @Jackiexiao -- the purpose here isn't to have the best possible pitch tracker, but rather to have a robust, flexible, and instructive implementation of a standard method.  Existing yin/pyin implementations have a lot of hard-coded parameters that aren't easy to change, which makes them unsuitable for a lot of applications.

**Comment by lostanlen** [comment]
Indeed: now that issue #639 is closed by PR #710, a librosa implementation of pYIN is within reach :)

**Comment by ZiyaoWei** [comment]
Very interested in implementing pYIN - can I try my hands at it or are there better issues that I could hack around on?

**Comment by lostanlen** [comment]
@ZiyaoWei glad to hear that you're interested in making pYIN into the core of librosa. You've done some great work on #731 #734 #750 #753 lately, so you're definitely on a good streak of merged PRs :) Furthermore, we've just released v0.6.2, as you know, and it's unlikely that v0.6.3 will be scheduled before 2-3 months (as judged by the time span from 0.6.0 to 0.6.1 and from 0.6.1 to 0.6.2), so now is a good time for forking the repository and starting to work on this.

What would be good would be if you could write a "bullet points" list of required steps in the implemenation of pYIN. One big step was Viterbi decoding and that is already checked, but the YIN algorithm itself is a cascade of several DSP techniques that are rather subtle, so it's worth making sure that they all belong.

Then you can fork the main branch, and immediately start the PR while tagging it as [WIP] ("Work In Progress") so that the admins don't merge it until the implementation is complete. Having the PR earlier than later is great though, because it offers a discussion board + Travis and Appveyor continuous integration + tests.

This message by @/rabitt from last year is relevant:
https://github.com/librosa/librosa/issues/527#issuecomment-344390449
She's an expert on f0 estimation, and the most suited librosa developer for reviewing your pYIN code in detail, once you've made some progress on it.

@ZiyaoWei Thanks again for offering your help and bon courage with this!

**Comment by bmcfee** [comment]
Just chiming in to say: by all means go for it!  We'll help you out however we can.  Getting a basic pitch tracker in place is a pretty high priority for us, but the core components (short-time autocorrelation, viterbi, etc) are all basically in place.

In my view, the hardest thing here will be defining the API, but we can iterate on that once a prototype is in place.

**Comment by rabitt** [comment]
I'm also happy to help, and to give it a thorough review when the whole thing is ready.

Note that, as mentioned by @bmcfee, we're not looking to exactly implement pYin, but rather a generic, more flexible pitch tracker based on similar principles. The comment @lostanlen pointed to [#527 (comment)](https://github.com/librosa/librosa/issues/527#issuecomment-344390449) details the generalizations we had in mind.

**Comment by ZiyaoWei** [comment]
Here's my first (mostly none) progress report on this issue - I've been traveling a lot during the past month so didn't get much hacking done, but I should be able to work on this a fair amount for the next month or so.

I did actually finished reading both the YIN and the pYIN papers (although somewhat cursory - I'm sure implementing these can be much trickier), so I figured the first step could be implementing a basic YIN along the lines of the `tempogram` function (e.g., following mostly the exact same signature without `onset_envelop`). I would assume we don't really need to expose this function since pYIN should be both powerful and simple enough as the builtin pitch tracking method?

Feel free to correct me if I'm wrong and/or if I am missing something obvious. I'll try to put some code in a pull request soon since, well, code wins arguments.

**Comment by bmcfee** [comment]
> so I figured the first step could be implementing a basic YIN along the lines of the tempogram function (e.g., following mostly the exact same signature without onset_envelop).

I'm not sure I follow you entirely, but I interpret this as just computing a (centered, windowed), autocorrelogram of the input audio signal?  If so, yeah, I think it might be worth factoring that out into its own function, but it's fine to leave it built into the pitch tracker function for a first cut.

After that, the main pieces are constructing the viterbi decoding parameters and hooking it all together.

**Comment by lostanlen** [comment]
>  I would assume we don't really need to expose this function since pYIN should be both powerful and simple enough as the builtin pitch tracking method?
I would prefer to expose YIN as well as pYIN, given that there are other algorithms in the literature that are built on YIN and not pYIN. YIN-Bird (O'Reilly Interspeech 2016) comes to mind for instance
https://www.isca-speech.org/archive/Interspeech_2016/pdfs/0090.PDF

**Comment by ZiyaoWei** [comment]
Thanks @lostanlen! The possibility to reuse YIN as a building block is
exactly why I asked :-)

**Comment by xiaoch2004** [comment]
If you mean fundamental frequency, here's my implementation of pYIN with librosa:
[https://github.com/xiaoch2004/librosa_py3_pYIN](https://github.com/xiaoch2004/librosa_py3_pYIN)
It's based on [pypYIIN](https://github.com/ronggong/pypYIN), hope it helps!

**Comment by lostanlen** [comment]
@xiaoch2004 Welcome to librosa! Thank you for your update.

A few comments to make:

* the code you host is licensed under GNU Affero GPL by the Music Technology Group in Barcelona. I looked at your diff and what you did was to take the code of ronggong, update `demo.py`, and convert a few print statements to Python 3. You removed the copyright notice; don't do this! Read the license first.

* if you want to use the full capabilities of librosa, you should use `librosa.sequence.viterbi` in lieu of `MonoNoteHMM.py`, `MonoPitchHMM.py`, etc.

* generally speaking, this package has a lot of unnecessary classes. It could be refactored into a purely functional paradigm. To understand what i mean, i suggest you watch this lecture:
https://www.youtube.com/watch?v=o9pEzgHorH0

**Comment by rafaelvalle** [comment]
@xiaoch2004 thanks for this contribution! 
Would love to see this merged to librosa as it's a very valuable contribution to our community!

**Comment by lostanlen** [comment]
@rafaelvalle unfortunately we couldn't include it into librosa as-is, at it would be a blatant infringement of the GNU Affero GPL

**Comment by xiaoch2004** [comment]
@lostanlen Thanks! It's glad to make contributions to the community. It's my first time involved with copyright issue. I've modified the license according to GNU Affero GPL in my repo. Have a check please. For the code refactoring issue, I'll fix it later. Looking forward to more suggestions to let my code help more people.

**Comment by lostanlen** [comment]
@xiaoch2004 This code could be simplified considerably by using some tools that already exist in librosa. 
See the original YIN paper: http://audition.ens.fr/adc/pdf/2002_JASA_YIN.pdf
Use `librosa.frame` for splitting the waveform into small frames.
Then, Equation 1 can be implemented directly with `librosa.core.autocorrelate`
Then, it's about getting a difference function: see Equation 7. It's just a difference of floating-point numbers and array.
Equation 8 can be done with pure numpy
Then you can apply a constant threshold (Section II.D)

When you arrive there, we can catch up and working on the post-processing: parabolic interpolation, best local estimate, and ultimately, Viterbi decoding (pYIN). But i think that we should be able to write tests for the simplest cases before that.

**Comment by lostanlen** [comment]
<img width="432" alt="Screen Shot 2019-07-21 at 10 46 07 AM" src="https://user-images.githubusercontent.com/3943142/61592705-de0eaa00-aba4-11e9-9f6f-e95aa1261139.png">
important details

**Comment by ZiyaoWei** [comment]
I definitely dropped the ball here :-/ Thanks for taking this on @xiaoch2004!

**Comment by abdoulsn** [comment]
> Hi,
> 
> there are some features which correlate to the F0 (e. g., zero crossing rate) but it highly depends on your signal. Are you having a mixture or a monophonic signal?
> 
> For monophonic signals go with YIN (or pYIN https://github.com/ronggong/pypYIN), for more complex mixtures with a predominant melody you can try out MELODIA (Salamon et al.), available in essentia or as a VAMP plugin.
> 
> Stefan

What other features is also correlated with? I use speech emotion data is zc good enough

**Comment by lostanlen** [comment]
@abdoulsn spectral centroid and spectral rolloff

**Comment by abdoulsn** [comment]
Thanks, Are both extractable in librosa?

**Comment by abdoulsn** [comment]
> @abdoulsn spectral centroid and spectral rolloff

Thanks lot.
