### ISSUE TITLE
different length of feature between rmse and others

### ISSUE THREAD

**Issue by karlhugle** [librosa/librosa#528]
when use the same hop_length=512
librosa.feature.rmse has different length than others. can anyone help me to explain it?

Please find attached screenshot.

![rmse](https://cloud.githubusercontent.com/assets/16356616/23834572/85c3801e-0750-11e7-8b17-a87c21ed0d8f.png)

**Comment by bmcfee** [comment]
`rmse`, by default now uses time-domain calculation, and left-aligned frames, rather than padded, center-aligned frames like the frequency-domain representations.  As a result, the frame counts and positions are different here.

You can circumvent this by precomputing a spectrogram:

```python
>>> S = np.abs(librosa.stft(y=y, hop_length=hop_length))
>>> rmse = librosa.feature.rmse(S=S)
```

---

@carlthome any interest in smartening up the `rmse` logic to simulate centered windows and zero-padding, for consistency with the other features?  It should be fairly straightforward to do this without explicit copy+padding, if you just slice off the partial energy from the first (left-aligned) frame.

**Comment by bmcfee** [comment]
Note: this is actually a bit subtler to get right because the stft implementation uses reflection padding of `y` for frame centering, so interpolating RMSE at the edges won't do exactly the right thing.

Once #531 is implemented, this will get even more complex.

Maybe a reasonable compromise is to implement a padding mode to `feature.rmse`, controlled by a `center` flag, which can decide to pad out the rmse to the correct shape for centered frame analysis, and use any of the `np.pad` modes to handle the edges.

**Comment by carlthome** [comment]
Let me take a stab at this. I see two issues:

1. For user convenience, array shape should be the same regardless of if `librosa.feature.rmse` is called with a precomputed spectrogram or a waveform.
2. The computed RMS energy from a waveform should be aligned like the default `librosa.stft` (I assume changing the default to `center=False` is not a reasonable solution?).

> Maybe a reasonable compromise is to implement a padding mode to feature.rmse, controlled by a center flag, which can decide to pad out the rmse to the correct shape for centered frame analysis, and use any of the np.pad modes to handle the edges.

In that API, how should this be handled?

```python
import librosa as lr

y, _ = lr.load(lr.util.example_audio_file())
S = lr.magphase(lr.stft(y, center=False))[0]
lr.feature.rmse(S=S, center=True)
```

Also, for `lr.feature.rmse(y=y, center=True)`, would it be reasonable to reflect pad in the time domain from the earliest zero crossing?

**Comment by bmcfee** [comment]
> In that API, how should this be handled?

I'm not sure I follow your example code, but I was thinking something like the following:

```python
rmse(y=y, center=False)  # no centering, should match shape with stft(..., center=False)
rmse(y=y, center=True)  # centered frames, should match shape with stft(..., center=True)
rmse(y=y, center=True, pad_mode='reflect', ...)  # like above but changing how the padding is done
```
in the last example above, the `...` params are pass-through to `np.pad`.  Note that this would apply *after* rmse calculation, and not before to the time-domain signal, so it won't be exactly the same as padding within `stft` to achieve frame centering.

**Comment by carlthome** [comment]
What I mean is, when calculating RMS energy with a precomputed spectrogram, how should the `center` flag be interpreted (as it would have no effect)?

**Comment by bmcfee** [comment]
I think it's fine to just ignore the `center` parameter in that case, and document the semantics as having the output always match the shape of the corresponding spectrogram.

**Comment by bmcfee** [comment]
This is the last issue on the stack for 0.5.1, so i'll self-assign and jam this out.

**Comment by carlthome** [comment]
Sorry, never got around to it. :zipper_mouth_face:
