### ISSUE TITLE
Incorrect size of mel spectrogram

### ISSUE THREAD

**Issue by nevosegal** [librosa/librosa#530]
Hi,

I compute the mel spectrogram on a time-domain signal that has `13230080` samples, like so:

    mel_spectrogram = librosa.feature.melspectrogram(audio_data, sr=44100, n_fft=2048, hop_length=512)

The resulting shape of the `mel_spectrogram` is `(128, 25841)`, however as far as I understand it should be `(128, 25840)` (n_mel, length of time domain signal / hope size). For some reason it has one extra frame.

Can you please explain? Thanks!

**Comment by bmcfee** [comment]
Librosa uses centered frames by default, and to achieve this, spectrograms are constructed by zero-padding the signal by half a frame.  This probably explains the discrepancy you're seeing.

If you want left-aligned frames, you can compute the STFT manually with `center=False` and then use that as input downstream instead of `audio_data`.  However, you'll need to be careful to pass `center=False` around to other functions when converting frame indices back to samples / timing, or inverting the spectrogram.

**Comment by nevosegal** [comment]
Thanks for that. Right, so it zero pads the whole of the signal at once? Not frame by frame?

When I use `center=False`, will it still do some zero-padding during the STFT?

**Comment by nevosegal** [comment]
Just read the docs and got the second question clarified, thanks for your help!

**Comment by bmcfee** [comment]
> Thanks for that. Right, so it zero pads the whole of the signal at once? Not frame by frame?

Correct: this is how it ensures that frame `t` is centered at sample `t * hop_length`.

Frame-level zero-padding is a separate idea, but if you want that, you can do it by setting `n_fft` larger than `win_length`.

**Comment by nevosegal** [comment]
Out of curiosity, what's the advantage of using centered frames over left-aligned frames?

**Comment by nevosegal** [comment]
hmmm with `center=False` I get `25837` mel spectrums.. So:

`center=True` = `25841` spectrums
`center=False` = `25841` spectrums
`Expected result` = `25840` speectrums

**Comment by bmcfee** [comment]
> Out of curiosity, what's the advantage of using centered frames over left-aligned frames?

A few:

- Ease of conversion between frame indices and sample positions.  If a frame is windowed, the relevant position is the center, not the left edge (which contributes near 0 to the frame's information after windowing).  If you then want to know where the center is for a left-aligned frame, you need to also know the frame length.  If it's centered, then the position is the same regardless of frame length.
- Consistency with variable-frame analyses, eg, CQT.  This is basically the same point as above, but since every CQT basis has a different filter length, you can't get away with left-aligned frames at all.

**Comment by bmcfee** [comment]
> Expected result = 25840 speectrums

I'm curious where you're getting this number from.

If you have 13230080 samples, `n_fft = 2048` and `hop_length = 512`, then the number of whole frames you can fit (left-aligned) is `1 + (n - n_fft) // hop_length = 25837`.

**Comment by nevosegal** [comment]
why is it `1 + (n - n_fft)` in the numerator? If I have 13230080 samples, can't I simply divide it by the `hop_length` to compute the number of whole frames I can fit?

**Comment by nevosegal** [comment]
Right, I computed it incorrectly, got it now. Thanks again! 💯

**Comment by bmcfee** [comment]
> why is it 1 + (n - n_fft) in the numerator?

It's `(n - n_fft)` in the numerator.

Working backwards, say you have a maximum frame number `T` and that frames are left-aligned.  For the last frame to be contained in the signal, you need `T * hop_length + n_fft < n`.  Rearranging terms, you get `T < (n - n_fft) / hop_length`.

The 1+ is there to handle the zero-hop case (ie the first frame).
