### ISSUE TITLE
Citing zenodo vs scipy paper

### ISSUE THREAD

**Issue by sertansenturk** [librosa/librosa#545]
Hi librosa folks,

While updating my reference repository, I realized that I have bibtex entries for librosa:

1. From the README linking to Zenodo: https://doi.org/10.5281/zenodo.293021
2. From the [documentation](http://librosa.github.io/librosa/) linking to the [Scipy Paper](http://conference.scipy.org/proceedings/scipy2015/pdfs/brian_mcfee.pdf)

It is a small issue, but the text in the README and the documentation could be somewhat misleading and might actually lead to a dispersion in your citations (Google Scholar also agrees: https://scholar.google.com/scholar?q=librosa).

My 5 cents is to include the paper in the README as early as possible as was done in the documentation, and use Zenodo to specify the particular version. 

If you would like, I could make the changes and send a pull request for your review. I was wanted to get your opinion before making any change.

**Comment by bmcfee** [comment]
Thanks for bringing this up @sertansenturk 

The core issue here, I think, is what the purpose of a software citation is.  I prefer that people cite the version of the software that they're using, which is indexed by zenodo.  You're right that this leads to citation dispersion, but I think (perhaps foolishly) that it's more useful to use citations to improve scholarship and reproducibility, rather than inflate my h-index. :grin: It also ensures that contributing authors get credit for whatever version(s) are used, which has been a real problem for projects like scikit-learn.

The scipy paper was written primarily to advertise the software, and to a lesser extent, document the motivation and design process.  If an author wishes to cite librosa for its design, rather to indicate that it was used to generate some experimental results, then they should cite the scipy paper instead.

**Comment by sertansenturk** [comment]
I totally agree with you in the usage, i.e. SciPy to refer to the librosa itself and Zenodo to refer if the library is actually used. In my opinion if there could be something like (stealing from your response):

```
If you wish to cite librosa for its design, motivation etc., please cite the paper:

   Scipy paper

If you are using the library for your work, for the sake of reproducibility, please cite the proper version as:

   Zenodo reference
```

in the README and everything will be clear. @bmcfee, do you think it makes sense?

**Comment by keunwoochoi** [comment]
OR BOTH!

It would be good if it's on README. I feel like fixing README is very much of the owner's thing ;)

**Comment by bmcfee** [comment]
Yeah, fair point!  I'm a bit swamped for the next couple of weeks, but will get back to this.

**Comment by xyz010** [comment]
Hello, I created a bibtex citation, let me know what you think

`@article{librosa, 
title={librosa: Audio and Music Signal Analysis in Python}, 
DOI={10.25080/majora-7b98e3ed-003}, 
journal={Proceedings of the 14th Python in Science Conference}, 
author={Mcfee, Brian and Raffel, Colin and Liang, Dawen and Ellis, Daniel and Mcvicar, Matt and Battenberg, Eric and Nieto, Oriol}, 
year={2015}
}`
