### ISSUE TITLE
Allow max-amplitude normalization in mel spectra

### ISSUE THREAD

**Issue by dpwe** [librosa/librosa#549]
Currently filters.mel generates fft-to-mel mappings that attempt to keep the integral of each mel band's row of weights approximately constant.  This is in keeping with Slaney's original AuditoryToolbox:mfcc.m, but is different from HTK, which is the de-facto standard for MFCC calculation - which has each row aim for a constant peak value, instead of a constant integral.

We could optionally support something closer to HTK by adding a normalization argument to mel() which defaults to 'integral', but can optionally be set to 'maximum' to get more HTK-like behavior.  It turns out that the HTK-like behavior gives mel spectrograms that look nicer, since the increasing integral for higher mel bands acts a bit like pre-emphasis to balance the energy rolloff of natural sounds.

Note, using the actual sum or max is not what we want, since the sampling of the underlying triangle functions make the empirical sum or max of each mel weight row not exactly what we want.

fix is something like:
```python
if normalization == 'integral':
      enorm = 2.0 / (freqs[2:n_mels+2] - freqs[:n_mels])
elif normalization == 'maximum':
      enorm = np.ones(n_mels)
else:
      raise ValueError('Unrecognized normalization argument: ' + normalization)
```

**Comment by bmcfee** [comment]
Sounds good to me.  API-wise, even though we wouldn't be using the numerical sum/max, i think it makes sense to keep the signature consistent with the rest of the package, eg, `norm='sum'` or `norm='max'` rather than having separate strings `integral` or `maximum`.  But that's a minor point.

`max`-normalization in your example appears to be a no-op though (multiply by 1).  Are there other variations that we should consider supporting?  Or would it make more sense to just make normalization a boolean option?

**Comment by dpwe** [comment]
norm='sum' or 'max' sounds good.

I thought about a boolean, but it's not obvious what to call it.  If you call it normalize_by_energy_not_peak_magnitude, it sort of seems better to specify normalize_by=(one or the other).  

I don't think there are any other normalization modes we'd want in practice, though.

**Comment by bmcfee** [comment]
> norm='sum' or 'max' sounds good.

How about using the same semantics as [`util.normalize`](https://librosa.github.io/librosa/generated/librosa.util.normalize.html?highlight=normalize#librosa.util.normalize)?  This would use `norm=1` as the current (sum) behavior, `norm=None` for unnormalized, and `norm=np.inf` for max-normalized.  We don't really need the full generality of all Lp normalizers here, but since we have the function already, we may as well use it and be consistent about the API.

**Comment by dpwe** [comment]
+1 for consistency in the API.

I think we'd have "unnormalized" be the same as "max-normalized", but
there's no harm in that.

  DAn.
