### ISSUE TITLE
Problem with spectral_bandwidth having only one frame

### ISSUE THREAD

**Issue by Mereep** [librosa/librosa#552]
Hello folks,

I try to use the librosa library for some library I want to implement, which essentially extracts some features from audio files. These files can be very short (including only one frame when transforming it with say stft)

So I stumpled about some unexpected behaviour when using the spectral_bandwith feature.

Let S be some spectrogram (S[bins][frames])
then the following calls will produce (for me) unexpected output:

`res_expected_1 = spectral_bandwidth(sr=sr, S=S)`
`res_expected_2 = spectral_bandwidth(sr=sr, S=S[:,0:2])`
`res_unexpected = spectral_bandwidth(sr=sr, S=S[:,0:1])`

Expected results return for each frame a number. 
So for _res_expected_2_ exactly 2 
and for _res_expected_1_ exactly _len(S[0])_
while res_unexpected produces _bin_num_    results. Which I don't think is what it is intented to do.

in addition I don't know why the results are wrapped in an array like [[frames]] instead of just [frames]

I hope someone can help me out a bit;
Thanks for your time meanwhile

**Comment by bmcfee** [comment]
Confirmed that this is a bug, thanks for reporting it.  I think I see where the error is creeping in: [this line](https://github.com/librosa/librosa/blob/master/librosa/feature/spectral.py#L247).  This shouldn't crop up in any other feature functions.

> in addition I don't know why the results are wrapped in an array like [[frames]] instead of just [frames]

This is for consistency; all of the functions in `librosa.feature` generate analyses in the shape `(n_channels, n_frames)`.  For some analyses, there's only a single channel of interest, e.g. `spectral_bandwidth` or `rmse`.  In these cases, we add a singleton dimension so that different feature types have a consistent index structure.  This way, we can easily concatenate features together, or process them by `sync` or `stack_memory` without having to special-case the indexing.

**Comment by Mereep** [comment]
Actually I was already at this line. But my brain got a overwhelmed from the (for me new) outer subtract and squeeze operation, that I thought, I will leave it to the python professionals ;-)

**Comment by bmcfee** [comment]
@Mereep yeah, the issue there is a premature flattening into 1d before expanding back into 2d.  It should be pretty easy to fix, but I can't get it to it until later this week.

**Comment by Mereep** [comment]
@bmcfee 
I don't know exactly what I did, but that fixed for me ;-)

    if freq.ndim == 1:
        squeezed_centroid = np.squeeze(centroid)
        if squeezed_centroid.ndim == 0:
            squeezed_centroid = [squeezed_centroid]
        deviation = np.abs(np.subtract.outer(freq, squeezed_centroid))

**Comment by bmcfee** [comment]
Cool, glad it's working for you.

I think we'll need a slightly more general solution to handle the instantaneous frequency case properly, but it'll for sure make it into the next point release.
