### ISSUE TITLE
_spectrogram should be public and include win_length parameter

### ISSUE THREAD

**Issue by chananshgong** [librosa/librosa#571]
The [`_spectrogram`](https://github.com/librosa/librosa/blob/master/librosa/core/spectrum.py) method should be public (_spectrogram->spectrogram) and should accept all parameters of `stft` such as `win_length` and `window` or just pass arbitrary parameters to `stft`.

Currently, methods which uses `_spectrogram` methods such as `mfcc` and `melspectrogram` don't support these parameters.

**Comment by bmcfee** [comment]
If you want custom stft parameters, there's nothing stopping you from computing it first and passing as input to the functions you use.

The _spectrogram function is an internal convenience function to reduce boiler plate code for handling either time or frequency domain inputs in spectral feature computations. I do not think it should be made public-facing.

**Comment by chananshgong** [comment]
Computing spectrogram is a common and useful feature. In deep learning, this is the the most common pre-processing stage.  Therefore, I don't see why to hide it. Moreover, I don't see why not pass all parameters to the underlying stft rather than just the one which are passed right now. If we change this, then mfcc will be generic in terms of `window` type and window length. Currently, `win_length` is implicitly constraint to be `n_fft` .

**Comment by bmcfee** [comment]
I think you misunderstood what this function is for. There are plenty of user-facing functions to compute various types of spectrogram representations in librosa, but this is not one of them.

As for exposing all parameters to upstream functions, i am opposed to this because it unnecessarily complicates the API. If you want alternate parameterizations, that's why the feature functions accept spectrogram inputs as well as time domain inputs.
