### ISSUE TITLE
inconsistency with python_speech_features

### ISSUE THREAD

**Issue by chananshgong** [librosa/librosa#573]
I compared the mfcc of [librosa](https://github.com/librosa/librosa/) with [python_speech_analysis](https://github.com/jameslyons/python_speech_features) package and got **totally different results**. 

Which one is correct?
librosa list of first frame coefficients:

> [-395.07433842032867, -7.1149347948192963e-14, 3.5772469223901538e-14, -1.7476140989485184e-14, 3.1665300829452658e-14, -4.4214136625668904e-14, 6.7157035631648599e-14, 1.5013974158050108e-14, 2.9512326634271699e-14, 7.2275398398734558e-14, -1.5043753316598812e-13, -2.2358383003147776e-14, 1.6209256159527285e-13]

python_speech_analysis list of first frame coefficients:

> [-169.91598446684722, 1.3219891974654943, 0.22216979881740945, -0.7368248288464827, 0.26268194306407788, 1.8470757480486224, 3.2670900572694435, 2.3726120692753563, 1.4983949546889608, 0.67862219561000914, -0.44705590991616034, 0.39184067109778226, -0.48048214059101707]

```
import librosa
import python_speech_features
from scipy.signal.windows import hann

n_mfcc = 13
n_mels = 40
n_fft = 512 # in librosa, win_length is assumed to be equal to n_fft implicitly
hop_length = 160
fmin = 0
fmax = None
y, sr = librosa.load(librosa.util.example_audio_file())
sr = 16000  # fake sample rate just to make the point

# librosa
mfcc_librosa = librosa.feature.mfcc(y=y, sr=sr, n_fft=n_fft,
                                    n_mfcc=n_mfcc, n_mels=n_mels,
                                    hop_length=hop_length,
                                    fmin=fmin, fmax=fmax)

# python_speech_features
# no preemph nor ceplifter in librosa, so setting to zero
# librosa default stft window is hann
mfcc_speech = python_speech_features.mfcc(signal=y, samplerate=sr, winlen=n_fft / sr, winstep=hop_length / sr,
                                          numcep=n_mfcc, nfilt=n_mels, nfft=n_fft, lowfreq=fmin, highfreq=fmax,
                                          preemph=0, ceplifter=0, appendEnergy=False, winfunc=hann)


print(list(mfcc_librosa[:, 0]))
print(list(mfcc_speech[0, :]))
```

**Comment by bmcfee** [comment]
This question is really better suited to the Google group, since it pertains to usage and not bugs or feature requests.

However, neither is "correct" nor "incorrect". I don't know how Python-speech-features is implemented, but librosa is thoroughly regression tested against @dpwe's Matlab implementation. 

There are a lot of subtle things under the hood to do with windowing, padding, etc, so I wouldn't expect numerical equivalence between librosa and another independent implemention.

**Comment by chananshgong** [comment]
I made sure I use exactly the same parameters, at least as stated. I think that the community will be confused if each implementation of MFCC outputs totally different outputs. How can one compare between packages or reproduce one another results?

I would like to contribute to librosa and make mfcc function be customized in respect to window type, preemph etc, but first I want to realize the current implementation is correct.

**Comment by albertz** [comment]
Any update here? And the provided sample code is Python 3? Otherwise the `winlen = n_fft / sr` etc would be zero.

**Comment by bmcfee** [comment]
> Any update here?

I'm not sure anything here needs updating?  OP never responded to my follow-up questions, so it's not clear what there is to add to this conversation.

**Comment by bmcfee** [comment]
Closing this one out due to lack of activity.

However, if anyone wants to implement pre-emphasis or liftering, they'd be welcome additions!

**Comment by harmanpreet93** [comment]
@chananshgong did u find out the reason why the features are inconsistent in both the libraries? Which library would you recommend to use if we are using mfcc features for some speech application?

**Comment by lostanlen** [comment]
@harmanpreet93 one reason for inconsistency that I can find in the OP's code is that the `htk` flag must be set to `True` so that the  definition of the mel scale matches the one that is used in python_speech_features. But that does not explain the stark differences in MFCC magnitudes.

> Which library would you recommend to use if we are using mfcc features for some speech application?
Of course, cannot answer this question in full objectivity. As bmcfee said earlier, there is not a single definition of the mel scale (librosa implements two of them: Slaney and HTK). So the notion of "correctness" is ill-defined here. However, librosa has more unit tests, a more extensive documentation, and a larger user community, so all these "soft metrics" make the case for using librosa.
