### ISSUE TITLE
onset detection missing first onset at 0:00

### ISSUE THREAD

**Issue by marikgoldstein** [librosa/librosa#585]
#### Description

On audio recordings that start directly at time 0:00 (e.g., what you get when you export a MIDI track as a WAV), librosa.onset.onset_detect(x,fs) misses the first onset. I'm still getting started with signals so I'm not sure if this is unavoidable!!!

#### Steps/Code to Reproduce
```
def get_onset_times(x, fs):
    onset_frames = librosa.onset.onset_detect(x, fs)
    return librosa.frames_to_time(onset_frames, fs)

x, fs = librosa.load('melody.wav')
onsets = get_onset_times(x, fs)

```
  
#### Expected Results
all onsets

#### Actual Results
all but initial onset (still really impressive!).

For a file that I know starts at 0:00, I just use:
```
 if onsets[0] != 0:
        onsets = numpy.array([0] + list(onsets))
```

but this isn't great.

#### Versions
Darwin-16.4.0-x86_64-i386-64bit
('Python', '2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]')
('NumPy', '1.12.1')
('SciPy', '0.18.1')
('librosa', '0.5.1')

**Comment by bmcfee** [comment]
I'm not sure there's much we can do here. Onsets can only be defined by contrast to the previous frame, since they're inferred from rising energy. At time 0, there is no previous frame, so it's impossible to detect.

You could maybe get around it by padding the signal first, and then subtracting off the resulting delay. This has the benefit that a signal starting with 0 amplitude will not interested an extra onset.

**Comment by marikgoldstein** [comment]
That make's perfect sense. I'll try experimenting with some zero padding in front of the signal. Thanks! Sorry, I know realize that this was more of a usage question than "bug question".
