### ISSUE TITLE
audioread.NoBackendError

### ISSUE THREAD

**Issue by caimj1993** [librosa/librosa#589]
i do not know how to install  ffmpeg.who can help me.when i run the :#coding=gbk
import librosa

def extract_feature(file_name):
    y, sr = librosa.load(file_name)
    y = librosa.effects.harmonic(y)
    tonnetz = librosa.feature.tonnetz(y=y, sr=sr)
    return tonnetz

print extract_feature("V1002_CCTVHD火炬手.avi")

audioread.NoBackendError

**Comment by keunwoochoi** [comment]
What's your OS? Could you try it after installing ffmpeg?

**Comment by caimj1993** [comment]
windows,after installing ffmpeg,it was report same error.i do not konw why.

**Comment by keunwoochoi** [comment]
Yeah.. then I don't know, but it is basically about Audioread, not librosa, as the error message clearly says. So it would be faster asking there.

**Comment by carlthome** [comment]
I think I've read that @bmcfee wants to remove audio file reading/writing out of librosa but I see a lot of people using `librosa.load` in various tutorials and stuff so it seems useful to keep IO around in core IMO.

However, I think it could be worthwhile moving librosa.load from depending on audioread to [soundfile 
](https://github.com/bastibe/PySoundFile) instead, because it will work out of the box on Windows and OS X (and for Linux, libsndfile is available via conda-forge, as well as most system package managers like `apt`). It would also support writing compressed audio, that `librosa.output.write_wav` could be deprecated in favor of a `librosa.save` function matching the load function.

I could have a pull request with such a change done tomorrow if it is of interest, @bmcfee.

**Comment by stefan-balke** [comment]
Hey,

so libsndfile came up from time to time but was not available on conda forge.
In the meantime, they have it here: https://github.com/conda-forge/libsndfile-feedstock

But also not for Windows which would be a pain to deploy...
I think `soundfile` circumvents this by shipping the dlls together with the package, so that would work.
However, we would currently lose mp3 support which some people use, I guess...

**Comment by bmcfee** [comment]
To clarify, my ideal scenario is the following:

1. libsndfile gets mp3 support (now legally/license-wise possible and just waiting for someone to step up and do it: https://github.com/erikd/libsndfile/issues/258 )
2. swap out audioread for soundfile under the hood in librosa

2 is fairly trivial to do, but I wouldn't merge it until there's stable mp3 support.  I would expect the number of bug reports due to lack of mp3 support would dwarf what we currently get via audioread.

**Comment by carlthome** [comment]
Ah, didn't think MP3 was missing. Subscribed to https://github.com/erikd/libsndfile/issues/258, thanks @bmcfee and @stefan-balke

**Comment by bmcfee** [comment]
Since this issue appears to be an audioread problem, I'm closing it out.

**Comment by tsando** [comment]
Just to say that I was having the same error on my Mac and mine got fixed after installing `ffmpeg` using `brew install ffmpeg`. And yes, issue seems to be realted to `audioread`. I got this error when calling `librosa.load(filename)`.

**Comment by carlthome** [comment]
Good that you got it working. It's mentioned in the README: https://github.com/librosa/librosa#audioread

**Comment by keunwoochoi** [comment]
Probably we can think of taking it as a special cade and providing how to deal with it in an error message. Can’t look into the code at the moment so I don’t know if it would make sense though..

On 9 Mar 2018, at 11:25, Carl Thomé <notifications@github.com<mailto:notifications@github.com>> wrote:


Good that you got it working. It's mentioned in the README: https://github.com/librosa/librosa#audioread

**Comment by KimRasak** [comment]
It worked, After I installed ffmpeg by `pip install ffmpeg`, and restarted the Pycharm IDE.

**Comment by crissallan** [comment]
If you are using Mac, check if the audio file folder contain a .DS_Store file!!! (using ls -a)
Delete it and everything would work fine

**Comment by surya203** [comment]
> What's your OS? Could you try it after installing ffmpeg?

Working for linux distributors

**Comment by pranaswi23** [comment]
even after installing ffmpeg i am getting same error.i dont know why.and please hep me.

**Comment by accraze** [comment]
I ran into this issue today when trying to load a non-audio file by accident.

**Comment by shuiyuejihua** [comment]
I load .mp3 audio,  it  happens, pip install ffmpeg don`t work for me.    Change  to  .wav  audio ,  it is ok . just the same file from moviepy saved.
.mp3,  2. 73 MB ，while  .wav 30. 2 MB

**Comment by harrett** [comment]
Just use conda:
`conda install ffmpeg`
