### ISSUE TITLE
Comparing scipy fft with librosa

### ISSUE THREAD

**Issue by JulietteCarter** [librosa/librosa#610]
I am simply trying to replicate a simple fft behaviour with librosa.stft
I am creating a sine wave and plotting the fft using scipy fft (nfft=4096)
Then I am using librosa.stft with the same nfft, and plotting the corresponding slice.

I would expect the same results, however I get different plots and the peaks to not have the same amplitude. Why is this different? How are you performing the stft?

```## create a 1k tone
## create a 1k tone
fs = 44100 #sampling frequency
f = 1000 #freaquency
num_of_samples =40960
sinewave = [0]*num_of_samples #initialise signal

for n in range(num_of_samples):
    sinewave[n] = np.sin(2*np.pi*f*n/fs)
sinewave = np.array(sinewave)

## Test with scipy.fftpack
testSineWave = sinewave[0:4096]
testFFT = scipy.fftpack.fft(testSineWave, 4096)
testFFT = np.abs(testFFT[0:2049])

## Test with librosa
spectrogram = librosa.stft(sinewave, 4096)
amplitude = np.abs(spectrogram[:,0])

```

**Comment by bmcfee** [comment]
The short answer is that there's a lot of stuff going on inside `librosa.stft`, including frame padding, centering, and windowing.  A more vanilla `stft` would be

```python
librosa.stft(sinewave, 4096, window=np.ones, center=False)
```
If you'd like to know more, you can always crack open the source and take a look: https://github.com/librosa/librosa/blob/master/librosa/core/spectrum.py#L142

**Comment by carlthome** [comment]
FYI SciPy recently merged a [STFT](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.stft.html) and inverse. They assume a sampling rate of 1, default to 50% overlap, and pad the signal end instead of [truncating it](https://github.com/librosa/librosa/blob/a41361c6629e5163f162bd2e20399b886812f714/librosa/util/utils.py#L93) but otherwise it looks pretty close (Hann window, centered frames, etc.). No idea about performance though.

**Comment by bmcfee** [comment]
@JulietteCarter did the above answer your question?  If so, can we close this thread?
