### ISSUE TITLE
Per-channel energy normalization (PCEN)

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#615]
#### Description
PCEN [(Wang et al.)](https://arxiv.org/pdf/1607.05666) seems to be a good alternative to log-amplitude scaling for speech recognition systems; see also: [(Battenberg, et al.)](https://arxiv.org/abs/1705.04400).  Since it's fairly easy to implement in the static (non-trainable) form, do folks thing it's worth including in librosa?

Here's a quick reference implementation of eq.1 in the paper, using the default parameters listed in section 2:
```python
def pcen(E, alpha=0.98, delta=2, r=0.5, s=0.025, eps=1e-6):   
    M = scipy.signal.lfilter([s], [1, s - 1], E)
    smooth = (eps + M)**(-alpha)
    return (E * smooth + delta)**r - delta**r
```
It could probably be made more numerically stable.  It could also be vectorized to support channel-dependent parameters, which might make it more useful for things like CQT.

**Comment by keunwoochoi** [comment]
I think so. I also know some audio event detection people who's (probably) using it.

**Comment by bmcfee** [comment]
@lostanlen does this implementation match yours?

**Comment by lostanlen** [comment]
Sorry for the late reply. Yes, this implementation is the one I use, modulo changes in parameter values.

**Comment by bmcfee** [comment]
Do you have any thoughts about changing the API so that `s` is inferred from the frame rate (sample rate / hop length)?  It would be more consistent with the rest of the librosa API.

AFAICT the rest of the parameters don't present any problems.

**Comment by lostanlen** [comment]
Yes, it would be useful to specify `s` by giving a time constant in physical units, such as half-time.
Other idea, maybe very foolish: making `eps` and `delta` relative to the magnitude of `E`?

**Comment by bmcfee** [comment]
> Yes, it would be useful to specify s by giving a time constant in physical units, such as half-life.

That makes sense, although it might be handy to provide an optional argument to bypass that and set it directly so that exact comparisons can be made.



> Other idea, maybe very foolish: making eps and delta relative to the magnitude of E?

I think `eps` should be absolute, since it's there primarily for numerical stability purposes.  I could see the case for `delta` being relative, but it's probably simpler to leave it as is.

**Comment by lostanlen** [comment]
I'm glad this is included in the 0.6.1 milestone.
Re: numerical stability, do you mean replacing
`smooth = (eps + M)**(-alpha)`
by
`smooth = np.exp(-alpha * np.log1p(M/eps))`
?

**Comment by bmcfee** [comment]
No, I meant that the purpose of the `eps` parameter is to provide numerical stability in the calculation of `smooth`: if `M` has low values, then `M**-alpha` would underflow.  For this reason, I favor keeping `eps` as an absolute parameter, as it's really intended to compensate for machine precision issues, much like the `amin` parameter in `amplitude_to_db` &friends.

**Comment by lostanlen** [comment]
`eps = 1e-6` is still orders of magnitude greater than machine precision. It's of the order of machine epsilon in single precision (32 bits). But I'm fine with keeping it as an absolute parameter by default. It can be changed by the user anyway, so whoever wants to fiddle with it, can.

However I still think that `(eps + M)  ** (-alpha)` is numerically unstable for M << eps, in the sense that is does not necessarily comply with the expected Taylor approximation:
`(eps + M)  ** (-alpha)   ≈    -alpha * eps(-(alpha+1)) * M`

Whereas using IEEE 754 functions `log1p` or `expm1` is probably more accurate at low energies.

**Comment by bmcfee** [comment]
Good points.  All that said, I think it's sane to default to the parameters listed in the paper unless we have strong reasons against doing so.  Implementation details may vary whether or not we change the defaults.

As mentioned above, the only one I'm a little wary of keeping at the paper's default is `s`, because it's tuned to a particular frame rate which differs from the defaults throughout librosa.

**Comment by bmcfee** [comment]
Follow-up on defaults: from the paper's parameters: `Note that s = 0:025 translates to a 40-frame time constant for the IIR smoother` and `For both log-mel and PCEN frontend, each frame is computed based on a 40-channel mel filterbank with 25ms windowing and 10ms frame shift`, which comes to a ~400ms time constant (~395ms by my count).

Translating this into the librosa default frame rate, `s=0.0571` gets pretty close (~395ms), but it's a rather ugly magic number.  Would it make more sense to just go with `s=0.06` (or 0.05)?  Or should we change the API to work in natural units (time)?  Note that doing so would require introducing frame rate parameters (sr, hop_length) that otherwise don't need to be there.

**Comment by keunwoochoi** [comment]
Or `s=0.057`? :) 
With a clear documentation, I think either `0.057` or `0.0571`, or whatever looks ugly but is matched to the paper would be fine, assuming the document would explain the meaning.

I also think it makes sense to use natural units. One thing I concern is if users would understand all `s` [in time], `sr`, `hop_length` are related and should be correctly set, but this mistake can happen even if we adopt `s=0.0571` or whatever.

**Comment by bmcfee** [comment]
I think I'm inclined to leave it parameterized by `s` so that it more closely resembles the paper.  I'd actually like to rename the parameters to something interpretable, but provide the equation and reference to the paper in docs.

**Comment by bmcfee** [comment]
FWIW, here's what an implementation based on time constant and frame parameters would look like:
```python
def pcen2(E, sr=22050, hop_length=512, alpha=0.98, delta=2, r=0.5, t=0.395, eps=1e-6):
    s = 1 - np.exp(- float(hop_length) / (t * sr))
    M = scipy.signal.lfilter([s], [1, s - 1], E)
    smooth = (eps + M)**(-alpha)
    return (E * smooth + delta)**r - delta**r
```
the magic number `t=0.395` corresponds to the time constant for the paper's implementation, and we infer the `s` parameter.

Otherwise, I'm considering the following renames:

- `delta` => `bias`, or perhaps `offset`
- `r` => `power`
- `alpha` => `gain`

**Comment by bmcfee** [comment]
Side note: fun extension to pcen is to vertically max-filter the reference/smoothing spectrum, similarly to superflux.  Results comparison (log, no max-filter, max_filter=5):

![image](https://user-images.githubusercontent.com/1190540/36431410-857aeb4e-1625-11e8-81e6-7a9478745188.png)

**Comment by f0k** [comment]
> Since it's fairly easy to implement in the static (non-trainable) form, do folks thing it's worth including in librosa?

As this is the first search result when looking for an implementation, it might be interesting to note that the trainable form is also fairly easy to implement, here's a version of PCEN for Lasagne:
https://gist.github.com/f0k/c837bcf0bfde189ca16eab63637839cb
I've used Vincent's formulation in there as well, thanks for the discussion here!

**Comment by 4p0pt0Z** [comment]
Hi all, 

When using the current implementation of the PCEN, I am having artifacts due to the filter initialization: currently the filter is created with `S_smooth = scipy.signal.lfilter([b], [1, b - 1], ref, axis=axis)` where the initial conditions for the filter are not specified, hence initial rest is assumed (see argument `zi` [here](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.signal.lfilter.html))
The initialization to zero of the filter creates artifacts in the first timesteps of the filtered spectrogram, for instance:
![pdaLR_specs](https://user-images.githubusercontent.com/22395788/54381711-b48dc100-468e-11e9-84ae-16e76bb97bd8.png)
The artifacts can be problematic when using the PCEN on short spectrograms. 

In [Wang et al.](https://arxiv.org/abs/1607.05666) the filter initialization is not detailed. Would it be possible to consider changing the filter initialization using the `zi` argument?

Alternatively, I have been using `scipy.signal.filtfilt` instead of `scipy.signal.lfilter` for the filtering operation, which applies the filter forward and backward on the spectrogram. This solves the initialization issue and uses a zero-phase filter, but it is different than in [Wang et al.](https://arxiv.org/abs/1607.05666). It is the third spectrogram in the image obtained by changing `S_smooth = scipy.signal.lfilter([b], [1, b - 1], ref, axis=axis)` to `S_smooth = scipy.signal.filtfilt([b], [1, b - 1], ref, axis=axis, padtype=None)` in the PCEN implementation.
Would you consider adding this as an alternative processing?

Best

**Comment by bmcfee** [comment]
Thanks @4p0pt0Z for the detailed comment here!  There is actually an open issue on pcen initialization (for streaming purposes) #816 , but nobody's taken it up yet.  So any input there would be most welcome.

`filtfilt` could be okay, but I worry about changing the causal interpretation of pcen, as you mention.  (It also changes the attenuation properties of the filter, but i'm less concerned about that overall.)

So yeah, I'm open to any suggestions / extensions on the API here, as long as we can keep it clear how to recover the original version, and what the different modifications do.

**Comment by lostanlen** [comment]
@4p0pt0Z Thank you for reporting this problem. I have noticed this issue before. 
The quick fix, without any change to librosa, is to replicate the signal twice, run PCEN on the concatenated (double) signal, and then trim the result to the latter half.
Of course, it's twice as slow and takes twice the memory but it does the job of initializing zi properly, assuming that your time constant T is small in front of the duration of the signal.
Long term, we do want an initialization of `zi` that is better that silence. My current thinking is to use a per-frequency temporal average of the signal, localized to a relatively small bit (of the order of T) near the beginning of the signal. The downside (with respect to initializing with silence) is that PCEN will not be causal anymore. The upside is that the artifiacts will disappear. And PCEN can potentially "catch up" with real time later in the signal (i.e after T), so that latency of T is only present for the first T frames.

I hope this helps!

**Comment by bmcfee** [comment]
I don't think we need to reopen this issue, since filter iniitalization is already covered by #816 .

**Comment by f0k** [comment]
@4p0pt0Z: What I did in my implementation was to simply initialize with the first frame rather than zeros:
https://gist.github.com/f0k/c837bcf0bfde189ca16eab63637839cb#file-pcenlayer-py-L52
I'd argue that this is a good enough initial estimate on the momentary magnitudes, at least much closer to the truth than zeros and still causal.

**Comment by 4p0pt0Z** [comment]
Thanks for the answers and suggestions everyone.
The way I understand it, to initialize the filter to something that plays nice with the first frames of the spectrogram to process, we need to use some information about that spectrogram, so we must give up the causal interpretation of the pcen (at least for the first frames). 
Then there are many ways to get the information we need to initialize the filter as suggested in this thread:
- Use the entire spectrogram for initialization (work around of @lostanlen)
- Use the first frame of the spectrogram (@f0k implementation)
- Use per-frequency averages of the first frames (@lostanlen proposition)
Maybe someone would have a suggestion on tests to select the best solution out of these ?

@bmcfee : I think the initialization issue is a bit different than #816. To use the PCEN in streaming, there is a need to let the user provide the value of the filter at the previous frame. Here the issue is more an automatic and smarter initialization of the filter for the processing of a new segment without history. Of course both issues require to modify the filter initialization.

**Comment by bmcfee** [comment]
@4p0pt0Z fair enough - though I think it's better to create a new issue for this than to tack onto a previously closed one. (It makes tracking the changelog much easier on my end.)

I'll throw out one more option for initialization (discussed offline with @lostanlen): initialize with the steady state computed by [lfilter_zi](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.signal.lfilter_zi.html#scipy.signal.lfilter_zi).  Here's how it looks:
![image](https://user-images.githubusercontent.com/1190540/54450887-dbe49c80-4727-11e9-9777-e39f1e059aa8.png)

**Comment by Ca-ressemble-a-du-fake** [comment]
Hi,

Thanks for this implementation. Is it possible to output directly a pcen normalized wav file ? I wrote a question on that topic [here](https://github.com/bastibe/python-soundfile/issues/359). Maybe you can answer here or there ;). Thank you!
