### ISSUE TITLE
Logarithmic Filterbank for STFT

### ISSUE THREAD

**Issue by jsleep** [librosa/librosa#623]
This is more of a feature request than a bug, so feel free to send me to a different forum if this is not appropriate. I was trying to see if LibROSA had any filterbanks to tranform an STFT into have representation with logarithmically spaced bins (similar to consant-q). This [paper](https://arxiv.org/abs/1612.05153) comparing CQT and logarthimically spaced STFT shows that there is a benefit to using the logarithmically spaced STFT for automatic music transcription with neural nets.

**Comment by stefan-balke** [comment]
Hey,

currently we have two different log-freq. representations in `librosa`. CQT and one based on IIR-filters (`iirt`).

Deriving log-freq. directly from the STFT is fairly easy. You might wanna check out examples here:
https://github.com/stefan-balke/mpa-exc/tree/master/02_fourier_transform

Also, `madmom` has some triangular-filter based approaches built-in.

**Comment by bmcfee** [comment]
@jsleep if I'm reading that paper correctly, it seems like they're actually using something pretty close to melspectrogram, which we already have.  Specifically, this passage:

![image](https://user-images.githubusercontent.com/1190540/30426244-ec13caca-9910-11e7-8ea0-eb253c6ac82b.png)

refers to a hybrid linear/log FB.  They don't say exactly what they're doing here, or even what kind of filters they're using (what's the window function?), so we don't know for sure how different it is from a melspec.

That said, I would also suggest reading this paper with a bit of skepticism for two reasons: 1) the dataset (MAPS) is quite small and lacks variability; 2) their comparison conflates the basis with amplitude scaling.  Since their model architecture does not appear to include any explicit scale correction on the input layer, linear or log amplitude can have a huge effect.  They only tested log amplitude on the stft-based method though, so it's hard to know what exactly is going on.

**Comment by jsleep** [comment]
@stefan-balke  Thanks for the examples. Re-reading the paper, they are actually using the `madmom` library to compute the log filtered STFT, so I can look at these things to see how to do it myself.

@bmcfee  You're totally right in that this paper is vague about details, it was mostly focused on the deep learning side of things and definitely glosses over parameters of the spectrogram. 

I feel content closing this with the information you both have given me.
