### ISSUE TITLE
example gallery isn't linked from the documentation sidebar

### ISSUE THREAD

**Issue by choldgraf** [librosa/librosa#649]
I don't see a link to the example gallery anywhere on the main documentation page: https://librosa.github.io/librosa/index.html

It made me think that such a gallery did not exist, until I found the link at the end of the tutorial. So I guess I have two questions:

1. Why not link to the example gallery in the sidebar?
2. Why have the example gallery in a totally separate domain? Why not include in the build of the librosa docs? This way you'd get things like function backreference linking for free.

A related 3rd question is why not turn your tutorial into a python script that sphinx-gallery can parse, that way you can include outputs / viz for the various steps in the tutorial.

If you're friendly to some or all of these points, I could try putting together a PR for this

**Comment by bmcfee** [comment]
The short answer to both questions is that the gallery was added later, and the documentation builds are synchronized with the latest stable release, so I haven't made the time to integrate them yet.

A slightly more involved answer is that the doc build is horrendously slow right now because of all the examples in the docstrings.  CI builds (via readthedocs) are out of the question because it would time out, and doctr doesn't seem stable enough yet to put in our critical path.  As a result, I build docs on my own machine at each release, and the whole process takes several hours.  For a while, the example gallery was updating pretty sporadically (and rapidly), so it didn't make much sense to tie the two.  That might be different now.



> A related 3rd question is why not turn your tutorial into a python script that sphinx-gallery can parse, that way you can include outputs / viz for the various steps in the tutorial.

:+1: 



> If you're friendly to some or all of these points, I could try putting together a PR for this

:+1: :heavy_multiplication_x: :100: !

**Comment by bmcfee** [comment]
Merging #668 migrated the gallery to the main documentation.  It will deploy once the release candidate goes out.

As future work, we could migrate the older example notebooks into sphinx_gallery now.

**Comment by choldgraf** [comment]
ah very cool - this was on my "if I ever get an extra hour" to-do list, nice to see it got done :-)
