### ISSUE TITLE
No Backends

### ISSUE THREAD

**Issue by sissoso** [librosa/librosa#650]
#### Description
Problem when i'm trying to run librosa.load with librosa.util.example_audio_file.

#### Code
import numpy as np
import matplotlib as plt
import librosa as lib
import IPython.display as ipd

import soundfile as sf
import os
import pandas as pd

y, sr = lib.load(lib.util.example_audio_file(), duration=5.0)

#### The error
voiceBengin\venv\lib\site-packages\audioread_init_.py", line 116, in audio_open
raise NoBackendError()
audioread.NoBackendError

#### Versions
pycharm 3.6

I already tried to install ffmpeg but it still doesn't works.

**Comment by sissoso** [comment]
Hey,
I have problem when i am trying to use librosa.load(y, sr = lib.load(lib.util.example_audio_file(), duration=5.0).
It writes to me that the : 
voiceBengin\venv\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError

I already tried to install ffmpeg but it still doesn't works.

**Comment by bmcfee** [comment]
Please fill out the prompts in the issue reporting form (description, steps to reproduce, versions, etc).

**Comment by bmcfee** [comment]
Sorry for the lag, I didn't notice that you updated the issue as requested.

The problem here is within audioread, not librosa, but it's something we see a lot, see  #589 .  It's hard to diagnose exactly since you didn't provide platform information (operating system, dependency versions, etc), but you appear to be on windows?  Maybe try installing gstreamer and PyGObject (as linked from the audioread page: https://github.com/beetbox/audioread )?
