### ISSUE TITLE
Constant Q filterbank with not hop_size=k*2^(n_octaves - 1)

### ISSUE THREAD

**Issue by Rikorose** [librosa/librosa#658]
#### Description
I need a specific hop size which corresponds to a time domain of e.g. 10 ms.
I used the deprecated [logfrequency filter](http://librosa.github.io/librosa/0.4.3/_modules/librosa/filters.html#logfrequency) because of the hop size restriction of the Constant Q filter.

What can I do to not use the deprecated function? Is re-sampling of the signal an option, so that k*2^(n_octaves - 1) corresponds to 10 ms?

#### Steps/Code to Reproduce
Example:
```py
>>> import librosa
>>> sr = 44100
>>> y, sr = librosa.load(librosa.util.example_audio_file(), sr=sr)
>>> librosa.core.cqt(y, sr=sr, hop_length=sr/100)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/librosa/core/constantq.py", line 226, in cqt
    .format(n_octaves - 1, n_octaves))
librosa.util.exceptions.ParameterError: hop_length must be a positive integer multiple of 2^6 for 7-octave CQT

```

#### Versions
```py
>>> import platform; print(platform.platform())
Linux-4.14.11-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
>>> import sys; print("Python", sys.version)
Python 3.6.3 (default, Oct  9 2017, 12:07:10) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.13.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 0.19.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.5.1

```

**Comment by bmcfee** [comment]
There are a couple of problems here:

- You're using float division `sr/100` instead of int division `sr//100`, which will cause a problem in python 3.
- The requirement of `k*2**(n_octaves - 1)` exists so that recursive downsampling inside CQT retains frame alignment.  There is an issue #418 to relax this requirement, but it's a pretty substantial restructuring of the algorithm, so we haven't taken it on yet.

If you're using this for feature extraction (ie on cqt magnitude spectra), one solution would be to sample it at a smaller (valid) hop length, and then interpolate out the time points that you want, using `scipy.interp.interp1d`.  This is a pretty dirty hack, but it should work.

Alternately, as you suggest, you can up-sample your signal before cqt.

**Comment by Rikorose** [comment]
Thanks for answering! 

Interpolating is not possible for me because of a high `n_octaves`, so maybe I'll go with the resampling.

I close this, since there already is #418.
