### ISSUE TITLE
Looking forward the function write_mp3

### ISSUE THREAD

**Issue by agangzz** [librosa/librosa#664]
As we known, librosa has a function write_wav, though write_mp3 is very easy to implement in python,  librosa with the function write_mp3 would be more convenient. 
Thanks

**Comment by stefan-balke** [comment]
Hi,

currently, we use `scipy.io.wavfile.write()` for writing WAVs which does not support other formats.
The problem is that many codecs are not free and thus need to be installed separately on the user side.
Building this into `librosa` in a clean way would probably take too much time which could be spent better in improving the algorithms.

However, for input/output of various kinds of audio formats, you can use `pysoundfile` 
http://pysoundfile.readthedocs.io/en/0.9.0/

- Stefan

**Comment by bmcfee** [comment]
@agangzz in general, I'd like to reduce the amount of IO that librosa supports, not expand it.  IO is a complex enough problem that it's better handled by other, stand-alone packages (eg audioread or pysoundfile).  We provide `write_wav` for convenience, but I don't want to go much further than that.

As @stefan-balke says, pysoundfile is a great option for IO across many formats.  Unfortunately, it does not yet support mp3, but it appears that there's a PR in the works to libsndfile that will make this possible in the future.
