### ISSUE TITLE
there are different output for different input parameters of get_duration 

### ISSUE THREAD

**Issue by xinyanliang** [librosa/librosa#686]
#### Description

There are different output for different input parameters of get_duration 
#### Steps/Code to Reproduce

```
import librosa
import os

# data can be download from https://pan.baidu.com/s/1spsAdsg3zEcd79dzJ0aokg
audio_path = os.path.join('data','s4_f3chi_an1.avi')
y,sr = librosa.load(audio_path)
print(librosa.get_duration(filename=audio_path))
print(librosa.get_duration(y=y,sr=sr))
```

#### Expected Results

3.2
3.2
#### Actual Results

3.2
4.056009070294785
#### Versions

Windows-10-10.0.15063-SP0
Python 3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 13:41:13) [MSC v.1900 64 bit (AMD64)]
NumPy 1.14.0
SciPy 0.19.1
librosa 0.5.1

**Comment by bmcfee** [comment]
That's interesting -- thanks for reporting it.

I can confirm this behavior on the file you provided, but I think the problem is with the file itself, and not librosa.

I get the following output from `ffprobe`:
```
$ ffprobe s4_f3chi_an1.avi 
ffprobe version 3.4.1 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 4.8.2 (GCC) 20140120 (Red Hat 4.8.2-15)
  configuration: --prefix=/home/bmcfee/miniconda/envs/py35 --disable-doc --enable-shared --enable-static --extra-cflags='-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC -I/home/bmcfee/miniconda/envs/py35/include' --extra-cxxflags='=-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC' --extra-libs='-L/home/bmcfee/miniconda/envs/py35/lib -lz' --enable-pic --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --enable-libfreetype --enable-gnutls --enable-libx264
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, avi, from 's4_f3chi_an1.avi':
  Duration: 00:00:03.20, start: 0.000000, bitrate: 24256 kb/s
    Stream #0:0: Video: cinepak (cvid / 0x64697663), rgb24, 720x480, 22532 kb/s, 30 fps, 30 tbr, 30 tbn, 30 tbc
    Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/s
```
Which confirms your 3.2 number.  However, when I load the video in a player (vlc, totem, etc), the duration is approximately 4 seconds.

A bit of background:

The `filename=` mode uses `audioread` to get the duration of the file, which may be done by probing header data and without decoding the entire stream -- if the header information is incorrect for some reason, then so will the duration reported by audioread and librosa.  This is why you see 3.2 when the `filename=` parameter is used.  The y/sr mode uses the already-decoded signal, and just does the appropriate calculation `len(y) / sr`.

In general, I would trust the second mode (`y=y, sr=sr`) more than the first (`filename=`) because it operates on the decoded buffer, rather than the header information.  If that value turns out to be incorrect, it's probably because the signal itself is incorrect, not `get_duration`.  Having loaded the signal and played it back, it doesn't seem to have any erroneous fragments at the end, so I think the problem lies with the header information in the file itself.

**Comment by lostanlen** [comment]
How long does it take to decode the buffer? In other words, how dire is the tradeoff between usability and numerical efficiency?

As a user I would expect an error, or at least a warning,  if there is a non-negligible discrepancy between:
1. `print(librosa.get_duration(filename=audio_path))` and 
2. `print(librosa.get_duration(y=y,sr=sr))`.

This means that the both prototypes should execute both pieces of code:
A. read the header and
B. measure length in samples.

Whereas currently 1 falls back to A and 2 falls back to B.
The downside is that it makes 1 as slow as 2.

Maybe we can preserve the distinction between A and B by means of a kwarg?

**Comment by bmcfee** [comment]
> How long does it take to decode the buffer? In other words, how dire is the tradeoff between usability and numerical efficiency?

Pretty bad, especially if there's a resample-on-load.

Given that this thread was triggered by what I believe to be a corrupted file, I'm not too concerned about putting sophisticated error detection into the library just to catch this sort of bug.

More generally, it would be good to punt downstream to `pysoundfile`, which also provides header-based duration info.
