### ISSUE TITLE
PCEN should support target axes

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#703]
#### Description

Right now, PCEN is hard-coded to operate on the last axis (temporal), with optional max-filtering on the first axis (frequency).  This fits the default behavior of librosa, but it would be nice to support overrides as well, especially when dealing with DL frameworks that expect time on the first axis.

This could be easily resolved by adding an `axis=` parameter that passes through to `lfilter`, and a `max_axis=` parameter to pass-through to `ndimage.maximum_filter1d`.

**Comment by lostanlen** [comment]
Yes, this is needed. `axis` is `None or int or tuple of ints, optional`, like in numpy ?

**Comment by lostanlen** [comment]
Yes, this is needed.
There is something to be said about multi-channel recordings though — where by channel I mean e.g. stereo, not channel as frequency subband like the "C" in PCEN.
If the input `E` is a tensor `E[c, f, t]` (channel `c`, frequency `f`, and time `t`) if the keyword argument `mono` is set to `False`, I could see why the user would want a temporal average `M` that is shared across channels, i.e. `M[f,t]` rather than `M[c,f,t]`, so that the definition of multi-channel PCEN is
`PCEN = (delta + E[c,f,t] / (eps + M[f,t])^alpha )^r - delta^r`
where the quotient is broadcasted over `c`.
Perhaps it does not fit the scope of the issue, and it might be difficult to document clearly, but it's worth keeping in mind as it implements binaural auditory masking.
The original paper by Wang et al. is monaural so the behavior of PCEN over binaural data is not yet defined.

**Comment by bmcfee** [comment]
Hmm.  I would generally expect all normalization to be channel-dependent.

Would it be sensible to extend the api to support a user-supplied reference spectrum?  Or is that overkill?

**Comment by bmcfee** [comment]
Ok, so how do you feel about changing [this block](https://github.com/librosa/librosa/blob/master/librosa/core/spectrum.py#L1444-L1447) to something like:

```python
if ref_spec is None:
    if max_size == 1:
        ref_spec = S
    else:
        ref_spec = scipy.ndimage.maximum_filter1d(S, max_size, axis=0)
```

I wonder if it also makes sense to generalize [superflux](https://github.com/librosa/librosa/blob/master/librosa/onset.py#L525-L528) accordingly?  Or factor a helper function out to eliminate duplicate code?

Then, the max-filtering logic can be tweaked to operate over a target axis as described above.  We have to be a little careful in the implementation there, since inferring the target non-temporal axis is undefined when `ndim>2`.
