### ISSUE TITLE
Librosa Trim vs SOX Trim

### ISSUE THREAD

**Issue by PetrochukM** [librosa/librosa#722]
#### Description

Help with Librosa trim and understanding it.

#### Steps/Code to Reproduce

```
import librosa

trimmed, _ = librosa.effects.trim(signal)
plot_waveform([trimmed[:1000]])
print(librosa.get_duration(signal), librosa.get_duration(trimmed))
```

#### Expected Results

Expecting the first ~400 samples to be trimmed.

#### Actual Results

![image](https://user-images.githubusercontent.com/7424737/40856140-a1aae4ee-658b-11e8-86b5-4a9b3ce22556.png)
```6.195238095238095 6.195238095238095```

#### Versions

Darwin-17.5.0-x86_64-i386-64bit
Python 3.6.5 (default, May 15 2018, 11:11:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
NumPy 1.14.3
SciPy 1.1.0
librosa 0.6.0

**Comment by PetrochukM** [comment]
Hi There, again!

I ran the same script with ``sox``. The result was quite different: 
![image](https://user-images.githubusercontent.com/7424737/40857575-63e6b700-6590-11e8-8f92-8f700d6b27da.png)

Looks it trimmed a bunch off.

**Comment by bmcfee** [comment]
This is a bit difficult to diagnose without access to the original signal.

For clarification, what `trim` does is clip off frames at the beginning or end of the clip where the rmse is significantly below the reference value.  By default, the reference value is the max over all frames, and the threshold for "significant" is 60dB.  The framing parameters are aligned to the library defaults (n=2048, hop=512).  In your case, it looks like there's enough energy in the first frame (2048 samples) to keep it above the threshold.  If you want to narrow the analysis, you can drop the frame length (say, 512)  and hop length (say 128) and that should give your expected behavior.

**Comment by PetrochukM** [comment]
Sample:
[LJ035-0174.wav.zip](https://github.com/librosa/librosa/files/2063927/LJ035-0174.wav.zip)

**Comment by PetrochukM** [comment]
```
import librosa

trimmed, _ = librosa.effects.trim(signal, frame_length=128, hop_length=32)
plot_waveform([trimmed[:1000]])
print(librosa.get_duration(signal), librosa.get_duration(trimmed))
```

Tried to edit the parameters as you suggested, and the result did not change:
![image](https://user-images.githubusercontent.com/7424737/40860333-d9a3a42c-6599-11e8-9b0d-699b86e16281.png)

**Comment by bmcfee** [comment]
I looked at your wav file, and it seems like the issue is that the amplitude range is just below the threshold where that bit would be cut:

```python
In [5]: y, sr = librosa.load('LJ035-0174.wav', sr=None)

In [6]: rmse = librosa.feature.rmse(y=y, frame_length=256, hop_length=64)[0]

In [7]: librosa.power_to_db(rmse**2, ref=np.max)
Out[7]: 
array([-58.33159 , -57.541306, -57.580276, ..., -54.477257, -60.306374,
       -59.16532 ], dtype=float32)
```
Meaning that your quiet frames are ~58dB below the reference, but the cutoff is 60.  You can either change the reference (say, use `ref=1`):
```python
In [11]: librosa.power_to_db(rmse**2, ref=1)
Out[11]: 
array([-68.277245, -67.48696 , -67.52593 , ..., -64.42291 , -70.25203 ,
       -69.11098 ], dtype=float32)
```
or move the threshold (say, `top_db=55`):
```python
In [12]: ytrim, _ = librosa.effects.trim(y, frame_length=256, hop_length=64, top_db=55)

In [13]: librosa.get_duration(y=ytrim, sr=sr)
Out[13]: 6.176507936507937

In [14]: librosa.get_duration(y=y, sr=sr)
Out[14]: 6.195238095238095
```

**Comment by PetrochukM** [comment]
@bmcfee Thank you! That worked well. Appreciate your time.
