### ISSUE TITLE
Incorrect documentation for librosa.core.spectrum.istft() function?

### ISSUE THREAD

**Issue by wooters** [librosa/librosa#724]
I'm not sure if this is an actual "issue" or just an indication of my lack of understanding, but it _seems_ like the documentation for `librosa.core.spectrum.istft()` may be incorrect.

The documentation [in the code](https://github.com/librosa/librosa/blob/master/librosa/core/spectrum.py#L195) indicates that the function operates by minimizing mean squared error as described in Griffin & Lim. But I don't think that's what is going on in this function.

**Comment by bmcfee** [comment]
@r9y9 might be the best person to respond to this.  My read is that since it explicitly says it takes a "complex-valued spectrogram", the MSE minimization is only relating to window modulation and not phase retrieval.  (@r9y9 please correct me if this is mistaken!)

I suppose this could be worded more carefully -- any suggestions would be welcome.

**Comment by r9y9** [comment]
Reading Griffin & Lim's paper ([PDF link](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.306.7858&rep=rep1&type=pdf)) again, I think it's correct. See section 2 of their paper (eq. (4) ~ (6)). Any suggestions for wording are welcome though. 

MSE minimization is not about phase retrieval, which might be confusing since Grifin & lim algorithm often reffered as a phase reconstruction algorithm.

**Comment by wooters** [comment]
Ah, that makes sense. As you guessed, I was confused because I was focusing on the phase-reconstruction aspect of Griffin & Lim's algorithm. Thanks!

**Comment by bmcfee** [comment]
Seems like that clears up the confusion.  The docs could be improved for this though, so I'll leave it open as a beginner issue.

**Comment by lostanlen** [comment]
What is indeed puzzling in the documentation is that it cites the Griffin-Lim paper, which is mostly reknowned today as a phase retrieval paper, with the algorithm in Figure 1 ("the Griffin-Lim algorithm"). Yet, `librosa.core.spectrum.istft` only uses the elements of the paper up to Section 2 ("reconstruction from MSTFT). It might be good to reference Section 2 specifically.

If you tag this issue as 0.6.3 I can write a spiel about that in the docs.
