### ISSUE TITLE
Question about y_frames computed in librosa.core.spectrum.stft() function

### ISSUE THREAD

**Issue by funcwj** [librosa/librosa#733]
#### Description

I noticed that `y_frames` in librosa.core.spectrum.stft() is computed by
```python
y_frames = util.frame(y, frame_length=n_fft, hop_length=hop_length)
```
when `win_length` is smaller than `n_fft`(for example, in asr task, `win_length`=400, `n_fft`=512) and `center` flag is `False`, it seems got fewer frames than expected(often missing last frame).

**Comment by bmcfee** [comment]
That's strange -- I don't think win_length should have a measurable effect on the number of frames.

Can you please fill out the full issue template, and include a minimal example demonstrating this behavior and the expected output?

**Comment by funcwj** [comment]
```python
import librosa
import numpy as np 

def test():
    num_samples = 10000
    frame_length = 400
    frame_shift = 160
    x = np.random.rand(N)
    y = librosa.stft(x, n_fft=512, hop_length=frame_shift, win_length=frame_length, center=False)
    print('expected: {} vs {}'.format(int((num_samples - frame_length) / frame_shift) + 1, y.shape[1]))

if __name__ == "__main__":
    test()
```
And output:
```
expected: 61 vs 60
```

**Comment by bmcfee** [comment]
Ah, I think there's some confusion of terminology here.

``win_length`` is the length of the effective window applied to a frame.  It can be smaller than the frame length (``nfft`` in this context), which is useful when you want to over-sample in frequency.

The correct calculation here would be ``1 + (num_samples - nfft) // frame_shift)``, which gives 60 as you observe.  Librosa is behaving according to specification here, though it may not agree with your initial expectations.

That said, there are a couple of open issues surrounding framing, windowing, and centering, that might be relevant to your interests, and your input on these would be most welcome.  See #596 and #695.

**Comment by bmcfee** [comment]
Great.  Are we okay to close this out then?

**Comment by funcwj** [comment]
OK, thanks a lot.

**Comment by mlinxiang** [comment]
@funcwj  i am a lit confuse of follow frame len compute code , if (len(y) - frame_length) is exact division hop_length， then the extra +1 will be unnecessary，alway have a lit difference of other library result
![image](https://user-images.githubusercontent.com/6283983/56207096-7c5c1280-6080-11e9-8947-63c4c12c12e0.png)

**Comment by bmcfee** [comment]
> if (len(y) - frame_length) is exact division hop_length， then the extra +1 will be unnecessary

That's incorrect.  If y is exactly one frame, then `len(y) - frame_length = 0 < n_frames = 1`.

**Comment by zlinsmile** [comment]
> 
> 
> ```python
> import librosa
> import numpy as np 
> 
> def test():
>     num_samples = 10000
>     frame_length = 400
>     frame_shift = 160
>     nfft = 512
>     x = np.random.rand(num_samples)
>     y = librosa.stft(x, n_fft=nfft, hop_length=frame_shift, win_length=frame_length, center=False)
>     print('expected: {} vs {}'.format(int((num_samples - frame_length) / frame_shift) + 1, y.shape[1]))
> 
> if __name__ == "__main__":
>     test()
> ```
> 
> And output:
> 
> ```
> expected: 61 vs 60
> ```

excuse me, 
when I use librosa.stft(x, n_fft=512, hop_length=frame_shift, win_length=400, center=False)
or librosa.stft(x, n_fft=512, hop_length=frame_shift, win_length=512, center=False)
I get the same frame size, I think the win_length doesn't work, 
and the win_length is equal to n_fft.
why? How can I fix it?
Thank you：）

**Comment by bmcfee** [comment]
> I get the same frame size, I think the win_length doesn't work,

No, that's correct. `n_fft` determines the number of samples in a frame; `win_length` determines the length (in samples) of the window within the frame.  Setting `win_length < n_fft` zeros out samples beyond the window length but within the frame, and is useful for over-sampling.

**Comment by ardasnck** [comment]
As @funcwj mentioned, I'm having exactly the similar issue, which is getting fewer frames than expected, because of `frame_length = n_fft` in `y_frames = util.frame(y, frame_length=n_fft, hop_length=hop_length)` while computing stft (Similar case as `win_length`=400, `n_fft`=512, `hop_length`=160 and `center`=False).

I was trying to implement Google's VGGish Input Audio Features (See [vggish_input.py](https://github.com/tensorflow/models/blob/fd72a90ef2a3efee3c21d57cc5f03c95a3102d04/research/audioset/vggish/vggish_input.py) and [mel_features.py](https://github.com/tensorflow/models/blob/master/research/audioset/vggish/mel_features.py)) with librosa and faced this problem. Number of frames are calculated as 
`num_samples`=16000

`num_frames = 1 + int(np.floor((num_samples - window_length) / hop_length))`

instead of 

`1 + (num_samples - nfft) // frame_shift` , which gives `(98 vs 97)` frames.

I will be very much appreciated if you can give me some solution about this @bmcfee 
Also, seems like @dpwe contributed to VGGish repo and involved in the discussion #695 . His insights would be also very helpful. 
Thanks.

**Comment by dpwe** [comment]
If it’s the 512 nfft vs 400 point win_length, add (512 - 400) zeros to the
end of the waveform before analyzing it.

  DAn.
