### ISSUE TITLE
custom win_length in mfcc computation

### ISSUE THREAD

**Issue by gorinars** [librosa/librosa#767]
This issue is in part discussed in https://github.com/librosa/librosa/issues/595, however, my question is more narrow.

It is quite common in speech processing to have win_length different from n_fft parameter.
As in @JinmingZhao  example:

```
n_fft = 512
win_length = 400 # 0.025*16000
hop_length = 160 # 0.010 * 16000

```

Current API makes impression that it is possible by executing 

`feature.mfcc(y=y, n_fft=512, hop_length=160, win_length=160)
`

Similar to how it is done in stft function.

However, the actual implementation eventually leads to `_spectrogram()` function that always assumes `n_fft=win_length`.

Is there specific reason for such strict requirement? 

If not, we can propose a fix soon.

I also think that other common feature extractors (for example, rmse, centroid, etc.) could be extended with such parameter.

**Comment by bmcfee** [comment]
You're absolutely right.  To be clear, the issue here is that `melspectrogram` does not propagate the window length parameter to `stft`.  It would be easy to change by having a `win_length = kwargs.popdefault('win_length`, None)` in `melspectrogram` and passing that into `_spectrogram`, which should also be expanded to support window length.

In general, the `_spectrogram` function doesn't support all the parameters of `stft`.  I think we originally wanted to limit the scope of that function to the minimal commonly used parameters, and let users construct their own spectrograms if they want anything fancier.  We could revisit that decision if there's sufficient interest or need for that.

**Comment by bmcfee** [comment]
Revisiting this one today, and I'm thinking that we could easily generalize `_spectrogram` to cover almost all of the parameters of `stft`, and propagate those up to the calling functions so that everything can be directly passed through.  The one exception to this is `dtype`, which should be complex in stft, but real in `_spectrogram`, so I'd prefer to not handle precision issues here.  If users really want high precision, they can compute the stft directly and use the `S=` interface.

To recap, the signature for `stft` looks like:
```python
def stft(y, n_fft=2048, hop_length=None, win_length=None, window='hann',
         center=True, dtype=np.complex64, pad_mode='reflect')
```
and the signature for `_spectrogram` looks like:
```python
def _spectrogram(y=None, S=None, n_fft=2048, hop_length=512, power=1):
```
so the missing parameters are `win_length`, `window`, `center`, and `pad_mode`.  These could be added easily enough here, but if we do that, they will need to be included in the following other functions:
- `pitch.piptrack`
- `feature.spectral_centroid`
- `feature.spectral_bandwidth`
- `feature.spectral_contrast`
- `feature.spectral_rolloff`
- `feature.spectral_flatness`
- `feature.rms`
- `feature.poly_features`
- `feature.chroma_stft`
- `feature.melspectrogram`
- `feature.mfcc` (redundant; kwarg passthru to melspectrogram)

So this would add, at most, 4 parameters to each of these functions (some already expose these), but there are no obvious conflicts with existing parameters.

I do worry about API bloat here, but it seems counter-productive to expose only one of these additional parameters (win_length) and not the others.  Likewise, it seems counter-productive to only add these in mel / mfcc (cf #804), but not the other spectral features.  That is to say, if we do this, it should be all-or-nothing.

Anyone care to chime in before I hack it out?  @stefan-balke @lostanlen ?
