### ISSUE TITLE
Why converting path to "real path" in the load function?

### ISSUE THREAD

**Issue by urinieto** [librosa/librosa#768]
I am trying to load some mp3s in the Google Cloud Platform with `librosa` (which have the following path format: `gs://name_of_bucket/name_of_file`), but the load function transforms the input path into something that does not really exist.

What is the reason of having `os.path.realpath(path)` in https://github.com/librosa/librosa/blob/master/librosa/core/audio.py#L112?

Thanks!

**Comment by bmcfee** [comment]
IIRC this was originally put in for the sake of pkg_resources and the example audio file.  But you may be right that it's not necessary.  I worry that it may depend on which backend audioread selects to load the file (which is environment and codec-dependent), so it might not be easy to test.

Do you want to hack it out and see if it still works, and if so, send a PR to remove the realpath conversion?

**Comment by bmcfee** [comment]
I'm looking into this now, and I'm not sure we can do anything here without also pushing some changes up to audioread.  Going through the various backends:

- ffmpeg backend calls out to a pipe and uses `-i` (which is interpreted as input file path)
- gstreamer backend prepends `'file://'` to the path (and abspath's it anyway)
- macca uses abspath
- mad takes the raw path and hands it pymad
- rawread takes the raw path

So the behavior is not really consistent here.  We can probably drop realpath in librosa, but it won't fix your problem.

OTOH, pysoundfile can do virtual IO (see https://librosa.github.io/librosa/ioformats.html#read-file-like-objects ), and that *will* fix your problem as long as you can get a file handle to your google bucket.  But you won't be able to load mp3s, because it's libsndfile.  Bit of a bummer!

**Comment by urinieto** [comment]
Thanks for looking into this. I found a workaround by just downloading a copy of the mp3 from the GCS bucket and then using librosa on the local file in one of the workers.
