### ISSUE TITLE
Allow user-provided reference values in piptrack

### ISSUE THREAD

**Issue by pvanlaar** [librosa/librosa#776]
#### Description
During the computation of chroma features, a warning is given that the frequency set is empty. The warning originated from line 150 of core/pitch.py from the `pitch_tuning` function. 
~~~python
if not np.any(frequencies):
        `warnings.warn('Trying to estimate tuning from empty frequency set.')
~~~
After some debugging I found that the problem lies in the `piptrack` function (line 171 of core/pitch.py) in the following part of the code (line 271 of core/pitch.py)
~~~python
    # Clip to the viable frequency range
    freq_mask = ((fmin <= fft_freqs) & (fft_freqs < fmax)).reshape((-1, 1))

    # Compute the column-wise local max of S after thresholding
    # Find the argmax coordinates
    idx = np.argwhere(freq_mask &
                      util.localmax(S * (S > (threshold * S.max(axis=0)))))
~~~

The frequency range is limited by the frequency mask, but the threshold is 0.1 times the maximum of all frequencies. If that peak is too high, no local peaks will be found on no pitches will be returned.

#### Steps/Code to Reproduce
~~~python
from librosa.core import piptrack
from numpy.random import random, randint

n_fft = 512

sampleRate = 24000
signal = random(n_fft) + randint(0, 3, n_fft)
signal[400:] = signal[400:] + 500  #create high amplitudes for high frequencies

pitches, mags = piptrack(fmin=150, fmax=4000, sr=sampleRate, 
                                         S=signal.reshape(-1, 1), n_fft=512, threshold=0.1, 
                                         hop_length=n_fft)
~~~
#### Expected Results
Non empty pitches

#### Actual Results
~~~python
sum(pitches) == 0
sum(mags) == 0
~~~

#### Versions
Linux-4.4.0-138-generic-x86_64-with-debian-jessie-sid
('Python', '2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19) \n[GCC 7.2.0]')
('NumPy', '1.13.3')
('SciPy', '1.0.0')
('librosa', '0.6.0')

**Comment by bmcfee** [comment]
This seems like expected behavior to me, at least for the example you provide.

The randomly generated synthetic spectrum in your example looks like a step function with minor fluctuations:
![image](https://user-images.githubusercontent.com/1190540/47944266-dd2bd000-ded0-11e8-8226-d4117203b64d.png)

Audio with such a spectrum would certainly not sound pitched in any meaningful sense, so a reasonable pitch estimator should return an empty set here.  For this specific algorithm, it's looking for parabolic peaks (local maxima) in the spectrum, and since there aren't any that are sufficiently peaky, it makes sense that the result is empty.

You do have a point that thresholding based on relative amplitude against the maximum within frame is maybe not a great strategy.  I suppose what you'd really want is a threshold that adapts to masking frequencies.  Maybe @craffel has thoughts on this?

**Comment by craffel** [comment]
It feels to me that when fed a non-pitched audio signal `piptrack` should not return any frequencies. 

> You do have a point that thresholding based on relative amplitude against the maximum within frame is maybe not a great strategy. I suppose what you'd really want is a threshold that adapts to masking frequencies. Maybe @craffel has thoughts on this?

Do you mean masking frequencies as in auditory masking? I'm not 100% clear on what you're suggesting.

**Comment by lostanlen** [comment]
@pvanlaar I suppose that this issue started with real-world music signals, not a synthetic audio wave like the one you give in our MWE? can you describe the type of music in which you encountered this problem?

**Comment by bmcfee** [comment]
> Do you mean masking frequencies as in auditory masking? I'm not 100% clear on what you're suggesting.

Yeah, that's roughly what I had in mind.

**Comment by craffel** [comment]
That would be cool but it feels a little out-of-scope, since computing masking thresholds is by no means straightforward (and, in fact, requires finding "peaks" in the spectrum, so there's a bit of a chicken-and-egg problem).

**Comment by bmcfee** [comment]
Yeah, agreed.

I still think it might be useful to generalize the threshold computation here, possibly following the pattern used in `amplitude_to_db`?  That is, provide a `ref` function or value (which is currently the frame-wise maximum).

**Comment by craffel** [comment]
You mean instead of providing `threshold` you could provide a function which takes S as input and returns an array of the same shape corresponding to the threshold? I could see that being useful, though it's probably only important if it's a use-case people want to use it for -- I still think the correct behavior for the example that started this issue is to return "no frequencies", regardless of what the threshold is set to.

**Comment by bmcfee** [comment]
> I still think the correct behavior for the example that started this issue is to return "no frequencies", regardless of what the threshold is set to

:+1:

> You mean instead of providing `threshold` you could provide a function which takes S as input and returns an array of the same shape corresponding to the threshold?

Yeah -- mostly I'm thinking this would be nice for API consistency across the package, but it would also allow the piptrack function to generalize to support an `axis` parameter, in case you have differently shaped spectrograms.

**Comment by craffel** [comment]
> Yeah -- mostly I'm thinking this would be nice for API consistency across the package,

Sounds good to me.
