### ISSUE TITLE
file size is different after loading and writing wav file with librosa

### ISSUE THREAD

**Issue by corner100** [librosa/librosa#796]
from
https://stackoverflow.com/questions/53357328/why-is-the-file-size-different-after-loading-and-writing-wav-file-with-librosa

#### Description

down vote
favorite

I am loading a wav file with librosa. after saving the file it is two times bigger. So I load it again and compare it with the original one. Somehow there is a difference. Even if I load it twice and compare it, there is a huge difference between both data.

```
import librosa
wave1, sr1 = librosa.load('go.wav', mono=True, sr=None)
librosa.output.write_wav('go2.wav', wave1, sr1)
librosa.output.write_wav('go3.wav', wave1, sr1)

wave2, sr2 = librosa.load('go2.wav', mono=True, sr=None)
diff12 = sum(abs(wave1-wave2))
wave3, sr3 = librosa.load('go3.wav', mono=True, sr=None)
diff13 = sum(abs(wave1-wave3))
diff23 = sum(abs(wave2-wave3))
```

diff12 = 0.106048583984375

diff13 = 0.102630615234375

diff23 = 0.181884765625

what is the reason that the files are not the same?

**Comment by lostanlen** [comment]
Hello, thank you for reporting this.
I am not exactly sure, but it might be a question of bit depth quantization in the WAV encoding.
We recommend using `scipy.io.wavfile.write` instead of `librosa.output.write_wav` for use cases like this one. This was recently fixed in PR #791, closing #761.
Please let us know what you find.

**Comment by bmcfee** [comment]
It could also be an artifact of accumulating floating point error.  How many samples are in this recording?  Can you report the mean, median, and max of the absolute difference instead of the sum?

**Comment by bmcfee** [comment]
I reimplemented the above code, and am pretty confident that this is just floating point error accumulation.  Since we don't know the number of samples in the input signal, it's hard to tell if the sample-wise error is significant, but on the packaged example audio, I get the following (summing):

```python
>>> diff12
20.67125

>>> diff13
20.67125

>>> diff23
0.0

```
with averaging the error across all samples, I get:
```python
>>> diff12
7.6268216e-06

>>> diff13
7.6268216e-06

>>> diff23
0.0
```

This seems like acceptable error to me.  Unless there are strong objections, I'd like to close this one out.
