### ISSUE TITLE
util.localmax fails when the max is at the first array position

### ISSUE THREAD

**Issue by brianlevis** [librosa/librosa#805]
#### Description

util.localmax returns an indicator array with no true values when the local maximum is located at the first position of a 1D input array. This caused a crash in beat.beat_track->__beat_tracker->__last_beat for me.
#### Steps/Code to Reproduce
```
from librosa.util import localmax
import numpy as np

print(localmax(np.array([2, 1])))
print(localmax(np.array([1, 2])))
```

#### Expected Results
```
[ True False]
[False  True]
```

#### Actual Results
```
[False False]
[False  True]
```

#### Versions
Darwin-18.2.0-x86_64-i386-64bit
Python 3.7.1 (default, Nov  6 2018, 18:46:03) 
[Clang 10.0.0 (clang-1000.11.45.5)]
NumPy 1.15.4
SciPy 1.2.0
librosa 0.6.2

**Comment by bmcfee** [comment]
Thanks for noting this.  I think this is expected, but non-documented behavior.  The localmax logic is, roughly:

x[i] > x[i-1]  and  x[i] >= x[i+1]

So the first entry will never count as a local max because its preceding value is undefined.  This is demonstrated in the example use cases in the [docs](https://librosa.github.io/librosa/generated/librosa.util.localmax.html?highlight=localmax#librosa.util.localmax).

I'll tag this as a doc issue, since the docstring really should explain the expected behavior rather than just provide examples.
