### ISSUE TITLE
Reading wave from memory

### ISSUE THREAD

**Issue by loretoparisi** [librosa/librosa#865]
There is a fork of `audioreader` that can read a wave file directly from memory like here https://github.com/jksinton/littlesleeper2/blob/master/littlesleeper.py#L453

So like

```python 
print "Processing MP3 queue buffer\n"
        # this is essentially a while-true loop
        for mp3data, timestamp in StreamBufferReader(self.queue_read):
            t1 = time.time() # start time used to calculate loop processing time below

            signaldata = None
            timestamp_str = timestamp.strftime("%Y-%m-%d %H:%M:%S.%f")
            try:
                signaldata = audioread.decode(StringIO(mp3data))
            except (audioread.NoBackendError, audioread.ffdec.ReadTimeoutError):
                print timestamp_str,"\tDecode error. Setting default value."
```

It is it possible to add a new interface to `librosa.open` to support this streaming mode?
See here about this https://github.com/beetbox/audioread/issues/53

**Comment by bmcfee** [comment]
Thanks for noting this.

Since #845 (and merging #847) , we're deprioritizing audioread backends (and hope to drop it entirely at some point).  Soundfile already supports this kind of streaming directly, and we have documentation illustrating how to do it [here](https://librosa.github.io/librosa/ioformats.html#read-file-like-objects), so I don't see a real need for adding this functionality.  Unless I'm misunderstanding your comment?

**Comment by loretoparisi** [comment]
@bmcfee awesome, I did not know about that, let me check it should work!

**Comment by loretoparisi** [comment]
@bmcfee in my case I was using `mp3` files to feed the `audioread`, how to load it `soundfile` if possibile?

**Comment by bmcfee** [comment]
> I was using `mp3` files to feed the `audioread`, how to load it when using `soundfile`

That's not possible yet because `libsndfile` doesn't have mp3 support.  There is an open (but languishing) pull request to add mp3 support to libsndfile now that the patent is no longer enforced, but last I checked, it still needs quite a bit of work.  Once that gets merged, then everything should work directly via the soundfile interface.

In the meantime, I'd prefer to not add more I/O special-casing to librosa; if you really need this functionality for mp3, I recommend using audioread directly.

**Comment by loretoparisi** [comment]
@bmcfee yes of course due to patents issues it makes sense. Okay thank you I think using `soundfile` it is enough for this issue, thank you. The mp3 decoding to wav can be done in a different way.
