### ISSUE TITLE
Dropping python 2.7 support?

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#896]
Python 2.7 is rapidly approaching EOL (2020-01-01).  Accordingly, many of our dependencies will be dropping python 2 support:

- Numpy's policy is [here](https://docs.scipy.org/doc/numpy-1.14.2/neps/dropping-python2.7-proposal.html).  We currently depend on 1.15, but 1.17 and up require python 3.
- Matplotlib (soft dependency) dropped py2 support from version 3 onwards.
- Many more projects listed [here](https://python3statement.org/).

Since it seems like we'll be forced to drop 2.7 support in the near future anyway, we may as well make a concrete plan.

I think it makes sense to have 0.7 be the last release to officially support python 2.7, and plan for 0.8 to be released some time in 2020 and py3 only.

There isn't much we'd have to do on the code end -- we use six in a few places to maintain compatibility, and that can stay put.  Mainly, our use of six comes down to python-internal things (checking for callables, decorator manipulation, etc).  Additionally, we have one small bit of py2 logic in the setup script to work around importlib issues.  It might be nice to clean these things up going forward.

Does this sound good?

**Comment by AlexMetsai** [comment]
Since virtually everyone is dropping Python 2 support, it seems like the obvious thing to do. Even if supporting python 2 does not consume a lot of resources, like in your case, there won't be any point in maintaining since nobody will be using it. But more importantly, like you're saying, librosa's dependencies will drop support as well.
 I tend to avoid Python 2 like the Devil avoids holy water (sic), but I do understand that some people needed it. And that's why the EOL was pushed so far away in the first place. Inevitably though, that date is coming closer and closer.
I'm definitely no expert in maintaining open source projects (or any project if you ask me). But dropping python 2 seems natural. Plus, its users get to enjoy another release of librosa that supports it.

**Comment by stefan-balke** [comment]
Yes, I'm fine with dropping it by 2020.

**Comment by lostanlen** [comment]
I'm fine with it too. I would be in favor of posting the OP on librosa's google group though, for maximal visibility wrt the community of users.

**Comment by lostanlen** [comment]
closed by #903
