### ISSUE TITLE
inconsistent/double calculation of tuning in cqt

### ISSUE THREAD

**Issue by jongwook** [librosa/librosa#925]
#### Description
When the `tuning` argument of `librosa.cqt()` is `None`, it estimates tuning by [calling `estimate_tuning()`](https://github.com/librosa/librosa/blob/0.7.0/librosa/core/constantq.py#L174-L175) to find the tuning and [calls `cqt_frequencies()`](https://github.com/librosa/librosa/blob/0.7.0/librosa/core/constantq.py#L178-L179).

1. The call to `estimate_tuning()` uses its default argument `bins_per_octave=12` always, but the call to `cqt_frequencies()` uses the `bins_per_octave` argument given to `cqt()`. This makes [the frequency correction term](https://github.com/librosa/librosa/blob/0.7.0/librosa/core/time_frequency.py#L957) different from the intended tuning, by a factor of `12 / bins_per_octave`.

2. Furthermore, `cqt()` calls `__cqt_filter_fft` with `fmin_t` in which the [tuning correction is already applied](https://github.com/librosa/librosa/blob/0.7.0/librosa/core/constantq.py#L178-L181), and in `constant_q` [the correction is applied once again](https://github.com/librosa/librosa/blob/0.7.0/librosa/filters.py#L512-L513). So the tuning correction is twice larger than it should be.

#### Steps/Code to Reproduce

This example uses a sound that is 42 cents above the standard A440 tuning. `estimate_tuning` returns 0.43 (which is close enough).

```
import numpy as np
import librosa

sr = 22050
fmin = librosa.note_to_hz('Ab4')
freq = librosa.note_to_hz('A4') * 2 ** (42 / 1200)  # 42 cent above A440
t = np.linspace(0, 1, sr, endpoint=False)
y = np.sin(2 * np.pi * freq * t)
print(np.abs(librosa.cqt(y, sr, fmin=fmin, n_bins=7, bins_per_octave=36, tuning=None))[:, 10])
```

#### Expected Results
If the tuning is correctly identified, the CQT spectrum would be symmetric around the peak.

#### Actual Results
The spectrum is not symmetric and the peak lies somewhere between the 4th and 5th bin.

`[ 0.05483014  0.67865918  5.63108114 22.61531804 19.71375346  3.43137636
  0.56649648]`

#### Workaround

To apply a certain `tuning` value, I can instead give `(tuning / 2) * (bins_per_octave / 12)`, dividing by 2 to compensate for the double calculation and multiplying by `bins_per_octave / 12` to compensate for the incorrect `estimate_tuning()` call.

So if I run the following instead:

`print(np.abs(librosa.cqt(y, sr, fmin=fmin, n_bins=7, bins_per_octave=36, tuning=0.63))[:, 10])`

I get a symmetric spectrum:

`[ 0.07743703  0.08895902 12.56089353 24.92553951 12.64337768  0.22712318
  0.11059439]`

#### Versions

```
Linux-4.15.0-54-generic-x86_64-with-debian-buster-sid
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
NumPy 1.16.4
SciPy 1.3.0
librosa 0.7.0
```

I think it'd be better if tuning is always defined in terms of 'fractions of a bin' and avoid using the term 'cents' altogether, as it's confusing with the music theory term (a 100th of a semitone)

**Comment by bmcfee** [comment]
Thanks for the thorough report.

I agree with your recommendation that `estimate_tuning` explicitly documents its output as being in fractions of a "bin", not cents.  Then we can just change the call from within cqt to propagate the BPO variable and things will be consistent.  (We should document that bpo=12 and resolution=0.01 produces units of cents.)





>     2\. urthermore, `cqt()` calls `__cqt_filter_fft` with `fmin_t` in which the [tuning correction is already applied](https://github.com/librosa/librosa/blob/0.7.0/librosa/core/constantq.py#L178-L181), and in `constant_q` [the correction is applied once again](https://github.com/librosa/librosa/blob/0.7.0/librosa/filters.py#L512-L513).

Good catch, I hadn't noticed that.  This is almost certainly an artifact of numerous refactorings over the years.  I think it would work to simply remove the `tuning` parameter from `cqt_filter_fft`, and assume that all tuning is accounted for when determining `fmin`, but it will take some thorough detective work to make sure of it.

As an aside: this got me thinking more generally about tuning in the library.  There are two other problems with it that I'd like to address in the 0.8 release, and it might be helpful to start thinking about them in conjunction with this issue:

1. tuning specification is not consistent.  Sometimes we have cents, sometimes we have fractions of a bin, and sometimes we have a reference A440.  As @jongwook suggests, I think fractions of a bin is the most sensible and general format here, so we should standardize on that.  In 0.7.1, I'd like to deprecate the A440= parameters wherever they appear (chroma filters, mainly, for historical reasons), and remove them in 0.8.

2. The tuning estimation algorithm we have is extremely naive, and doesn't correctly account for harmonics.  I do try to keep pre-trained models with baked-in parameters out of the library, but I think we could do something smarter here.  (This is a much larger issue, and need not be rolled in with the above, but it's worth thinking about.)

**Comment by bmcfee** [comment]
Update:

I've started digging into this, and discovering that it's much more delicate than I'd originally thought due to the inter-dependence of all the functions.  Taking notes here, mainly for my own benefit, but they could be useful for others down the road.

- Definitionally, I think the only sane way to approach this is that the CQT is defined to start at base frequency `fmin * 2**(tuning / bins_per_octave)`.  This isn't exactly how cqt is documented though, so we'll need to do a thorough audit of the cqt module (and related functions in display) to make sure that it's all consistent.
- Right now, the tuning parameter is spread all over the place, and this is the source of our problem.  Probably the best thing to do is push all the tuning correction logic up to the front, and remove `tuning` as a parameter from the cqt filter construction functions.  (This can go through a deprecation cycle.)  This way, it becomes the responsibility of the caller (ie, cqt, icqt, hybrid_cqt, pseudocqt, etc) to correctly determine fmin before asking for the filter bank, and the filter bank functions can be a bit simpler.
- Taking the above step also simplifies some of the hairier parts of, say, `hybrid_cqt`, where the basis is constructed in pieces and used differently.

Once the CQT bits are sorted out, I'll set about deprecating `A440` parameters and standardizing `tuning=` across the board.  Those will all be rolled into the same PR.

Tuning estimation improvements will be a separate PR.
