### ISSUE TITLE
Idea: Add path for audio file as part of Warnings and errors

### ISSUE THREAD

**Issue by 21kc-caracol** [librosa/librosa#936]
Hi,

while using:
    wav_data, sampling_rate = librosa.load(wav_path, duration=5)
 <lines of code with feature extraction, for example:>
    feature_wav_spec_cent = librosa.feature.spectral_centroid(y=wav_data, sr=sampling_rate)
    zcr = librosa.feature.zero_crossing_rate(wav_data)
   ...
   ...
I'm getting the next warning:

> Trying to estimate tuning from empty frequency set.

I've read about this warning here, but I couldn't understand why the warning doesn't include the path/filename for easier debugging?

If I'm looping over thousands of WAV's ...such information could be great...

thanks in advance...
-Kc.

**Comment by lostanlen** [comment]
Hello @21kc-caracol, welcome to librosa.

You raise a fair point about the need to inspect the path of a file which causes a warning. The problem is that we can't print this information directly where the warning is raised:
https://github.com/librosa/librosa/blob/781e8eeea8f793d217c11df11e2c6766ee1e7d70/librosa/core/pitch.py#L146

This is because  `pitch_tuning` only has access to the `frequencies` array, not to the waveform itself, let alone the `wav_path`. Note that, in your code, you supply `wav_data`, not `wav_path` as an argument.

Is there a workaround? Yes, definitely. But it needs to happen in your code.


```python
import librosa
import numpy as np
import warnings

wav_paths = [librosa.util.example_audio_file()]
sampling_rate = 22050

for wav_path in wav_paths:
    # NB: we set the audio duration to 0.01 seconds to purposefully
    # trigger the warning: "Trying to estimate tuning from empty frequency set."
    # Replace duration by a larger number (e.g., 1.0 second) to
    # obtain a well-defined tuning estimate.
    wav_data, _ = librosa.load(wav_path, sampling_rate, duration=1.0)
    with warnings.catch_warnings(record=True) as feature_warnings:
        ch = librosa.feature.chroma_stft(y=wav_data, sr=sampling_rate)
        for feature_warning in feature_warnings:
            print("Warning: {} Triggered in:\n {}\n".format(
                feature_warning.message, wav_path))
```

**Comment by 21kc-caracol** [comment]
thank you, it did work and I also learned how to log warnings ..
