### ISSUE TITLE
mp3 loading fails

### ISSUE THREAD

**Issue by nomota** [librosa/librosa#945]
y, sr = librosa.load("my.mp3")

Traceback (most recent call last):
  File "/home/esperanto/anaconda3/lib/python3.6/site-packages/librosa/core/audio.py", line 127, in load
    with sf.SoundFile(path) as sf_desc:
  File "/home/esperanto/anaconda3/lib/python3.6/site-packages/soundfile.py", line 627, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/esperanto/anaconda3/lib/python3.6/site-packages/soundfile.py", line 1182, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/esperanto/anaconda3/lib/python3.6/site-packages/soundfile.py", line 1355, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'my.mp3': File contains data in an unknown format.

#### Versions

Linux-4.4.0-17763-Microsoft-x86_64-with-debian-jessie-sid
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0]
NumPy 1.16.4
SciPy 1.1.0
librosa 0.7.0

**Comment by lostanlen** [comment]
Hello @nomota, please read this: https://github.com/librosa/librosa#audioread-and-mp3-support


To fuel `audioread` with more audio-decoding power (e.g., for reading MP3 files),
you may need to install either *ffmpeg* or *GStreamer*.

*Note that on some platforms, `audioread` needs at least one of the programs to work properly.*

If you are using Anaconda, install *ffmpeg* by calling
```
conda install -c conda-forge ffmpeg
```

If you are not using Anaconda, here are some common commands for different operating systems:

* Linux (apt-get): `apt-get install ffmpeg` or `apt-get install gstreamer1.0-plugins-base gstreamer1.0-plugins-ugly`
* Linux (yum): `yum install ffmpeg` or `yum install gstreamer1.0-plugins-base gstreamer1.0-plugins-ugly`
* Mac: `brew install ffmpeg` or `brew install gstreamer`
* Windows: download binaries from this [website]( https://gstreamer.freedesktop.org/) 

For GStreamer, you also need to install the Python bindings with 
```
pip install pygobject
```

**Comment by paraclete-pizza** [comment]
The support text lostanlen shared unfortunately doesn't seem to work for Windows machines (or is missing key steps). Installation of the GStreamer binaries does not solve the issue, and the pip command to install pygobject elicits an error. At present, at least on Windows, it looks like Librosa can't parse MP3s.

**Comment by bmcfee** [comment]
> At present, at least on Windows, it looks like Librosa can't parse MP3s.

It definitely can, we include this in our windows platform continuous integration tests.

If it's not working on your installation, there is a problem with the upstream decoding libraries (audioread -> ffmpeg).  Be sure to follow the installation instructions carefully.

**Comment by paraclete-pizza** [comment]
That gives me some hope! Though I've been hitting my head against this problem for days, now,

Are there installation instructions anywhere that I could "follow carefully" to install ffmpeg? The instructions above from the Librosa git only cover GStreamer, and, as noted, the required pip installation of pygobject generates an error (an enormous, multi-screen error, headed with "ERROR: Command errored out with exit status 1:" that Google has not helped with).

If ffmpeg is a viable alternative to GStreamer for Windows, I haven't found installation instructions that have successfully helped it interface with Python. Just the usual instructions to download ffmpeg to a directory and add it to Windows Path. But when followed carefully, they still don't seem to affect my Librosa scripts' ability to parse MP3s.

On your Windows tests, are you using ffmpeg rather than GStreamer? I feel like I've gotten better at untangling the various dependency knots across different Python versions, and managing installation of packages, but this has had me stymied for a while now (and I'm working with large enough file sets that I can't just convert them all to ogg to make them work)!

**Comment by bmcfee** [comment]
> On your Windows tests, are you using ffmpeg rather than GStreamer?

Yes, the relevant parts of our Appveyor setup are the following:
https://github.com/librosa/librosa/blob/4b827ce9b2ff5221792dc069b601bef18d9eacb4/appveyor.yml#L16-L24

Lines 17-22 create the conda environment, line 23 installs ffmpeg via conda-forge, and line 24 installs the remaining dependencies needed for testing.

Note that this is all from the main development branch.  If you're using the packaged version, the following ought to suffice:

```
conda install -c conda-forge ffmpeg librosa
```

**Comment by its-just-jo** [comment]
I'm getting this error even with ffmpeg installed via anaconda.

Are there any other solutions?
