### ISSUE TITLE
util.valid_audio validates non-Fortran contiguous arrays

### ISSUE THREAD

**Issue by lostanlen** [librosa/librosa#964]
#### Description
Raised during CR of #960 which cl0sed #959.
https://github.com/librosa/librosa/pull/960#issuecomment-521862461

Last time we updated `valid_audio` was #616 which cl0sed #612

#### Steps/Code to Reproduce

```python
from librosa import util
import numpy as np

y = np.zeros(1000)
print(util.valid_audio(y))

y_strided = np.zeros(1000)[::2]
print(util.valid_audio(y_strided))

y_clang = np.zeros(1000).reshape(2, 500)
print(util.valid_audio(y_clang, mono=False))

y_fortran = np.asfortranarray(
    np.zeros(1000).reshape(2, 500))
print(util.valid_audio(y_fortran, mono=False))

y_fortran_colon = y_fortran[:]
print(util.valid_audio(y_fortran_colon, mono=False))
```

#### Expected Results
```python
True
False
False
True
True
```

#### Actual Results
```python
True
True
True
True
True
```

#### Versions
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.4 (default, Aug  9 2019, 12:36:10) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.16.4
SciPy 1.3.1
librosa 0.7.0
```

**Comment by lostanlen** [comment]
@bmcfee I will write a PR tomorrow if you confirm that this is indeed the expected result.

**Comment by bmcfee** [comment]
Confirmed, please do!

**Comment by bmcfee** [comment]
One thought about this: what should happen if `to_mono` is called with a discontiguous, 1-d input?

Right now, it's a no-op: data will be returned as-is.  The change proposed here will turn it into an error, because step 1 is validation.

Maybe to_mono should explicitly make the data contiguous?  Then you could do something like `to_mono(y[0])` (to carve out the left channel of a stereo mix).  Or, we could extend the api a bit to allow channel selection: `to_mono(y, channel=0)` (select out the 0 channel).  The default would be `channel=None`, which averages over all channels (despite the recent [twitter thread](https://twitter.com/jordiponsdotme/status/1158149501661540354)).

**Comment by lostanlen** [comment]
Yes, this seems like a good API to have. And yes, we need the output of `to_mono` (or any function that produces a wave, really) to pass `valid_audio`!

**Comment by bmcfee** [comment]
Great.  Can we roll changes to `to_mono` into this issue as well?
