### ISSUE TITLE
how to understand the librosa.stft ?

### ISSUE THREAD

**Issue by ucasiggcas** [librosa/librosa#984]
Dear,
if I use the 1024 samples into the librosa.stft with
`x=np.random.randn(1024)`
`stft=librosa.stft(x,1024,256)`
`stft.shape`
`(513, 5)`

so how to undertand the **5** ?

if I use tf.signal.stft, the result is not the same.
`stft2=tf.signal.stft(x,frame_length=1024,frame_step=256)`
`with tf.Session() as sess:
    stft2=sess.run(stft2)
    print(stft2.shape)`
`(1, 513)`

so what's wrong ?where is difference ?

Thanks

**Comment by bmcfee** [comment]
The librosa stft uses frame-centered analysis by default.  To do this, the signal is padded by half a frame so that the first frame is centered around sample 0.  The padded signal then has enough samples to support 5 frames when your hop is 256 samples.

The tensorflow stft does not pad, so you only get one frame worth of analysis.
