### ISSUE TITLE
This should be win_length

### ISSUE THREAD

**Issue by risajef** [librosa/librosa#992]
In my opinion `frame_length` should be `win_length` as it refers to time.

https://github.com/librosa/librosa/blob/679a6a958d4df1b32c47d8ee811bb09ef1650338/librosa/core/spectrum.py#L220

Tensorflow also uses the frame_length.
https://github.com/tensorflow/tensorflow/blob/38ef1a2febf6532666b52a1000f48ac0f6ba8b5d/tensorflow/python/ops/signal/spectral_ops.py#L83

**Comment by bmcfee** [comment]
No, that would not be correct.  We allow `win_length` to be less than `n_fft` to facilitate frequency over-sampling (by zero-padding the frame).  Using the window length for the frame would eliminate the option to zero-pad.

It might be possible to achieve comparable effects by overriding the `n` parameter in `fft` downstream, and using the shorter window length that you describe, but I'm wary of phase differences due to centered vs left-aligned padding.

**Comment by lostanlen** [comment]
Hello @risajef, thank you for reporting this.

I agree that `frame_length` and `win_length` express different things and that the kwarg in `frame` needs to be called `frame_length` in this case.

@bmcfee detailed the motivation behind that design choice above very well already, so i'm going to close this issue. Feel free to reopen if need be.
